
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AccordionDemo: typeof import("../app/components/content/AccordionDemo.vue")['default']
export const AvatarDemo: typeof import("../app/components/content/AvatarDemo.vue")['default']
export const BreadcrumbsDemo: typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']
export const ComponentPreview: typeof import("../app/components/content/ComponentPreview.vue")['default']
export const DocPreview: typeof import("../app/components/content/DocPreview.vue")['default']
export const FeatureLinkListDemo: typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']
export const FilterSidebarDemo: typeof import("../app/components/content/FilterSidebarDemo.vue")['default']
export const LiveCode: typeof import("../app/components/content/LiveCode.vue")['default']
export const PaginationDemo: typeof import("../app/components/content/PaginationDemo.vue")['default']
export const ProgressIndicatorDemo: typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']
export const PropsTable: typeof import("../app/components/content/PropsTable.vue")['default']
export const ProsePre: typeof import("../app/components/content/ProsePre.vue")['default']
export const SideNavDemo: typeof import("../app/components/content/SideNavDemo.vue")['default']
export const DocsLayout: typeof import("../app/components/DocsLayout.vue")['default']
export const ProseA: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ContentRenderer: typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const AgDsAccordion: typeof import("agds-vue")['AgDSAccordion']
export const AgDsAccordionItem: typeof import("agds-vue")['AgDSAccordionItem']
export const AgDsAppLayout: typeof import("agds-vue")['AgDSAppLayout']
export const AgDsAppLayoutFooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
export const AgDsAppLayoutFooterDivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
export const AgDsAppLayoutHeader: typeof import("agds-vue")['AgDSAppLayoutHeader']
export const AgDsAppLayoutSidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
export const AgDsAppLayoutSidebarNav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
export const AgDsAutocomplete: typeof import("agds-vue")['AgDSAutocomplete']
export const AgDsAvatar: typeof import("agds-vue")['AgDSAvatar']
export const AgDsBox: typeof import("agds-vue")['AgDSBox']
export const AgDsBreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
export const AgDsBreadcrumbsItem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
export const AgDsButton: typeof import("agds-vue")['AgDSButton']
export const AgDsButtonLink: typeof import("agds-vue")['AgDSButtonLink']
export const AgDsCallout: typeof import("agds-vue")['AgDSCallout']
export const AgDsCallToActionButton: typeof import("agds-vue")['AgDSCallToActionButton']
export const AgDsCallToActionLink: typeof import("agds-vue")['AgDSCallToActionLink']
export const AgDsCard: typeof import("agds-vue")['AgDSCard']
export const AgDsCardFooter: typeof import("agds-vue")['AgDSCardFooter']
export const AgDsCardHeader: typeof import("agds-vue")['AgDSCardHeader']
export const AgDsCardInner: typeof import("agds-vue")['AgDSCardInner']
export const AgDsCardLink: typeof import("agds-vue")['AgDSCardLink']
export const AgDsCheckbox: typeof import("agds-vue")['AgDSCheckbox']
export const AgDsCheckboxGroup: typeof import("agds-vue")['AgDSCheckboxGroup']
export const AgDsCollapsingSideBar: typeof import("agds-vue")['AgDSCollapsingSideBar']
export const AgDsColumn: typeof import("agds-vue")['AgDSColumn']
export const AgDsColumns: typeof import("agds-vue")['AgDSColumns']
export const AgDsCombobox: typeof import("agds-vue")['AgDSCombobox']
export const AgDsComboboxAsync: typeof import("agds-vue")['AgDSComboboxAsync']
export const AgDsComboboxAsyncMulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
export const AgDsComboboxMulti: typeof import("agds-vue")['AgDSComboboxMulti']
export const AgDsContent: typeof import("agds-vue")['AgDSContent']
export const AgDsContentBleed: typeof import("agds-vue")['AgDSContentBleed']
export const AgDsCore: typeof import("agds-vue")['AgDSCore']
export const AgDsCoreProvider: typeof import("agds-vue")['AgDSCoreProvider']
export const AgDsDatePicker: typeof import("agds-vue")['AgDSDatePicker']
export const AgDsDetails: typeof import("agds-vue")['AgDSDetails']
export const AgDsDirectionButton: typeof import("agds-vue")['AgDSDirectionButton']
export const AgDsDirectionLink: typeof import("agds-vue")['AgDSDirectionLink']
export const AgDsDivider: typeof import("agds-vue")['AgDSDivider']
export const AgDsDrawer: typeof import("agds-vue")['AgDSDrawer']
export const AgDsDropdownMenu: typeof import("agds-vue")['AgDSDropdownMenu']
export const AgDsDropdownMenuButton: typeof import("agds-vue")['AgDSDropdownMenuButton']
export const AgDsDropdownMenuDivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
export const AgDsDropdownMenuGroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
export const AgDsDropdownMenuItem: typeof import("agds-vue")['AgDSDropdownMenuItem']
export const AgDsDropdownMenuItemLink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
export const AgDsDropdownMenuItemRadio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
export const AgDsDropdownMenuPanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
export const AgDsExternalLinkCallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
export const AgDsFeatureLinkList: typeof import("agds-vue")['AgDSFeatureLinkList']
export const AgDsFeatureLinkListItem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
export const AgDsField: typeof import("agds-vue")['AgDSField']
export const AgDsFieldContainer: typeof import("agds-vue")['AgDSFieldContainer']
export const AgDsFieldHint: typeof import("agds-vue")['AgDSFieldHint']
export const AgDsFieldLabel: typeof import("agds-vue")['AgDSFieldLabel']
export const AgDsFieldMessage: typeof import("agds-vue")['AgDSFieldMessage']
export const AgDsFieldset: typeof import("agds-vue")['AgDSFieldset']
export const AgDsFileUpload: typeof import("agds-vue")['AgDSFileUpload']
export const AgDsFilterSidebar: typeof import("agds-vue")['AgDSFilterSidebar']
export const AgDsFlex: typeof import("agds-vue")['AgDSFlex']
export const AgDsFooter: typeof import("agds-vue")['AgDSFooter']
export const AgDsFooterDivider: typeof import("agds-vue")['AgDSFooterDivider']
export const AgDsFormStack: typeof import("agds-vue")['AgDSFormStack']
export const AgDsGlobalAlert: typeof import("agds-vue")['AgDSGlobalAlert']
export const AgDsGroupedFields: typeof import("agds-vue")['AgDSGroupedFields']
export const AgDsHeader: typeof import("agds-vue")['AgDSHeader']
export const AgDsHeading: typeof import("agds-vue")['AgDSHeading']
export const AgDSH1: typeof import("agds-vue")['AgDSH1']
export const AgDSH2: typeof import("agds-vue")['AgDSH2']
export const AgDSH3: typeof import("agds-vue")['AgDSH3']
export const AgDSH4: typeof import("agds-vue")['AgDSH4']
export const AgDSH5: typeof import("agds-vue")['AgDSH5']
export const AgDSH6: typeof import("agds-vue")['AgDSH6']
export const AgDsIcon: typeof import("agds-vue")['AgDSIcon']
export const AgDsInpageNav: typeof import("agds-vue")['AgDSInpageNav']
export const AgDsLinkList: typeof import("agds-vue")['AgDSLinkList']
export const AgDsLinkListItem: typeof import("agds-vue")['AgDSLinkListItem']
export const AgDsListItem: typeof import("agds-vue")['AgDSListItem']
export const AgDsLoadingBlanket: typeof import("agds-vue")['AgDSLoadingBlanket']
export const AgDsMainNav: typeof import("agds-vue")['AgDSMainNav']
export const AgDsModal: typeof import("agds-vue")['AgDSModal']
export const AgDsNotificationBadge: typeof import("agds-vue")['AgDSNotificationBadge']
export const AgDsOrderedList: typeof import("agds-vue")['AgDSOrderedList']
export const AgDsPageAlert: typeof import("agds-vue")['AgDSPageAlert']
export const AgDsPageContent: typeof import("agds-vue")['AgDSPageContent']
export const AgDsPagination: typeof import("agds-vue")['AgDSPagination']
export const AgDsPaginationButtons: typeof import("agds-vue")['AgDSPaginationButtons']
export const AgDsProgressIndicator: typeof import("agds-vue")['AgDSProgressIndicator']
export const AgDsProse: typeof import("agds-vue")['AgDSProse']
export const AgDsRadio: typeof import("agds-vue")['AgDSRadio']
export const AgDsRadioGroup: typeof import("agds-vue")['AgDSRadioGroup']
export const AgDsSearchBox: typeof import("agds-vue")['AgDSSearchBox']
export const AgDsSearchBoxButton: typeof import("agds-vue")['AgDSSearchBoxButton']
export const AgDsSearchBoxInput: typeof import("agds-vue")['AgDSSearchBoxInput']
export const AgDsSearchInput: typeof import("agds-vue")['AgDSSearchInput']
export const AgDsSectionAlert: typeof import("agds-vue")['AgDSSectionAlert']
export const AgDsSectionContent: typeof import("agds-vue")['AgDSSectionContent']
export const AgDsSelect: typeof import("agds-vue")['AgDSSelect']
export const AgDsSideNav: typeof import("agds-vue")['AgDSSideNav']
export const AgDsSkipLinks: typeof import("agds-vue")['AgDSSkipLinks']
export const AgDsStack: typeof import("agds-vue")['AgDSStack']
export const AgDsSubNav: typeof import("agds-vue")['AgDSSubNav']
export const AgDsSummaryList: typeof import("agds-vue")['AgDSSummaryList']
export const AgDsSummaryListItem: typeof import("agds-vue")['AgDSSummaryListItem']
export const AgDsSummaryListItemAction: typeof import("agds-vue")['AgDSSummaryListItemAction']
export const AgDsSummaryListItemDescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
export const AgDsSummaryListItemTerm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
export const AgDsSwitch: typeof import("agds-vue")['AgDSSwitch']
export const AgDsTab: typeof import("agds-vue")['AgDSTab']
export const AgDsTable: typeof import("agds-vue")['AgDSTable']
export const AgDsTableBody: typeof import("agds-vue")['AgDSTableBody']
export const AgDsTableCaption: typeof import("agds-vue")['AgDSTableCaption']
export const AgDsTableCell: typeof import("agds-vue")['AgDSTableCell']
export const AgDsTableHead: typeof import("agds-vue")['AgDSTableHead']
export const AgDsTableHeader: typeof import("agds-vue")['AgDSTableHeader']
export const AgDsTableHeaderSortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
export const AgDsTableRow: typeof import("agds-vue")['AgDSTableRow']
export const AgDsTableScroller: typeof import("agds-vue")['AgDSTableScroller']
export const AgDsTabList: typeof import("agds-vue")['AgDSTabList']
export const AgDsTabPanel: typeof import("agds-vue")['AgDSTabPanel']
export const AgDsTabs: typeof import("agds-vue")['AgDSTabs']
export const AgDsTag: typeof import("agds-vue")['AgDSTag']
export const AgDsTags: typeof import("agds-vue")['AgDSTags']
export const AgDsText: typeof import("agds-vue")['AgDSText']
export const AgDsTextarea: typeof import("agds-vue")['AgDSTextarea']
export const AgDsTextInput: typeof import("agds-vue")['AgDSTextInput']
export const AgDsTextLink: typeof import("agds-vue")['AgDSTextLink']
export const AgDsTextLinkExternal: typeof import("agds-vue")['AgDSTextLinkExternal']
export const AgDsTimeInput: typeof import("agds-vue")['AgDSTimeInput']
export const AgDsTimePicker: typeof import("agds-vue")['AgDSTimePicker']
export const AgDsToggleButton: typeof import("agds-vue")['AgDSToggleButton']
export const AgDsUnorderedList: typeof import("agds-vue")['AgDSUnorderedList']
export const AgDsVisuallyHidden: typeof import("agds-vue")['AgDSVisuallyHidden']
export const NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
export const MDC: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAccordionDemo: LazyComponent<typeof import("../app/components/content/AccordionDemo.vue")['default']>
export const LazyAvatarDemo: LazyComponent<typeof import("../app/components/content/AvatarDemo.vue")['default']>
export const LazyBreadcrumbsDemo: LazyComponent<typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']>
export const LazyComponentPreview: LazyComponent<typeof import("../app/components/content/ComponentPreview.vue")['default']>
export const LazyDocPreview: LazyComponent<typeof import("../app/components/content/DocPreview.vue")['default']>
export const LazyFeatureLinkListDemo: LazyComponent<typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']>
export const LazyFilterSidebarDemo: LazyComponent<typeof import("../app/components/content/FilterSidebarDemo.vue")['default']>
export const LazyLiveCode: LazyComponent<typeof import("../app/components/content/LiveCode.vue")['default']>
export const LazyPaginationDemo: LazyComponent<typeof import("../app/components/content/PaginationDemo.vue")['default']>
export const LazyProgressIndicatorDemo: LazyComponent<typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']>
export const LazyPropsTable: LazyComponent<typeof import("../app/components/content/PropsTable.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../app/components/content/ProsePre.vue")['default']>
export const LazySideNavDemo: LazyComponent<typeof import("../app/components/content/SideNavDemo.vue")['default']>
export const LazyDocsLayout: LazyComponent<typeof import("../app/components/DocsLayout.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyContentRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyAgDsAccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
export const LazyAgDsAccordionItem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
export const LazyAgDsAppLayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
export const LazyAgDsAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
export const LazyAgDsAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
export const LazyAgDsAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
export const LazyAgDsAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
export const LazyAgDsAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
export const LazyAgDsAutocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
export const LazyAgDsAvatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
export const LazyAgDsBox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
export const LazyAgDsBreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
export const LazyAgDsBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
export const LazyAgDsButton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
export const LazyAgDsButtonLink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
export const LazyAgDsCallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
export const LazyAgDsCallToActionButton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
export const LazyAgDsCallToActionLink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
export const LazyAgDsCard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
export const LazyAgDsCardFooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
export const LazyAgDsCardHeader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
export const LazyAgDsCardInner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
export const LazyAgDsCardLink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
export const LazyAgDsCheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
export const LazyAgDsCheckboxGroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
export const LazyAgDsCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
export const LazyAgDsColumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
export const LazyAgDsColumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
export const LazyAgDsCombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
export const LazyAgDsComboboxAsync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
export const LazyAgDsComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
export const LazyAgDsComboboxMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
export const LazyAgDsContent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
export const LazyAgDsContentBleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
export const LazyAgDsCore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
export const LazyAgDsCoreProvider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
export const LazyAgDsDatePicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
export const LazyAgDsDetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
export const LazyAgDsDirectionButton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
export const LazyAgDsDirectionLink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
export const LazyAgDsDivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
export const LazyAgDsDrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
export const LazyAgDsDropdownMenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
export const LazyAgDsDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
export const LazyAgDsDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
export const LazyAgDsDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
export const LazyAgDsDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
export const LazyAgDsDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
export const LazyAgDsDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
export const LazyAgDsDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
export const LazyAgDsExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
export const LazyAgDsFeatureLinkList: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
export const LazyAgDsFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
export const LazyAgDsField: LazyComponent<typeof import("agds-vue")['AgDSField']>
export const LazyAgDsFieldContainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
export const LazyAgDsFieldHint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
export const LazyAgDsFieldLabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
export const LazyAgDsFieldMessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
export const LazyAgDsFieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
export const LazyAgDsFileUpload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
export const LazyAgDsFilterSidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
export const LazyAgDsFlex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
export const LazyAgDsFooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
export const LazyAgDsFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
export const LazyAgDsFormStack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
export const LazyAgDsGlobalAlert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
export const LazyAgDsGroupedFields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
export const LazyAgDsHeader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
export const LazyAgDsHeading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
export const LazyAgDSH1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
export const LazyAgDSH2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
export const LazyAgDSH3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
export const LazyAgDSH4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
export const LazyAgDSH5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
export const LazyAgDSH6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
export const LazyAgDsIcon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
export const LazyAgDsInpageNav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
export const LazyAgDsLinkList: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
export const LazyAgDsLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
export const LazyAgDsListItem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
export const LazyAgDsLoadingBlanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
export const LazyAgDsMainNav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
export const LazyAgDsModal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
export const LazyAgDsNotificationBadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
export const LazyAgDsOrderedList: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
export const LazyAgDsPageAlert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
export const LazyAgDsPageContent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
export const LazyAgDsPagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
export const LazyAgDsPaginationButtons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
export const LazyAgDsProgressIndicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
export const LazyAgDsProse: LazyComponent<typeof import("agds-vue")['AgDSProse']>
export const LazyAgDsRadio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
export const LazyAgDsRadioGroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
export const LazyAgDsSearchBox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
export const LazyAgDsSearchBoxButton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
export const LazyAgDsSearchBoxInput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
export const LazyAgDsSearchInput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
export const LazyAgDsSectionAlert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
export const LazyAgDsSectionContent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
export const LazyAgDsSelect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
export const LazyAgDsSideNav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
export const LazyAgDsSkipLinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
export const LazyAgDsStack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
export const LazyAgDsSubNav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
export const LazyAgDsSummaryList: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
export const LazyAgDsSummaryListItem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
export const LazyAgDsSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
export const LazyAgDsSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
export const LazyAgDsSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
export const LazyAgDsSwitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
export const LazyAgDsTab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
export const LazyAgDsTable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
export const LazyAgDsTableBody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
export const LazyAgDsTableCaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
export const LazyAgDsTableCell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
export const LazyAgDsTableHead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
export const LazyAgDsTableHeader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
export const LazyAgDsTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
export const LazyAgDsTableRow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
export const LazyAgDsTableScroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
export const LazyAgDsTabList: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
export const LazyAgDsTabPanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
export const LazyAgDsTabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
export const LazyAgDsTag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
export const LazyAgDsTags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
export const LazyAgDsText: LazyComponent<typeof import("agds-vue")['AgDSText']>
export const LazyAgDsTextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
export const LazyAgDsTextInput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
export const LazyAgDsTextLink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
export const LazyAgDsTextLinkExternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
export const LazyAgDsTimeInput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
export const LazyAgDsTimePicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
export const LazyAgDsToggleButton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
export const LazyAgDsUnorderedList: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
export const LazyAgDsVisuallyHidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
export const LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyMDC: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
