
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AccordionDemo: typeof import("../app/components/content/AccordionDemo.vue")['default']
export const AutocompleteDemo: typeof import("../app/components/content/AutocompleteDemo.vue")['default']
export const AvatarDemo: typeof import("../app/components/content/AvatarDemo.vue")['default']
export const BreadcrumbsDemo: typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']
export const CheckboxDemo: typeof import("../app/components/content/CheckboxDemo.vue")['default']
export const ComboboxAsyncMultiDemo: typeof import("../app/components/content/ComboboxAsyncMultiDemo.vue")['default']
export const ComboboxDemo: typeof import("../app/components/content/ComboboxDemo.vue")['default']
export const ComponentPreview: typeof import("../app/components/content/ComponentPreview.vue")['default']
export const DatePickerDemo: typeof import("../app/components/content/DatePickerDemo.vue")['default']
export const DocPreview: typeof import("../app/components/content/DocPreview.vue")['default']
export const FeatureLinkListDemo: typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']
export const FilterSidebarDemo: typeof import("../app/components/content/FilterSidebarDemo.vue")['default']
export const LiveCode: typeof import("../app/components/content/LiveCode.vue")['default']
export const PageAlertDemo: typeof import("../app/components/content/PageAlertDemo.vue")['default']
export const PaginationDemo: typeof import("../app/components/content/PaginationDemo.vue")['default']
export const ProgressIndicatorDemo: typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']
export const PropsTable: typeof import("../app/components/content/PropsTable.vue")['default']
export const ProsePre: typeof import("../app/components/content/ProsePre.vue")['default']
export const SectionAlertDemo: typeof import("../app/components/content/SectionAlertDemo.vue")['default']
export const SideNavDemo: typeof import("../app/components/content/SideNavDemo.vue")['default']
export const SkipLinksDemo: typeof import("../app/components/content/SkipLinksDemo.vue")['default']
export const StatusBadgeDemo: typeof import("../app/components/content/StatusBadgeDemo.vue")['default']
export const TagsDemo: typeof import("../app/components/content/TagsDemo.vue")['default']
export const TaskListDemo: typeof import("../app/components/content/TaskListDemo.vue")['default']
export const DocsLayout: typeof import("../app/components/DocsLayout.vue")['default']
export const ProseA: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ContentRenderer: typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const AGDSAccordion: typeof import("agds-vue")['AGDSAccordion']
export const Agdsaccordion: typeof import("agds-vue")['AGDSAccordion']
export const AGDSAccordionItem: typeof import("agds-vue")['AGDSAccordionItem']
export const Agdsaccordionitem: typeof import("agds-vue")['AGDSAccordionItem']
export const AGDSAppLayout: typeof import("agds-vue")['AGDSAppLayout']
export const Agdsapplayout: typeof import("agds-vue")['AGDSAppLayout']
export const AGDSAppLayoutFooter: typeof import("agds-vue")['AGDSAppLayoutFooter']
export const Agdsapplayoutfooter: typeof import("agds-vue")['AGDSAppLayoutFooter']
export const AGDSAppLayoutFooterDivider: typeof import("agds-vue")['AGDSAppLayoutFooterDivider']
export const Agdsapplayoutfooterdivider: typeof import("agds-vue")['AGDSAppLayoutFooterDivider']
export const AGDSAppLayoutHeader: typeof import("agds-vue")['AGDSAppLayoutHeader']
export const Agdsapplayoutheader: typeof import("agds-vue")['AGDSAppLayoutHeader']
export const AGDSAppLayoutSidebar: typeof import("agds-vue")['AGDSAppLayoutSidebar']
export const Agdsapplayoutsidebar: typeof import("agds-vue")['AGDSAppLayoutSidebar']
export const AGDSAppLayoutSidebarNav: typeof import("agds-vue")['AGDSAppLayoutSidebarNav']
export const Agdsapplayoutsidebarnav: typeof import("agds-vue")['AGDSAppLayoutSidebarNav']
export const AGDSAutocomplete: typeof import("agds-vue")['AGDSAutocomplete']
export const Agdsautocomplete: typeof import("agds-vue")['AGDSAutocomplete']
export const AGDSAvatar: typeof import("agds-vue")['AGDSAvatar']
export const Agdsavatar: typeof import("agds-vue")['AGDSAvatar']
export const AGDSBox: typeof import("agds-vue")['AGDSBox']
export const Agdsbox: typeof import("agds-vue")['AGDSBox']
export const AGDSBreadcrumbs: typeof import("agds-vue")['AGDSBreadcrumbs']
export const Agdsbreadcrumbs: typeof import("agds-vue")['AGDSBreadcrumbs']
export const AGDSBreadcrumbsItem: typeof import("agds-vue")['AGDSBreadcrumbsItem']
export const Agdsbreadcrumbsitem: typeof import("agds-vue")['AGDSBreadcrumbsItem']
export const AGDSButton: typeof import("agds-vue")['AGDSButton']
export const Agdsbutton: typeof import("agds-vue")['AGDSButton']
export const AGDSButtonLink: typeof import("agds-vue")['AGDSButtonLink']
export const Agdsbuttonlink: typeof import("agds-vue")['AGDSButtonLink']
export const AGDSCallout: typeof import("agds-vue")['AGDSCallout']
export const Agdscallout: typeof import("agds-vue")['AGDSCallout']
export const AGDSCallToActionButton: typeof import("agds-vue")['AGDSCallToActionButton']
export const Agdscalltoactionbutton: typeof import("agds-vue")['AGDSCallToActionButton']
export const AGDSCallToActionLink: typeof import("agds-vue")['AGDSCallToActionLink']
export const Agdscalltoactionlink: typeof import("agds-vue")['AGDSCallToActionLink']
export const AGDSCard: typeof import("agds-vue")['AGDSCard']
export const Agdscard: typeof import("agds-vue")['AGDSCard']
export const AGDSCardFooter: typeof import("agds-vue")['AGDSCardFooter']
export const Agdscardfooter: typeof import("agds-vue")['AGDSCardFooter']
export const AGDSCardHeader: typeof import("agds-vue")['AGDSCardHeader']
export const Agdscardheader: typeof import("agds-vue")['AGDSCardHeader']
export const AGDSCardInner: typeof import("agds-vue")['AGDSCardInner']
export const Agdscardinner: typeof import("agds-vue")['AGDSCardInner']
export const AGDSCardLink: typeof import("agds-vue")['AGDSCardLink']
export const Agdscardlink: typeof import("agds-vue")['AGDSCardLink']
export const AGDSCheckbox: typeof import("agds-vue")['AGDSCheckbox']
export const Agdscheckbox: typeof import("agds-vue")['AGDSCheckbox']
export const AGDSCheckboxGroup: typeof import("agds-vue")['AGDSCheckboxGroup']
export const Agdscheckboxgroup: typeof import("agds-vue")['AGDSCheckboxGroup']
export const AGDSCollapsingSideBar: typeof import("agds-vue")['AGDSCollapsingSideBar']
export const Agdscollapsingsidebar: typeof import("agds-vue")['AGDSCollapsingSideBar']
export const AGDSColumn: typeof import("agds-vue")['AGDSColumn']
export const Agdscolumn: typeof import("agds-vue")['AGDSColumn']
export const AGDSColumns: typeof import("agds-vue")['AGDSColumns']
export const Agdscolumns: typeof import("agds-vue")['AGDSColumns']
export const AGDSCombobox: typeof import("agds-vue")['AGDSCombobox']
export const Agdscombobox: typeof import("agds-vue")['AGDSCombobox']
export const AGDSComboboxAsync: typeof import("agds-vue")['AGDSComboboxAsync']
export const Agdscomboboxasync: typeof import("agds-vue")['AGDSComboboxAsync']
export const AGDSComboboxAsyncMulti: typeof import("agds-vue")['AGDSComboboxAsyncMulti']
export const Agdscomboboxasyncmulti: typeof import("agds-vue")['AGDSComboboxAsyncMulti']
export const AGDSComboboxMulti: typeof import("agds-vue")['AGDSComboboxMulti']
export const Agdscomboboxmulti: typeof import("agds-vue")['AGDSComboboxMulti']
export const AGDSContent: typeof import("agds-vue")['AGDSContent']
export const Agdscontent: typeof import("agds-vue")['AGDSContent']
export const AGDSContentBleed: typeof import("agds-vue")['AGDSContentBleed']
export const Agdscontentbleed: typeof import("agds-vue")['AGDSContentBleed']
export const AGDSCore: typeof import("agds-vue")['AGDSCore']
export const Agdscore: typeof import("agds-vue")['AGDSCore']
export const AGDSCoreProvider: typeof import("agds-vue")['AGDSCoreProvider']
export const Agdscoreprovider: typeof import("agds-vue")['AGDSCoreProvider']
export const AGDSDatePicker: typeof import("agds-vue")['AGDSDatePicker']
export const Agdsdatepicker: typeof import("agds-vue")['AGDSDatePicker']
export const AGDSDetails: typeof import("agds-vue")['AGDSDetails']
export const Agdsdetails: typeof import("agds-vue")['AGDSDetails']
export const AGDSDirectionButton: typeof import("agds-vue")['AGDSDirectionButton']
export const Agdsdirectionbutton: typeof import("agds-vue")['AGDSDirectionButton']
export const AGDSDirectionLink: typeof import("agds-vue")['AGDSDirectionLink']
export const Agdsdirectionlink: typeof import("agds-vue")['AGDSDirectionLink']
export const AGDSDivider: typeof import("agds-vue")['AGDSDivider']
export const Agdsdivider: typeof import("agds-vue")['AGDSDivider']
export const AGDSDrawer: typeof import("agds-vue")['AGDSDrawer']
export const Agdsdrawer: typeof import("agds-vue")['AGDSDrawer']
export const AGDSDropdownMenu: typeof import("agds-vue")['AGDSDropdownMenu']
export const Agdsdropdownmenu: typeof import("agds-vue")['AGDSDropdownMenu']
export const AGDSDropdownMenuButton: typeof import("agds-vue")['AGDSDropdownMenuButton']
export const Agdsdropdownmenubutton: typeof import("agds-vue")['AGDSDropdownMenuButton']
export const AGDSDropdownMenuDivider: typeof import("agds-vue")['AGDSDropdownMenuDivider']
export const Agdsdropdownmenudivider: typeof import("agds-vue")['AGDSDropdownMenuDivider']
export const AGDSDropdownMenuGroup: typeof import("agds-vue")['AGDSDropdownMenuGroup']
export const Agdsdropdownmenugroup: typeof import("agds-vue")['AGDSDropdownMenuGroup']
export const AGDSDropdownMenuItem: typeof import("agds-vue")['AGDSDropdownMenuItem']
export const Agdsdropdownmenuitem: typeof import("agds-vue")['AGDSDropdownMenuItem']
export const AGDSDropdownMenuItemLink: typeof import("agds-vue")['AGDSDropdownMenuItemLink']
export const Agdsdropdownmenuitemlink: typeof import("agds-vue")['AGDSDropdownMenuItemLink']
export const AGDSDropdownMenuItemRadio: typeof import("agds-vue")['AGDSDropdownMenuItemRadio']
export const Agdsdropdownmenuitemradio: typeof import("agds-vue")['AGDSDropdownMenuItemRadio']
export const AGDSDropdownMenuPanel: typeof import("agds-vue")['AGDSDropdownMenuPanel']
export const Agdsdropdownmenupanel: typeof import("agds-vue")['AGDSDropdownMenuPanel']
export const AGDSExternalLinkCallout: typeof import("agds-vue")['AGDSExternalLinkCallout']
export const Agdsexternallinkcallout: typeof import("agds-vue")['AGDSExternalLinkCallout']
export const AGDSFeatureLinkList: typeof import("agds-vue")['AGDSFeatureLinkList']
export const Agdsfeaturelinklist: typeof import("agds-vue")['AGDSFeatureLinkList']
export const AGDSFeatureLinkListItem: typeof import("agds-vue")['AGDSFeatureLinkListItem']
export const Agdsfeaturelinklistitem: typeof import("agds-vue")['AGDSFeatureLinkListItem']
export const AGDSField: typeof import("agds-vue")['AGDSField']
export const Agdsfield: typeof import("agds-vue")['AGDSField']
export const AGDSFieldContainer: typeof import("agds-vue")['AGDSFieldContainer']
export const Agdsfieldcontainer: typeof import("agds-vue")['AGDSFieldContainer']
export const AGDSFieldHint: typeof import("agds-vue")['AGDSFieldHint']
export const Agdsfieldhint: typeof import("agds-vue")['AGDSFieldHint']
export const AGDSFieldLabel: typeof import("agds-vue")['AGDSFieldLabel']
export const Agdsfieldlabel: typeof import("agds-vue")['AGDSFieldLabel']
export const AGDSFieldMessage: typeof import("agds-vue")['AGDSFieldMessage']
export const Agdsfieldmessage: typeof import("agds-vue")['AGDSFieldMessage']
export const AGDSFieldset: typeof import("agds-vue")['AGDSFieldset']
export const Agdsfieldset: typeof import("agds-vue")['AGDSFieldset']
export const AGDSFileUpload: typeof import("agds-vue")['AGDSFileUpload']
export const Agdsfileupload: typeof import("agds-vue")['AGDSFileUpload']
export const AGDSFilterSidebar: typeof import("agds-vue")['AGDSFilterSidebar']
export const Agdsfiltersidebar: typeof import("agds-vue")['AGDSFilterSidebar']
export const AGDSFlex: typeof import("agds-vue")['AGDSFlex']
export const Agdsflex: typeof import("agds-vue")['AGDSFlex']
export const AGDSFooter: typeof import("agds-vue")['AGDSFooter']
export const Agdsfooter: typeof import("agds-vue")['AGDSFooter']
export const AGDSFooterDivider: typeof import("agds-vue")['AGDSFooterDivider']
export const Agdsfooterdivider: typeof import("agds-vue")['AGDSFooterDivider']
export const AGDSFormStack: typeof import("agds-vue")['AGDSFormStack']
export const Agdsformstack: typeof import("agds-vue")['AGDSFormStack']
export const AGDSGlobalAlert: typeof import("agds-vue")['AGDSGlobalAlert']
export const Agdsglobalalert: typeof import("agds-vue")['AGDSGlobalAlert']
export const AGDSGroupedFields: typeof import("agds-vue")['AGDSGroupedFields']
export const Agdsgroupedfields: typeof import("agds-vue")['AGDSGroupedFields']
export const AGDSHeader: typeof import("agds-vue")['AGDSHeader']
export const Agdsheader: typeof import("agds-vue")['AGDSHeader']
export const AGDSHeading: typeof import("agds-vue")['AGDSHeading']
export const Agdsheading: typeof import("agds-vue")['AGDSHeading']
export const Agdsh1: typeof import("agds-vue")['AGDSH1']
export const Agdsh2: typeof import("agds-vue")['AGDSH2']
export const Agdsh3: typeof import("agds-vue")['AGDSH3']
export const Agdsh4: typeof import("agds-vue")['AGDSH4']
export const Agdsh5: typeof import("agds-vue")['AGDSH5']
export const Agdsh6: typeof import("agds-vue")['AGDSH6']
export const AGDSIcon: typeof import("agds-vue")['AGDSIcon']
export const Agdsicon: typeof import("agds-vue")['AGDSIcon']
export const AGDSInpageNav: typeof import("agds-vue")['AGDSInpageNav']
export const Agdsinpagenav: typeof import("agds-vue")['AGDSInpageNav']
export const AGDSLinkList: typeof import("agds-vue")['AGDSLinkList']
export const Agdslinklist: typeof import("agds-vue")['AGDSLinkList']
export const AGDSLinkListItem: typeof import("agds-vue")['AGDSLinkListItem']
export const Agdslinklistitem: typeof import("agds-vue")['AGDSLinkListItem']
export const AGDSListItem: typeof import("agds-vue")['AGDSListItem']
export const Agdslistitem: typeof import("agds-vue")['AGDSListItem']
export const AGDSLoadingBlanket: typeof import("agds-vue")['AGDSLoadingBlanket']
export const Agdsloadingblanket: typeof import("agds-vue")['AGDSLoadingBlanket']
export const AGDSMainNav: typeof import("agds-vue")['AGDSMainNav']
export const Agdsmainnav: typeof import("agds-vue")['AGDSMainNav']
export const AGDSModal: typeof import("agds-vue")['AGDSModal']
export const Agdsmodal: typeof import("agds-vue")['AGDSModal']
export const AGDSNotificationBadge: typeof import("agds-vue")['AGDSNotificationBadge']
export const Agdsnotificationbadge: typeof import("agds-vue")['AGDSNotificationBadge']
export const AGDSOrderedList: typeof import("agds-vue")['AGDSOrderedList']
export const Agdsorderedlist: typeof import("agds-vue")['AGDSOrderedList']
export const AGDSPageAlert: typeof import("agds-vue")['AGDSPageAlert']
export const Agdspagealert: typeof import("agds-vue")['AGDSPageAlert']
export const AGDSPageContent: typeof import("agds-vue")['AGDSPageContent']
export const Agdspagecontent: typeof import("agds-vue")['AGDSPageContent']
export const AGDSPagination: typeof import("agds-vue")['AGDSPagination']
export const Agdspagination: typeof import("agds-vue")['AGDSPagination']
export const AGDSPaginationButtons: typeof import("agds-vue")['AGDSPaginationButtons']
export const Agdspaginationbuttons: typeof import("agds-vue")['AGDSPaginationButtons']
export const AGDSProgressIndicator: typeof import("agds-vue")['AGDSProgressIndicator']
export const Agdsprogressindicator: typeof import("agds-vue")['AGDSProgressIndicator']
export const AGDSProse: typeof import("agds-vue")['AGDSProse']
export const Agdsprose: typeof import("agds-vue")['AGDSProse']
export const AGDSRadio: typeof import("agds-vue")['AGDSRadio']
export const Agdsradio: typeof import("agds-vue")['AGDSRadio']
export const AGDSRadioGroup: typeof import("agds-vue")['AGDSRadioGroup']
export const Agdsradiogroup: typeof import("agds-vue")['AGDSRadioGroup']
export const AGDSSearchBox: typeof import("agds-vue")['AGDSSearchBox']
export const Agdssearchbox: typeof import("agds-vue")['AGDSSearchBox']
export const AGDSSearchBoxButton: typeof import("agds-vue")['AGDSSearchBoxButton']
export const Agdssearchboxbutton: typeof import("agds-vue")['AGDSSearchBoxButton']
export const AGDSSearchBoxInput: typeof import("agds-vue")['AGDSSearchBoxInput']
export const Agdssearchboxinput: typeof import("agds-vue")['AGDSSearchBoxInput']
export const AGDSSearchInput: typeof import("agds-vue")['AGDSSearchInput']
export const Agdssearchinput: typeof import("agds-vue")['AGDSSearchInput']
export const AGDSSectionAlert: typeof import("agds-vue")['AGDSSectionAlert']
export const Agdssectionalert: typeof import("agds-vue")['AGDSSectionAlert']
export const AGDSSectionContent: typeof import("agds-vue")['AGDSSectionContent']
export const Agdssectioncontent: typeof import("agds-vue")['AGDSSectionContent']
export const AGDSSelect: typeof import("agds-vue")['AGDSSelect']
export const Agdsselect: typeof import("agds-vue")['AGDSSelect']
export const AGDSSideNav: typeof import("agds-vue")['AGDSSideNav']
export const Agdssidenav: typeof import("agds-vue")['AGDSSideNav']
export const AGDSSkipLinks: typeof import("agds-vue")['AGDSSkipLinks']
export const Agdsskiplinks: typeof import("agds-vue")['AGDSSkipLinks']
export const AGDSStack: typeof import("agds-vue")['AGDSStack']
export const Agdsstack: typeof import("agds-vue")['AGDSStack']
export const AGDSStatusBadge: typeof import("agds-vue")['AGDSStatusBadge']
export const Agdsstatusbadge: typeof import("agds-vue")['AGDSStatusBadge']
export const AGDSSubNav: typeof import("agds-vue")['AGDSSubNav']
export const Agdssubnav: typeof import("agds-vue")['AGDSSubNav']
export const AGDSSummaryList: typeof import("agds-vue")['AGDSSummaryList']
export const Agdssummarylist: typeof import("agds-vue")['AGDSSummaryList']
export const AGDSSummaryListItem: typeof import("agds-vue")['AGDSSummaryListItem']
export const Agdssummarylistitem: typeof import("agds-vue")['AGDSSummaryListItem']
export const AGDSSummaryListItemAction: typeof import("agds-vue")['AGDSSummaryListItemAction']
export const Agdssummarylistitemaction: typeof import("agds-vue")['AGDSSummaryListItemAction']
export const AGDSSummaryListItemDescription: typeof import("agds-vue")['AGDSSummaryListItemDescription']
export const Agdssummarylistitemdescription: typeof import("agds-vue")['AGDSSummaryListItemDescription']
export const AGDSSummaryListItemTerm: typeof import("agds-vue")['AGDSSummaryListItemTerm']
export const Agdssummarylistitemterm: typeof import("agds-vue")['AGDSSummaryListItemTerm']
export const AGDSSwitch: typeof import("agds-vue")['AGDSSwitch']
export const Agdsswitch: typeof import("agds-vue")['AGDSSwitch']
export const AGDSTab: typeof import("agds-vue")['AGDSTab']
export const Agdstab: typeof import("agds-vue")['AGDSTab']
export const AGDSTable: typeof import("agds-vue")['AGDSTable']
export const Agdstable: typeof import("agds-vue")['AGDSTable']
export const AGDSTableBody: typeof import("agds-vue")['AGDSTableBody']
export const Agdstablebody: typeof import("agds-vue")['AGDSTableBody']
export const AGDSTableCaption: typeof import("agds-vue")['AGDSTableCaption']
export const Agdstablecaption: typeof import("agds-vue")['AGDSTableCaption']
export const AGDSTableCell: typeof import("agds-vue")['AGDSTableCell']
export const Agdstablecell: typeof import("agds-vue")['AGDSTableCell']
export const AGDSTableHead: typeof import("agds-vue")['AGDSTableHead']
export const Agdstablehead: typeof import("agds-vue")['AGDSTableHead']
export const AGDSTableHeader: typeof import("agds-vue")['AGDSTableHeader']
export const Agdstableheader: typeof import("agds-vue")['AGDSTableHeader']
export const AGDSTableHeaderSortable: typeof import("agds-vue")['AGDSTableHeaderSortable']
export const Agdstableheadersortable: typeof import("agds-vue")['AGDSTableHeaderSortable']
export const AGDSTableRow: typeof import("agds-vue")['AGDSTableRow']
export const Agdstablerow: typeof import("agds-vue")['AGDSTableRow']
export const AGDSTableScroller: typeof import("agds-vue")['AGDSTableScroller']
export const Agdstablescroller: typeof import("agds-vue")['AGDSTableScroller']
export const AGDSTabList: typeof import("agds-vue")['AGDSTabList']
export const Agdstablist: typeof import("agds-vue")['AGDSTabList']
export const AGDSTabPanel: typeof import("agds-vue")['AGDSTabPanel']
export const Agdstabpanel: typeof import("agds-vue")['AGDSTabPanel']
export const AGDSTabs: typeof import("agds-vue")['AGDSTabs']
export const Agdstabs: typeof import("agds-vue")['AGDSTabs']
export const AGDSTag: typeof import("agds-vue")['AGDSTag']
export const Agdstag: typeof import("agds-vue")['AGDSTag']
export const AGDSTags: typeof import("agds-vue")['AGDSTags']
export const Agdstags: typeof import("agds-vue")['AGDSTags']
export const AGDSTaskList: typeof import("agds-vue")['AGDSTaskList']
export const Agdstasklist: typeof import("agds-vue")['AGDSTaskList']
export const AGDSTaskListItem: typeof import("agds-vue")['AGDSTaskListItem']
export const Agdstasklistitem: typeof import("agds-vue")['AGDSTaskListItem']
export const AGDSText: typeof import("agds-vue")['AGDSText']
export const Agdstext: typeof import("agds-vue")['AGDSText']
export const AGDSTextarea: typeof import("agds-vue")['AGDSTextarea']
export const Agdstextarea: typeof import("agds-vue")['AGDSTextarea']
export const AGDSTextInput: typeof import("agds-vue")['AGDSTextInput']
export const Agdstextinput: typeof import("agds-vue")['AGDSTextInput']
export const AGDSTextLink: typeof import("agds-vue")['AGDSTextLink']
export const Agdstextlink: typeof import("agds-vue")['AGDSTextLink']
export const AGDSTextLinkExternal: typeof import("agds-vue")['AGDSTextLinkExternal']
export const Agdstextlinkexternal: typeof import("agds-vue")['AGDSTextLinkExternal']
export const AGDSTimeInput: typeof import("agds-vue")['AGDSTimeInput']
export const Agdstimeinput: typeof import("agds-vue")['AGDSTimeInput']
export const AGDSTimePicker: typeof import("agds-vue")['AGDSTimePicker']
export const Agdstimepicker: typeof import("agds-vue")['AGDSTimePicker']
export const AGDSToggleButton: typeof import("agds-vue")['AGDSToggleButton']
export const Agdstogglebutton: typeof import("agds-vue")['AGDSToggleButton']
export const AGDSUnorderedList: typeof import("agds-vue")['AGDSUnorderedList']
export const Agdsunorderedlist: typeof import("agds-vue")['AGDSUnorderedList']
export const AGDSVisuallyHidden: typeof import("agds-vue")['AGDSVisuallyHidden']
export const Agdsvisuallyhidden: typeof import("agds-vue")['AGDSVisuallyHidden']
export const NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
export const MDC: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAccordionDemo: LazyComponent<typeof import("../app/components/content/AccordionDemo.vue")['default']>
export const LazyAutocompleteDemo: LazyComponent<typeof import("../app/components/content/AutocompleteDemo.vue")['default']>
export const LazyAvatarDemo: LazyComponent<typeof import("../app/components/content/AvatarDemo.vue")['default']>
export const LazyBreadcrumbsDemo: LazyComponent<typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']>
export const LazyCheckboxDemo: LazyComponent<typeof import("../app/components/content/CheckboxDemo.vue")['default']>
export const LazyComboboxAsyncMultiDemo: LazyComponent<typeof import("../app/components/content/ComboboxAsyncMultiDemo.vue")['default']>
export const LazyComboboxDemo: LazyComponent<typeof import("../app/components/content/ComboboxDemo.vue")['default']>
export const LazyComponentPreview: LazyComponent<typeof import("../app/components/content/ComponentPreview.vue")['default']>
export const LazyDatePickerDemo: LazyComponent<typeof import("../app/components/content/DatePickerDemo.vue")['default']>
export const LazyDocPreview: LazyComponent<typeof import("../app/components/content/DocPreview.vue")['default']>
export const LazyFeatureLinkListDemo: LazyComponent<typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']>
export const LazyFilterSidebarDemo: LazyComponent<typeof import("../app/components/content/FilterSidebarDemo.vue")['default']>
export const LazyLiveCode: LazyComponent<typeof import("../app/components/content/LiveCode.vue")['default']>
export const LazyPageAlertDemo: LazyComponent<typeof import("../app/components/content/PageAlertDemo.vue")['default']>
export const LazyPaginationDemo: LazyComponent<typeof import("../app/components/content/PaginationDemo.vue")['default']>
export const LazyProgressIndicatorDemo: LazyComponent<typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']>
export const LazyPropsTable: LazyComponent<typeof import("../app/components/content/PropsTable.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../app/components/content/ProsePre.vue")['default']>
export const LazySectionAlertDemo: LazyComponent<typeof import("../app/components/content/SectionAlertDemo.vue")['default']>
export const LazySideNavDemo: LazyComponent<typeof import("../app/components/content/SideNavDemo.vue")['default']>
export const LazySkipLinksDemo: LazyComponent<typeof import("../app/components/content/SkipLinksDemo.vue")['default']>
export const LazyStatusBadgeDemo: LazyComponent<typeof import("../app/components/content/StatusBadgeDemo.vue")['default']>
export const LazyTagsDemo: LazyComponent<typeof import("../app/components/content/TagsDemo.vue")['default']>
export const LazyTaskListDemo: LazyComponent<typeof import("../app/components/content/TaskListDemo.vue")['default']>
export const LazyDocsLayout: LazyComponent<typeof import("../app/components/DocsLayout.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyContentRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyAGDSAccordion: LazyComponent<typeof import("agds-vue")['AGDSAccordion']>
export const LazyAgdsaccordion: LazyComponent<typeof import("agds-vue")['AGDSAccordion']>
export const LazyAGDSAccordionItem: LazyComponent<typeof import("agds-vue")['AGDSAccordionItem']>
export const LazyAgdsaccordionitem: LazyComponent<typeof import("agds-vue")['AGDSAccordionItem']>
export const LazyAGDSAppLayout: LazyComponent<typeof import("agds-vue")['AGDSAppLayout']>
export const LazyAgdsapplayout: LazyComponent<typeof import("agds-vue")['AGDSAppLayout']>
export const LazyAGDSAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooter']>
export const LazyAgdsapplayoutfooter: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooter']>
export const LazyAGDSAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooterDivider']>
export const LazyAgdsapplayoutfooterdivider: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooterDivider']>
export const LazyAGDSAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutHeader']>
export const LazyAgdsapplayoutheader: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutHeader']>
export const LazyAGDSAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebar']>
export const LazyAgdsapplayoutsidebar: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebar']>
export const LazyAGDSAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebarNav']>
export const LazyAgdsapplayoutsidebarnav: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebarNav']>
export const LazyAGDSAutocomplete: LazyComponent<typeof import("agds-vue")['AGDSAutocomplete']>
export const LazyAgdsautocomplete: LazyComponent<typeof import("agds-vue")['AGDSAutocomplete']>
export const LazyAGDSAvatar: LazyComponent<typeof import("agds-vue")['AGDSAvatar']>
export const LazyAgdsavatar: LazyComponent<typeof import("agds-vue")['AGDSAvatar']>
export const LazyAGDSBox: LazyComponent<typeof import("agds-vue")['AGDSBox']>
export const LazyAgdsbox: LazyComponent<typeof import("agds-vue")['AGDSBox']>
export const LazyAGDSBreadcrumbs: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbs']>
export const LazyAgdsbreadcrumbs: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbs']>
export const LazyAGDSBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbsItem']>
export const LazyAgdsbreadcrumbsitem: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbsItem']>
export const LazyAGDSButton: LazyComponent<typeof import("agds-vue")['AGDSButton']>
export const LazyAgdsbutton: LazyComponent<typeof import("agds-vue")['AGDSButton']>
export const LazyAGDSButtonLink: LazyComponent<typeof import("agds-vue")['AGDSButtonLink']>
export const LazyAgdsbuttonlink: LazyComponent<typeof import("agds-vue")['AGDSButtonLink']>
export const LazyAGDSCallout: LazyComponent<typeof import("agds-vue")['AGDSCallout']>
export const LazyAgdscallout: LazyComponent<typeof import("agds-vue")['AGDSCallout']>
export const LazyAGDSCallToActionButton: LazyComponent<typeof import("agds-vue")['AGDSCallToActionButton']>
export const LazyAgdscalltoactionbutton: LazyComponent<typeof import("agds-vue")['AGDSCallToActionButton']>
export const LazyAGDSCallToActionLink: LazyComponent<typeof import("agds-vue")['AGDSCallToActionLink']>
export const LazyAgdscalltoactionlink: LazyComponent<typeof import("agds-vue")['AGDSCallToActionLink']>
export const LazyAGDSCard: LazyComponent<typeof import("agds-vue")['AGDSCard']>
export const LazyAgdscard: LazyComponent<typeof import("agds-vue")['AGDSCard']>
export const LazyAGDSCardFooter: LazyComponent<typeof import("agds-vue")['AGDSCardFooter']>
export const LazyAgdscardfooter: LazyComponent<typeof import("agds-vue")['AGDSCardFooter']>
export const LazyAGDSCardHeader: LazyComponent<typeof import("agds-vue")['AGDSCardHeader']>
export const LazyAgdscardheader: LazyComponent<typeof import("agds-vue")['AGDSCardHeader']>
export const LazyAGDSCardInner: LazyComponent<typeof import("agds-vue")['AGDSCardInner']>
export const LazyAgdscardinner: LazyComponent<typeof import("agds-vue")['AGDSCardInner']>
export const LazyAGDSCardLink: LazyComponent<typeof import("agds-vue")['AGDSCardLink']>
export const LazyAgdscardlink: LazyComponent<typeof import("agds-vue")['AGDSCardLink']>
export const LazyAGDSCheckbox: LazyComponent<typeof import("agds-vue")['AGDSCheckbox']>
export const LazyAgdscheckbox: LazyComponent<typeof import("agds-vue")['AGDSCheckbox']>
export const LazyAGDSCheckboxGroup: LazyComponent<typeof import("agds-vue")['AGDSCheckboxGroup']>
export const LazyAgdscheckboxgroup: LazyComponent<typeof import("agds-vue")['AGDSCheckboxGroup']>
export const LazyAGDSCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AGDSCollapsingSideBar']>
export const LazyAgdscollapsingsidebar: LazyComponent<typeof import("agds-vue")['AGDSCollapsingSideBar']>
export const LazyAGDSColumn: LazyComponent<typeof import("agds-vue")['AGDSColumn']>
export const LazyAgdscolumn: LazyComponent<typeof import("agds-vue")['AGDSColumn']>
export const LazyAGDSColumns: LazyComponent<typeof import("agds-vue")['AGDSColumns']>
export const LazyAgdscolumns: LazyComponent<typeof import("agds-vue")['AGDSColumns']>
export const LazyAGDSCombobox: LazyComponent<typeof import("agds-vue")['AGDSCombobox']>
export const LazyAgdscombobox: LazyComponent<typeof import("agds-vue")['AGDSCombobox']>
export const LazyAGDSComboboxAsync: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsync']>
export const LazyAgdscomboboxasync: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsync']>
export const LazyAGDSComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsyncMulti']>
export const LazyAgdscomboboxasyncmulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsyncMulti']>
export const LazyAGDSComboboxMulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxMulti']>
export const LazyAgdscomboboxmulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxMulti']>
export const LazyAGDSContent: LazyComponent<typeof import("agds-vue")['AGDSContent']>
export const LazyAgdscontent: LazyComponent<typeof import("agds-vue")['AGDSContent']>
export const LazyAGDSContentBleed: LazyComponent<typeof import("agds-vue")['AGDSContentBleed']>
export const LazyAgdscontentbleed: LazyComponent<typeof import("agds-vue")['AGDSContentBleed']>
export const LazyAGDSCore: LazyComponent<typeof import("agds-vue")['AGDSCore']>
export const LazyAgdscore: LazyComponent<typeof import("agds-vue")['AGDSCore']>
export const LazyAGDSCoreProvider: LazyComponent<typeof import("agds-vue")['AGDSCoreProvider']>
export const LazyAgdscoreprovider: LazyComponent<typeof import("agds-vue")['AGDSCoreProvider']>
export const LazyAGDSDatePicker: LazyComponent<typeof import("agds-vue")['AGDSDatePicker']>
export const LazyAgdsdatepicker: LazyComponent<typeof import("agds-vue")['AGDSDatePicker']>
export const LazyAGDSDetails: LazyComponent<typeof import("agds-vue")['AGDSDetails']>
export const LazyAgdsdetails: LazyComponent<typeof import("agds-vue")['AGDSDetails']>
export const LazyAGDSDirectionButton: LazyComponent<typeof import("agds-vue")['AGDSDirectionButton']>
export const LazyAgdsdirectionbutton: LazyComponent<typeof import("agds-vue")['AGDSDirectionButton']>
export const LazyAGDSDirectionLink: LazyComponent<typeof import("agds-vue")['AGDSDirectionLink']>
export const LazyAgdsdirectionlink: LazyComponent<typeof import("agds-vue")['AGDSDirectionLink']>
export const LazyAGDSDivider: LazyComponent<typeof import("agds-vue")['AGDSDivider']>
export const LazyAgdsdivider: LazyComponent<typeof import("agds-vue")['AGDSDivider']>
export const LazyAGDSDrawer: LazyComponent<typeof import("agds-vue")['AGDSDrawer']>
export const LazyAgdsdrawer: LazyComponent<typeof import("agds-vue")['AGDSDrawer']>
export const LazyAGDSDropdownMenu: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenu']>
export const LazyAgdsdropdownmenu: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenu']>
export const LazyAGDSDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuButton']>
export const LazyAgdsdropdownmenubutton: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuButton']>
export const LazyAGDSDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuDivider']>
export const LazyAgdsdropdownmenudivider: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuDivider']>
export const LazyAGDSDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuGroup']>
export const LazyAgdsdropdownmenugroup: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuGroup']>
export const LazyAGDSDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItem']>
export const LazyAgdsdropdownmenuitem: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItem']>
export const LazyAGDSDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemLink']>
export const LazyAgdsdropdownmenuitemlink: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemLink']>
export const LazyAGDSDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemRadio']>
export const LazyAgdsdropdownmenuitemradio: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemRadio']>
export const LazyAGDSDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuPanel']>
export const LazyAgdsdropdownmenupanel: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuPanel']>
export const LazyAGDSExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AGDSExternalLinkCallout']>
export const LazyAgdsexternallinkcallout: LazyComponent<typeof import("agds-vue")['AGDSExternalLinkCallout']>
export const LazyAGDSFeatureLinkList: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkList']>
export const LazyAgdsfeaturelinklist: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkList']>
export const LazyAGDSFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkListItem']>
export const LazyAgdsfeaturelinklistitem: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkListItem']>
export const LazyAGDSField: LazyComponent<typeof import("agds-vue")['AGDSField']>
export const LazyAgdsfield: LazyComponent<typeof import("agds-vue")['AGDSField']>
export const LazyAGDSFieldContainer: LazyComponent<typeof import("agds-vue")['AGDSFieldContainer']>
export const LazyAgdsfieldcontainer: LazyComponent<typeof import("agds-vue")['AGDSFieldContainer']>
export const LazyAGDSFieldHint: LazyComponent<typeof import("agds-vue")['AGDSFieldHint']>
export const LazyAgdsfieldhint: LazyComponent<typeof import("agds-vue")['AGDSFieldHint']>
export const LazyAGDSFieldLabel: LazyComponent<typeof import("agds-vue")['AGDSFieldLabel']>
export const LazyAgdsfieldlabel: LazyComponent<typeof import("agds-vue")['AGDSFieldLabel']>
export const LazyAGDSFieldMessage: LazyComponent<typeof import("agds-vue")['AGDSFieldMessage']>
export const LazyAgdsfieldmessage: LazyComponent<typeof import("agds-vue")['AGDSFieldMessage']>
export const LazyAGDSFieldset: LazyComponent<typeof import("agds-vue")['AGDSFieldset']>
export const LazyAgdsfieldset: LazyComponent<typeof import("agds-vue")['AGDSFieldset']>
export const LazyAGDSFileUpload: LazyComponent<typeof import("agds-vue")['AGDSFileUpload']>
export const LazyAgdsfileupload: LazyComponent<typeof import("agds-vue")['AGDSFileUpload']>
export const LazyAGDSFilterSidebar: LazyComponent<typeof import("agds-vue")['AGDSFilterSidebar']>
export const LazyAgdsfiltersidebar: LazyComponent<typeof import("agds-vue")['AGDSFilterSidebar']>
export const LazyAGDSFlex: LazyComponent<typeof import("agds-vue")['AGDSFlex']>
export const LazyAgdsflex: LazyComponent<typeof import("agds-vue")['AGDSFlex']>
export const LazyAGDSFooter: LazyComponent<typeof import("agds-vue")['AGDSFooter']>
export const LazyAgdsfooter: LazyComponent<typeof import("agds-vue")['AGDSFooter']>
export const LazyAGDSFooterDivider: LazyComponent<typeof import("agds-vue")['AGDSFooterDivider']>
export const LazyAgdsfooterdivider: LazyComponent<typeof import("agds-vue")['AGDSFooterDivider']>
export const LazyAGDSFormStack: LazyComponent<typeof import("agds-vue")['AGDSFormStack']>
export const LazyAgdsformstack: LazyComponent<typeof import("agds-vue")['AGDSFormStack']>
export const LazyAGDSGlobalAlert: LazyComponent<typeof import("agds-vue")['AGDSGlobalAlert']>
export const LazyAgdsglobalalert: LazyComponent<typeof import("agds-vue")['AGDSGlobalAlert']>
export const LazyAGDSGroupedFields: LazyComponent<typeof import("agds-vue")['AGDSGroupedFields']>
export const LazyAgdsgroupedfields: LazyComponent<typeof import("agds-vue")['AGDSGroupedFields']>
export const LazyAGDSHeader: LazyComponent<typeof import("agds-vue")['AGDSHeader']>
export const LazyAgdsheader: LazyComponent<typeof import("agds-vue")['AGDSHeader']>
export const LazyAGDSHeading: LazyComponent<typeof import("agds-vue")['AGDSHeading']>
export const LazyAgdsheading: LazyComponent<typeof import("agds-vue")['AGDSHeading']>
export const LazyAgdsh1: LazyComponent<typeof import("agds-vue")['AGDSH1']>
export const LazyAgdsh2: LazyComponent<typeof import("agds-vue")['AGDSH2']>
export const LazyAgdsh3: LazyComponent<typeof import("agds-vue")['AGDSH3']>
export const LazyAgdsh4: LazyComponent<typeof import("agds-vue")['AGDSH4']>
export const LazyAgdsh5: LazyComponent<typeof import("agds-vue")['AGDSH5']>
export const LazyAgdsh6: LazyComponent<typeof import("agds-vue")['AGDSH6']>
export const LazyAGDSIcon: LazyComponent<typeof import("agds-vue")['AGDSIcon']>
export const LazyAgdsicon: LazyComponent<typeof import("agds-vue")['AGDSIcon']>
export const LazyAGDSInpageNav: LazyComponent<typeof import("agds-vue")['AGDSInpageNav']>
export const LazyAgdsinpagenav: LazyComponent<typeof import("agds-vue")['AGDSInpageNav']>
export const LazyAGDSLinkList: LazyComponent<typeof import("agds-vue")['AGDSLinkList']>
export const LazyAgdslinklist: LazyComponent<typeof import("agds-vue")['AGDSLinkList']>
export const LazyAGDSLinkListItem: LazyComponent<typeof import("agds-vue")['AGDSLinkListItem']>
export const LazyAgdslinklistitem: LazyComponent<typeof import("agds-vue")['AGDSLinkListItem']>
export const LazyAGDSListItem: LazyComponent<typeof import("agds-vue")['AGDSListItem']>
export const LazyAgdslistitem: LazyComponent<typeof import("agds-vue")['AGDSListItem']>
export const LazyAGDSLoadingBlanket: LazyComponent<typeof import("agds-vue")['AGDSLoadingBlanket']>
export const LazyAgdsloadingblanket: LazyComponent<typeof import("agds-vue")['AGDSLoadingBlanket']>
export const LazyAGDSMainNav: LazyComponent<typeof import("agds-vue")['AGDSMainNav']>
export const LazyAgdsmainnav: LazyComponent<typeof import("agds-vue")['AGDSMainNav']>
export const LazyAGDSModal: LazyComponent<typeof import("agds-vue")['AGDSModal']>
export const LazyAgdsmodal: LazyComponent<typeof import("agds-vue")['AGDSModal']>
export const LazyAGDSNotificationBadge: LazyComponent<typeof import("agds-vue")['AGDSNotificationBadge']>
export const LazyAgdsnotificationbadge: LazyComponent<typeof import("agds-vue")['AGDSNotificationBadge']>
export const LazyAGDSOrderedList: LazyComponent<typeof import("agds-vue")['AGDSOrderedList']>
export const LazyAgdsorderedlist: LazyComponent<typeof import("agds-vue")['AGDSOrderedList']>
export const LazyAGDSPageAlert: LazyComponent<typeof import("agds-vue")['AGDSPageAlert']>
export const LazyAgdspagealert: LazyComponent<typeof import("agds-vue")['AGDSPageAlert']>
export const LazyAGDSPageContent: LazyComponent<typeof import("agds-vue")['AGDSPageContent']>
export const LazyAgdspagecontent: LazyComponent<typeof import("agds-vue")['AGDSPageContent']>
export const LazyAGDSPagination: LazyComponent<typeof import("agds-vue")['AGDSPagination']>
export const LazyAgdspagination: LazyComponent<typeof import("agds-vue")['AGDSPagination']>
export const LazyAGDSPaginationButtons: LazyComponent<typeof import("agds-vue")['AGDSPaginationButtons']>
export const LazyAgdspaginationbuttons: LazyComponent<typeof import("agds-vue")['AGDSPaginationButtons']>
export const LazyAGDSProgressIndicator: LazyComponent<typeof import("agds-vue")['AGDSProgressIndicator']>
export const LazyAgdsprogressindicator: LazyComponent<typeof import("agds-vue")['AGDSProgressIndicator']>
export const LazyAGDSProse: LazyComponent<typeof import("agds-vue")['AGDSProse']>
export const LazyAgdsprose: LazyComponent<typeof import("agds-vue")['AGDSProse']>
export const LazyAGDSRadio: LazyComponent<typeof import("agds-vue")['AGDSRadio']>
export const LazyAgdsradio: LazyComponent<typeof import("agds-vue")['AGDSRadio']>
export const LazyAGDSRadioGroup: LazyComponent<typeof import("agds-vue")['AGDSRadioGroup']>
export const LazyAgdsradiogroup: LazyComponent<typeof import("agds-vue")['AGDSRadioGroup']>
export const LazyAGDSSearchBox: LazyComponent<typeof import("agds-vue")['AGDSSearchBox']>
export const LazyAgdssearchbox: LazyComponent<typeof import("agds-vue")['AGDSSearchBox']>
export const LazyAGDSSearchBoxButton: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxButton']>
export const LazyAgdssearchboxbutton: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxButton']>
export const LazyAGDSSearchBoxInput: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxInput']>
export const LazyAgdssearchboxinput: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxInput']>
export const LazyAGDSSearchInput: LazyComponent<typeof import("agds-vue")['AGDSSearchInput']>
export const LazyAgdssearchinput: LazyComponent<typeof import("agds-vue")['AGDSSearchInput']>
export const LazyAGDSSectionAlert: LazyComponent<typeof import("agds-vue")['AGDSSectionAlert']>
export const LazyAgdssectionalert: LazyComponent<typeof import("agds-vue")['AGDSSectionAlert']>
export const LazyAGDSSectionContent: LazyComponent<typeof import("agds-vue")['AGDSSectionContent']>
export const LazyAgdssectioncontent: LazyComponent<typeof import("agds-vue")['AGDSSectionContent']>
export const LazyAGDSSelect: LazyComponent<typeof import("agds-vue")['AGDSSelect']>
export const LazyAgdsselect: LazyComponent<typeof import("agds-vue")['AGDSSelect']>
export const LazyAGDSSideNav: LazyComponent<typeof import("agds-vue")['AGDSSideNav']>
export const LazyAgdssidenav: LazyComponent<typeof import("agds-vue")['AGDSSideNav']>
export const LazyAGDSSkipLinks: LazyComponent<typeof import("agds-vue")['AGDSSkipLinks']>
export const LazyAgdsskiplinks: LazyComponent<typeof import("agds-vue")['AGDSSkipLinks']>
export const LazyAGDSStack: LazyComponent<typeof import("agds-vue")['AGDSStack']>
export const LazyAgdsstack: LazyComponent<typeof import("agds-vue")['AGDSStack']>
export const LazyAGDSStatusBadge: LazyComponent<typeof import("agds-vue")['AGDSStatusBadge']>
export const LazyAgdsstatusbadge: LazyComponent<typeof import("agds-vue")['AGDSStatusBadge']>
export const LazyAGDSSubNav: LazyComponent<typeof import("agds-vue")['AGDSSubNav']>
export const LazyAgdssubnav: LazyComponent<typeof import("agds-vue")['AGDSSubNav']>
export const LazyAGDSSummaryList: LazyComponent<typeof import("agds-vue")['AGDSSummaryList']>
export const LazyAgdssummarylist: LazyComponent<typeof import("agds-vue")['AGDSSummaryList']>
export const LazyAGDSSummaryListItem: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItem']>
export const LazyAgdssummarylistitem: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItem']>
export const LazyAGDSSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemAction']>
export const LazyAgdssummarylistitemaction: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemAction']>
export const LazyAGDSSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemDescription']>
export const LazyAgdssummarylistitemdescription: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemDescription']>
export const LazyAGDSSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemTerm']>
export const LazyAgdssummarylistitemterm: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemTerm']>
export const LazyAGDSSwitch: LazyComponent<typeof import("agds-vue")['AGDSSwitch']>
export const LazyAgdsswitch: LazyComponent<typeof import("agds-vue")['AGDSSwitch']>
export const LazyAGDSTab: LazyComponent<typeof import("agds-vue")['AGDSTab']>
export const LazyAgdstab: LazyComponent<typeof import("agds-vue")['AGDSTab']>
export const LazyAGDSTable: LazyComponent<typeof import("agds-vue")['AGDSTable']>
export const LazyAgdstable: LazyComponent<typeof import("agds-vue")['AGDSTable']>
export const LazyAGDSTableBody: LazyComponent<typeof import("agds-vue")['AGDSTableBody']>
export const LazyAgdstablebody: LazyComponent<typeof import("agds-vue")['AGDSTableBody']>
export const LazyAGDSTableCaption: LazyComponent<typeof import("agds-vue")['AGDSTableCaption']>
export const LazyAgdstablecaption: LazyComponent<typeof import("agds-vue")['AGDSTableCaption']>
export const LazyAGDSTableCell: LazyComponent<typeof import("agds-vue")['AGDSTableCell']>
export const LazyAgdstablecell: LazyComponent<typeof import("agds-vue")['AGDSTableCell']>
export const LazyAGDSTableHead: LazyComponent<typeof import("agds-vue")['AGDSTableHead']>
export const LazyAgdstablehead: LazyComponent<typeof import("agds-vue")['AGDSTableHead']>
export const LazyAGDSTableHeader: LazyComponent<typeof import("agds-vue")['AGDSTableHeader']>
export const LazyAgdstableheader: LazyComponent<typeof import("agds-vue")['AGDSTableHeader']>
export const LazyAGDSTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AGDSTableHeaderSortable']>
export const LazyAgdstableheadersortable: LazyComponent<typeof import("agds-vue")['AGDSTableHeaderSortable']>
export const LazyAGDSTableRow: LazyComponent<typeof import("agds-vue")['AGDSTableRow']>
export const LazyAgdstablerow: LazyComponent<typeof import("agds-vue")['AGDSTableRow']>
export const LazyAGDSTableScroller: LazyComponent<typeof import("agds-vue")['AGDSTableScroller']>
export const LazyAgdstablescroller: LazyComponent<typeof import("agds-vue")['AGDSTableScroller']>
export const LazyAGDSTabList: LazyComponent<typeof import("agds-vue")['AGDSTabList']>
export const LazyAgdstablist: LazyComponent<typeof import("agds-vue")['AGDSTabList']>
export const LazyAGDSTabPanel: LazyComponent<typeof import("agds-vue")['AGDSTabPanel']>
export const LazyAgdstabpanel: LazyComponent<typeof import("agds-vue")['AGDSTabPanel']>
export const LazyAGDSTabs: LazyComponent<typeof import("agds-vue")['AGDSTabs']>
export const LazyAgdstabs: LazyComponent<typeof import("agds-vue")['AGDSTabs']>
export const LazyAGDSTag: LazyComponent<typeof import("agds-vue")['AGDSTag']>
export const LazyAgdstag: LazyComponent<typeof import("agds-vue")['AGDSTag']>
export const LazyAGDSTags: LazyComponent<typeof import("agds-vue")['AGDSTags']>
export const LazyAgdstags: LazyComponent<typeof import("agds-vue")['AGDSTags']>
export const LazyAGDSTaskList: LazyComponent<typeof import("agds-vue")['AGDSTaskList']>
export const LazyAgdstasklist: LazyComponent<typeof import("agds-vue")['AGDSTaskList']>
export const LazyAGDSTaskListItem: LazyComponent<typeof import("agds-vue")['AGDSTaskListItem']>
export const LazyAgdstasklistitem: LazyComponent<typeof import("agds-vue")['AGDSTaskListItem']>
export const LazyAGDSText: LazyComponent<typeof import("agds-vue")['AGDSText']>
export const LazyAgdstext: LazyComponent<typeof import("agds-vue")['AGDSText']>
export const LazyAGDSTextarea: LazyComponent<typeof import("agds-vue")['AGDSTextarea']>
export const LazyAgdstextarea: LazyComponent<typeof import("agds-vue")['AGDSTextarea']>
export const LazyAGDSTextInput: LazyComponent<typeof import("agds-vue")['AGDSTextInput']>
export const LazyAgdstextinput: LazyComponent<typeof import("agds-vue")['AGDSTextInput']>
export const LazyAGDSTextLink: LazyComponent<typeof import("agds-vue")['AGDSTextLink']>
export const LazyAgdstextlink: LazyComponent<typeof import("agds-vue")['AGDSTextLink']>
export const LazyAGDSTextLinkExternal: LazyComponent<typeof import("agds-vue")['AGDSTextLinkExternal']>
export const LazyAgdstextlinkexternal: LazyComponent<typeof import("agds-vue")['AGDSTextLinkExternal']>
export const LazyAGDSTimeInput: LazyComponent<typeof import("agds-vue")['AGDSTimeInput']>
export const LazyAgdstimeinput: LazyComponent<typeof import("agds-vue")['AGDSTimeInput']>
export const LazyAGDSTimePicker: LazyComponent<typeof import("agds-vue")['AGDSTimePicker']>
export const LazyAgdstimepicker: LazyComponent<typeof import("agds-vue")['AGDSTimePicker']>
export const LazyAGDSToggleButton: LazyComponent<typeof import("agds-vue")['AGDSToggleButton']>
export const LazyAgdstogglebutton: LazyComponent<typeof import("agds-vue")['AGDSToggleButton']>
export const LazyAGDSUnorderedList: LazyComponent<typeof import("agds-vue")['AGDSUnorderedList']>
export const LazyAgdsunorderedlist: LazyComponent<typeof import("agds-vue")['AGDSUnorderedList']>
export const LazyAGDSVisuallyHidden: LazyComponent<typeof import("agds-vue")['AGDSVisuallyHidden']>
export const LazyAgdsvisuallyhidden: LazyComponent<typeof import("agds-vue")['AGDSVisuallyHidden']>
export const LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyMDC: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
