
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AccordionDemo: typeof import("../app/components/content/AccordionDemo.vue")['default']
export const BreadcrumbsDemo: typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']
export const ComponentPreview: typeof import("../app/components/content/ComponentPreview.vue")['default']
export const DocPreview: typeof import("../app/components/content/DocPreview.vue")['default']
export const FeatureLinkListDemo: typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']
export const FilterSidebarDemo: typeof import("../app/components/content/FilterSidebarDemo.vue")['default']
export const LiveCode: typeof import("../app/components/content/LiveCode.vue")['default']
export const PaginationDemo: typeof import("../app/components/content/PaginationDemo.vue")['default']
export const ProgressIndicatorDemo: typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']
export const PropsTable: typeof import("../app/components/content/PropsTable.vue")['default']
export const ProsePre: typeof import("../app/components/content/ProsePre.vue")['default']
export const SideNavDemo: typeof import("../app/components/content/SideNavDemo.vue")['default']
export const DocsLayout: typeof import("../app/components/DocsLayout.vue")['default']
export const ProseA: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ContentRenderer: typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const AgDSAccordion: typeof import("agds-vue")['AgDSAccordion']
export const Agdsaccordion: typeof import("agds-vue")['AgDSAccordion']
export const AgDSAccordionItem: typeof import("agds-vue")['AgDSAccordionItem']
export const Agdsaccordionitem: typeof import("agds-vue")['AgDSAccordionItem']
export const AgDSAppLayout: typeof import("agds-vue")['AgDSAppLayout']
export const Agdsapplayout: typeof import("agds-vue")['AgDSAppLayout']
export const AgDSAppLayoutFooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
export const Agdsapplayoutfooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
export const AgDSAppLayoutFooterDivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
export const Agdsapplayoutfooterdivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
export const AgDSAppLayoutHeader: typeof import("agds-vue")['AgDSAppLayoutHeader']
export const Agdsapplayoutheader: typeof import("agds-vue")['AgDSAppLayoutHeader']
export const AgDSAppLayoutSidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
export const Agdsapplayoutsidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
export const AgDSAppLayoutSidebarNav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
export const Agdsapplayoutsidebarnav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
export const AgDSAutocomplete: typeof import("agds-vue")['AgDSAutocomplete']
export const Agdsautocomplete: typeof import("agds-vue")['AgDSAutocomplete']
export const AgDSAvatar: typeof import("agds-vue")['AgDSAvatar']
export const Agdsavatar: typeof import("agds-vue")['AgDSAvatar']
export const AgDSBox: typeof import("agds-vue")['AgDSBox']
export const Agdsbox: typeof import("agds-vue")['AgDSBox']
export const AgDSBreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
export const Agdsbreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
export const AgDSBreadcrumbsItem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
export const Agdsbreadcrumbsitem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
export const AgDSButton: typeof import("agds-vue")['AgDSButton']
export const Agdsbutton: typeof import("agds-vue")['AgDSButton']
export const AgDSButtonLink: typeof import("agds-vue")['AgDSButtonLink']
export const Agdsbuttonlink: typeof import("agds-vue")['AgDSButtonLink']
export const AgDSCallout: typeof import("agds-vue")['AgDSCallout']
export const Agdscallout: typeof import("agds-vue")['AgDSCallout']
export const AgDSCallToActionButton: typeof import("agds-vue")['AgDSCallToActionButton']
export const Agdscalltoactionbutton: typeof import("agds-vue")['AgDSCallToActionButton']
export const AgDSCallToActionLink: typeof import("agds-vue")['AgDSCallToActionLink']
export const Agdscalltoactionlink: typeof import("agds-vue")['AgDSCallToActionLink']
export const AgDSCard: typeof import("agds-vue")['AgDSCard']
export const Agdscard: typeof import("agds-vue")['AgDSCard']
export const AgDSCardFooter: typeof import("agds-vue")['AgDSCardFooter']
export const Agdscardfooter: typeof import("agds-vue")['AgDSCardFooter']
export const AgDSCardHeader: typeof import("agds-vue")['AgDSCardHeader']
export const Agdscardheader: typeof import("agds-vue")['AgDSCardHeader']
export const AgDSCardInner: typeof import("agds-vue")['AgDSCardInner']
export const Agdscardinner: typeof import("agds-vue")['AgDSCardInner']
export const AgDSCardLink: typeof import("agds-vue")['AgDSCardLink']
export const Agdscardlink: typeof import("agds-vue")['AgDSCardLink']
export const AgDSCheckbox: typeof import("agds-vue")['AgDSCheckbox']
export const Agdscheckbox: typeof import("agds-vue")['AgDSCheckbox']
export const AgDSCheckboxGroup: typeof import("agds-vue")['AgDSCheckboxGroup']
export const Agdscheckboxgroup: typeof import("agds-vue")['AgDSCheckboxGroup']
export const AgDSCollapsingSideBar: typeof import("agds-vue")['AgDSCollapsingSideBar']
export const Agdscollapsingsidebar: typeof import("agds-vue")['AgDSCollapsingSideBar']
export const AgDSColumn: typeof import("agds-vue")['AgDSColumn']
export const Agdscolumn: typeof import("agds-vue")['AgDSColumn']
export const AgDSColumns: typeof import("agds-vue")['AgDSColumns']
export const Agdscolumns: typeof import("agds-vue")['AgDSColumns']
export const AgDSCombobox: typeof import("agds-vue")['AgDSCombobox']
export const Agdscombobox: typeof import("agds-vue")['AgDSCombobox']
export const AgDSComboboxAsync: typeof import("agds-vue")['AgDSComboboxAsync']
export const Agdscomboboxasync: typeof import("agds-vue")['AgDSComboboxAsync']
export const AgDSComboboxAsyncMulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
export const Agdscomboboxasyncmulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
export const AgDSComboboxMulti: typeof import("agds-vue")['AgDSComboboxMulti']
export const Agdscomboboxmulti: typeof import("agds-vue")['AgDSComboboxMulti']
export const AgDSContent: typeof import("agds-vue")['AgDSContent']
export const Agdscontent: typeof import("agds-vue")['AgDSContent']
export const AgDSContentBleed: typeof import("agds-vue")['AgDSContentBleed']
export const Agdscontentbleed: typeof import("agds-vue")['AgDSContentBleed']
export const AgDSCore: typeof import("agds-vue")['AgDSCore']
export const Agdscore: typeof import("agds-vue")['AgDSCore']
export const AgDSCoreProvider: typeof import("agds-vue")['AgDSCoreProvider']
export const Agdscoreprovider: typeof import("agds-vue")['AgDSCoreProvider']
export const AgDSDatePicker: typeof import("agds-vue")['AgDSDatePicker']
export const Agdsdatepicker: typeof import("agds-vue")['AgDSDatePicker']
export const AgDSDetails: typeof import("agds-vue")['AgDSDetails']
export const Agdsdetails: typeof import("agds-vue")['AgDSDetails']
export const AgDSDirectionButton: typeof import("agds-vue")['AgDSDirectionButton']
export const Agdsdirectionbutton: typeof import("agds-vue")['AgDSDirectionButton']
export const AgDSDirectionLink: typeof import("agds-vue")['AgDSDirectionLink']
export const Agdsdirectionlink: typeof import("agds-vue")['AgDSDirectionLink']
export const AgDSDivider: typeof import("agds-vue")['AgDSDivider']
export const Agdsdivider: typeof import("agds-vue")['AgDSDivider']
export const AgDSDrawer: typeof import("agds-vue")['AgDSDrawer']
export const Agdsdrawer: typeof import("agds-vue")['AgDSDrawer']
export const AgDSDropdownMenu: typeof import("agds-vue")['AgDSDropdownMenu']
export const Agdsdropdownmenu: typeof import("agds-vue")['AgDSDropdownMenu']
export const AgDSDropdownMenuButton: typeof import("agds-vue")['AgDSDropdownMenuButton']
export const Agdsdropdownmenubutton: typeof import("agds-vue")['AgDSDropdownMenuButton']
export const AgDSDropdownMenuDivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
export const Agdsdropdownmenudivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
export const AgDSDropdownMenuGroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
export const Agdsdropdownmenugroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
export const AgDSDropdownMenuItem: typeof import("agds-vue")['AgDSDropdownMenuItem']
export const Agdsdropdownmenuitem: typeof import("agds-vue")['AgDSDropdownMenuItem']
export const AgDSDropdownMenuItemLink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
export const Agdsdropdownmenuitemlink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
export const AgDSDropdownMenuItemRadio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
export const Agdsdropdownmenuitemradio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
export const AgDSDropdownMenuPanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
export const Agdsdropdownmenupanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
export const AgDSExternalLinkCallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
export const Agdsexternallinkcallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
export const AgDSFeatureLinkList: typeof import("agds-vue")['AgDSFeatureLinkList']
export const Agdsfeaturelinklist: typeof import("agds-vue")['AgDSFeatureLinkList']
export const AgDSFeatureLinkListItem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
export const Agdsfeaturelinklistitem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
export const AgDSField: typeof import("agds-vue")['AgDSField']
export const Agdsfield: typeof import("agds-vue")['AgDSField']
export const AgDSFieldContainer: typeof import("agds-vue")['AgDSFieldContainer']
export const Agdsfieldcontainer: typeof import("agds-vue")['AgDSFieldContainer']
export const AgDSFieldHint: typeof import("agds-vue")['AgDSFieldHint']
export const Agdsfieldhint: typeof import("agds-vue")['AgDSFieldHint']
export const AgDSFieldLabel: typeof import("agds-vue")['AgDSFieldLabel']
export const Agdsfieldlabel: typeof import("agds-vue")['AgDSFieldLabel']
export const AgDSFieldMessage: typeof import("agds-vue")['AgDSFieldMessage']
export const Agdsfieldmessage: typeof import("agds-vue")['AgDSFieldMessage']
export const AgDSFieldset: typeof import("agds-vue")['AgDSFieldset']
export const Agdsfieldset: typeof import("agds-vue")['AgDSFieldset']
export const AgDSFileUpload: typeof import("agds-vue")['AgDSFileUpload']
export const Agdsfileupload: typeof import("agds-vue")['AgDSFileUpload']
export const AgDSFilterSidebar: typeof import("agds-vue")['AgDSFilterSidebar']
export const Agdsfiltersidebar: typeof import("agds-vue")['AgDSFilterSidebar']
export const AgDSFlex: typeof import("agds-vue")['AgDSFlex']
export const Agdsflex: typeof import("agds-vue")['AgDSFlex']
export const AgDSFooter: typeof import("agds-vue")['AgDSFooter']
export const Agdsfooter: typeof import("agds-vue")['AgDSFooter']
export const AgDSFooterDivider: typeof import("agds-vue")['AgDSFooterDivider']
export const Agdsfooterdivider: typeof import("agds-vue")['AgDSFooterDivider']
export const AgDSFormStack: typeof import("agds-vue")['AgDSFormStack']
export const Agdsformstack: typeof import("agds-vue")['AgDSFormStack']
export const AgDSGlobalAlert: typeof import("agds-vue")['AgDSGlobalAlert']
export const Agdsglobalalert: typeof import("agds-vue")['AgDSGlobalAlert']
export const AgDSGroupedFields: typeof import("agds-vue")['AgDSGroupedFields']
export const Agdsgroupedfields: typeof import("agds-vue")['AgDSGroupedFields']
export const AgDSHeader: typeof import("agds-vue")['AgDSHeader']
export const Agdsheader: typeof import("agds-vue")['AgDSHeader']
export const AgDSHeading: typeof import("agds-vue")['AgDSHeading']
export const Agdsheading: typeof import("agds-vue")['AgDSHeading']
export const AgDSH1: typeof import("agds-vue")['AgDSH1']
export const Agdsh1: typeof import("agds-vue")['AgDSH1']
export const AgDSH2: typeof import("agds-vue")['AgDSH2']
export const Agdsh2: typeof import("agds-vue")['AgDSH2']
export const AgDSH3: typeof import("agds-vue")['AgDSH3']
export const Agdsh3: typeof import("agds-vue")['AgDSH3']
export const AgDSH4: typeof import("agds-vue")['AgDSH4']
export const Agdsh4: typeof import("agds-vue")['AgDSH4']
export const AgDSH5: typeof import("agds-vue")['AgDSH5']
export const Agdsh5: typeof import("agds-vue")['AgDSH5']
export const AgDSH6: typeof import("agds-vue")['AgDSH6']
export const Agdsh6: typeof import("agds-vue")['AgDSH6']
export const AgDSIcon: typeof import("agds-vue")['AgDSIcon']
export const Agdsicon: typeof import("agds-vue")['AgDSIcon']
export const AgDSInpageNav: typeof import("agds-vue")['AgDSInpageNav']
export const Agdsinpagenav: typeof import("agds-vue")['AgDSInpageNav']
export const AgDSLinkList: typeof import("agds-vue")['AgDSLinkList']
export const Agdslinklist: typeof import("agds-vue")['AgDSLinkList']
export const AgDSLinkListItem: typeof import("agds-vue")['AgDSLinkListItem']
export const Agdslinklistitem: typeof import("agds-vue")['AgDSLinkListItem']
export const AgDSListItem: typeof import("agds-vue")['AgDSListItem']
export const Agdslistitem: typeof import("agds-vue")['AgDSListItem']
export const AgDSLoadingBlanket: typeof import("agds-vue")['AgDSLoadingBlanket']
export const Agdsloadingblanket: typeof import("agds-vue")['AgDSLoadingBlanket']
export const AgDSMainNav: typeof import("agds-vue")['AgDSMainNav']
export const Agdsmainnav: typeof import("agds-vue")['AgDSMainNav']
export const AgDSModal: typeof import("agds-vue")['AgDSModal']
export const Agdsmodal: typeof import("agds-vue")['AgDSModal']
export const AgDSNotificationBadge: typeof import("agds-vue")['AgDSNotificationBadge']
export const Agdsnotificationbadge: typeof import("agds-vue")['AgDSNotificationBadge']
export const AgDSOrderedList: typeof import("agds-vue")['AgDSOrderedList']
export const Agdsorderedlist: typeof import("agds-vue")['AgDSOrderedList']
export const AgDSPageAlert: typeof import("agds-vue")['AgDSPageAlert']
export const Agdspagealert: typeof import("agds-vue")['AgDSPageAlert']
export const AgDSPageContent: typeof import("agds-vue")['AgDSPageContent']
export const Agdspagecontent: typeof import("agds-vue")['AgDSPageContent']
export const AgDSPagination: typeof import("agds-vue")['AgDSPagination']
export const Agdspagination: typeof import("agds-vue")['AgDSPagination']
export const AgDSPaginationButtons: typeof import("agds-vue")['AgDSPaginationButtons']
export const Agdspaginationbuttons: typeof import("agds-vue")['AgDSPaginationButtons']
export const AgDSProgressIndicator: typeof import("agds-vue")['AgDSProgressIndicator']
export const Agdsprogressindicator: typeof import("agds-vue")['AgDSProgressIndicator']
export const AgDSProse: typeof import("agds-vue")['AgDSProse']
export const Agdsprose: typeof import("agds-vue")['AgDSProse']
export const AgDSRadio: typeof import("agds-vue")['AgDSRadio']
export const Agdsradio: typeof import("agds-vue")['AgDSRadio']
export const AgDSRadioGroup: typeof import("agds-vue")['AgDSRadioGroup']
export const Agdsradiogroup: typeof import("agds-vue")['AgDSRadioGroup']
export const AgDSSearchBox: typeof import("agds-vue")['AgDSSearchBox']
export const Agdssearchbox: typeof import("agds-vue")['AgDSSearchBox']
export const AgDSSearchBoxButton: typeof import("agds-vue")['AgDSSearchBoxButton']
export const Agdssearchboxbutton: typeof import("agds-vue")['AgDSSearchBoxButton']
export const AgDSSearchBoxInput: typeof import("agds-vue")['AgDSSearchBoxInput']
export const Agdssearchboxinput: typeof import("agds-vue")['AgDSSearchBoxInput']
export const AgDSSearchInput: typeof import("agds-vue")['AgDSSearchInput']
export const Agdssearchinput: typeof import("agds-vue")['AgDSSearchInput']
export const AgDSSectionAlert: typeof import("agds-vue")['AgDSSectionAlert']
export const Agdssectionalert: typeof import("agds-vue")['AgDSSectionAlert']
export const AgDSSectionContent: typeof import("agds-vue")['AgDSSectionContent']
export const Agdssectioncontent: typeof import("agds-vue")['AgDSSectionContent']
export const AgDSSelect: typeof import("agds-vue")['AgDSSelect']
export const Agdsselect: typeof import("agds-vue")['AgDSSelect']
export const AgDSSideNav: typeof import("agds-vue")['AgDSSideNav']
export const Agdssidenav: typeof import("agds-vue")['AgDSSideNav']
export const AgDSSkipLinks: typeof import("agds-vue")['AgDSSkipLinks']
export const Agdsskiplinks: typeof import("agds-vue")['AgDSSkipLinks']
export const AgDSStack: typeof import("agds-vue")['AgDSStack']
export const Agdsstack: typeof import("agds-vue")['AgDSStack']
export const AgDSSubNav: typeof import("agds-vue")['AgDSSubNav']
export const Agdssubnav: typeof import("agds-vue")['AgDSSubNav']
export const AgDSSummaryList: typeof import("agds-vue")['AgDSSummaryList']
export const Agdssummarylist: typeof import("agds-vue")['AgDSSummaryList']
export const AgDSSummaryListItem: typeof import("agds-vue")['AgDSSummaryListItem']
export const Agdssummarylistitem: typeof import("agds-vue")['AgDSSummaryListItem']
export const AgDSSummaryListItemAction: typeof import("agds-vue")['AgDSSummaryListItemAction']
export const Agdssummarylistitemaction: typeof import("agds-vue")['AgDSSummaryListItemAction']
export const AgDSSummaryListItemDescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
export const Agdssummarylistitemdescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
export const AgDSSummaryListItemTerm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
export const Agdssummarylistitemterm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
export const AgDSSwitch: typeof import("agds-vue")['AgDSSwitch']
export const Agdsswitch: typeof import("agds-vue")['AgDSSwitch']
export const AgDSTab: typeof import("agds-vue")['AgDSTab']
export const Agdstab: typeof import("agds-vue")['AgDSTab']
export const AgDSTable: typeof import("agds-vue")['AgDSTable']
export const Agdstable: typeof import("agds-vue")['AgDSTable']
export const AgDSTableBody: typeof import("agds-vue")['AgDSTableBody']
export const Agdstablebody: typeof import("agds-vue")['AgDSTableBody']
export const AgDSTableCaption: typeof import("agds-vue")['AgDSTableCaption']
export const Agdstablecaption: typeof import("agds-vue")['AgDSTableCaption']
export const AgDSTableCell: typeof import("agds-vue")['AgDSTableCell']
export const Agdstablecell: typeof import("agds-vue")['AgDSTableCell']
export const AgDSTableHead: typeof import("agds-vue")['AgDSTableHead']
export const Agdstablehead: typeof import("agds-vue")['AgDSTableHead']
export const AgDSTableHeader: typeof import("agds-vue")['AgDSTableHeader']
export const Agdstableheader: typeof import("agds-vue")['AgDSTableHeader']
export const AgDSTableHeaderSortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
export const Agdstableheadersortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
export const AgDSTableRow: typeof import("agds-vue")['AgDSTableRow']
export const Agdstablerow: typeof import("agds-vue")['AgDSTableRow']
export const AgDSTableScroller: typeof import("agds-vue")['AgDSTableScroller']
export const Agdstablescroller: typeof import("agds-vue")['AgDSTableScroller']
export const AgDSTabList: typeof import("agds-vue")['AgDSTabList']
export const Agdstablist: typeof import("agds-vue")['AgDSTabList']
export const AgDSTabPanel: typeof import("agds-vue")['AgDSTabPanel']
export const Agdstabpanel: typeof import("agds-vue")['AgDSTabPanel']
export const AgDSTabs: typeof import("agds-vue")['AgDSTabs']
export const Agdstabs: typeof import("agds-vue")['AgDSTabs']
export const AgDSTag: typeof import("agds-vue")['AgDSTag']
export const Agdstag: typeof import("agds-vue")['AgDSTag']
export const AgDSTags: typeof import("agds-vue")['AgDSTags']
export const Agdstags: typeof import("agds-vue")['AgDSTags']
export const AgDSText: typeof import("agds-vue")['AgDSText']
export const Agdstext: typeof import("agds-vue")['AgDSText']
export const AgDSTextarea: typeof import("agds-vue")['AgDSTextarea']
export const Agdstextarea: typeof import("agds-vue")['AgDSTextarea']
export const AgDSTextInput: typeof import("agds-vue")['AgDSTextInput']
export const Agdstextinput: typeof import("agds-vue")['AgDSTextInput']
export const AgDSTextLink: typeof import("agds-vue")['AgDSTextLink']
export const Agdstextlink: typeof import("agds-vue")['AgDSTextLink']
export const AgDSTextLinkExternal: typeof import("agds-vue")['AgDSTextLinkExternal']
export const Agdstextlinkexternal: typeof import("agds-vue")['AgDSTextLinkExternal']
export const AgDSTimeInput: typeof import("agds-vue")['AgDSTimeInput']
export const Agdstimeinput: typeof import("agds-vue")['AgDSTimeInput']
export const AgDSTimePicker: typeof import("agds-vue")['AgDSTimePicker']
export const Agdstimepicker: typeof import("agds-vue")['AgDSTimePicker']
export const AgDSToggleButton: typeof import("agds-vue")['AgDSToggleButton']
export const Agdstogglebutton: typeof import("agds-vue")['AgDSToggleButton']
export const AgDSUnorderedList: typeof import("agds-vue")['AgDSUnorderedList']
export const Agdsunorderedlist: typeof import("agds-vue")['AgDSUnorderedList']
export const AgDSVisuallyHidden: typeof import("agds-vue")['AgDSVisuallyHidden']
export const Agdsvisuallyhidden: typeof import("agds-vue")['AgDSVisuallyHidden']
export const NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
export const MDC: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAccordionDemo: LazyComponent<typeof import("../app/components/content/AccordionDemo.vue")['default']>
export const LazyBreadcrumbsDemo: LazyComponent<typeof import("../app/components/content/BreadcrumbsDemo.vue")['default']>
export const LazyComponentPreview: LazyComponent<typeof import("../app/components/content/ComponentPreview.vue")['default']>
export const LazyDocPreview: LazyComponent<typeof import("../app/components/content/DocPreview.vue")['default']>
export const LazyFeatureLinkListDemo: LazyComponent<typeof import("../app/components/content/FeatureLinkListDemo.vue")['default']>
export const LazyFilterSidebarDemo: LazyComponent<typeof import("../app/components/content/FilterSidebarDemo.vue")['default']>
export const LazyLiveCode: LazyComponent<typeof import("../app/components/content/LiveCode.vue")['default']>
export const LazyPaginationDemo: LazyComponent<typeof import("../app/components/content/PaginationDemo.vue")['default']>
export const LazyProgressIndicatorDemo: LazyComponent<typeof import("../app/components/content/ProgressIndicatorDemo.vue")['default']>
export const LazyPropsTable: LazyComponent<typeof import("../app/components/content/PropsTable.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../app/components/content/ProsePre.vue")['default']>
export const LazySideNavDemo: LazyComponent<typeof import("../app/components/content/SideNavDemo.vue")['default']>
export const LazyDocsLayout: LazyComponent<typeof import("../app/components/DocsLayout.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyContentRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyAgDSAccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
export const LazyAgdsaccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
export const LazyAgDSAccordionItem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
export const LazyAgdsaccordionitem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
export const LazyAgDSAppLayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
export const LazyAgdsapplayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
export const LazyAgDSAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
export const LazyAgdsapplayoutfooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
export const LazyAgDSAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
export const LazyAgdsapplayoutfooterdivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
export const LazyAgDSAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
export const LazyAgdsapplayoutheader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
export const LazyAgDSAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
export const LazyAgdsapplayoutsidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
export const LazyAgDSAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
export const LazyAgdsapplayoutsidebarnav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
export const LazyAgDSAutocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
export const LazyAgdsautocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
export const LazyAgDSAvatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
export const LazyAgdsavatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
export const LazyAgDSBox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
export const LazyAgdsbox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
export const LazyAgDSBreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
export const LazyAgdsbreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
export const LazyAgDSBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
export const LazyAgdsbreadcrumbsitem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
export const LazyAgDSButton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
export const LazyAgdsbutton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
export const LazyAgDSButtonLink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
export const LazyAgdsbuttonlink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
export const LazyAgDSCallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
export const LazyAgdscallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
export const LazyAgDSCallToActionButton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
export const LazyAgdscalltoactionbutton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
export const LazyAgDSCallToActionLink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
export const LazyAgdscalltoactionlink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
export const LazyAgDSCard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
export const LazyAgdscard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
export const LazyAgDSCardFooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
export const LazyAgdscardfooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
export const LazyAgDSCardHeader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
export const LazyAgdscardheader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
export const LazyAgDSCardInner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
export const LazyAgdscardinner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
export const LazyAgDSCardLink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
export const LazyAgdscardlink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
export const LazyAgDSCheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
export const LazyAgdscheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
export const LazyAgDSCheckboxGroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
export const LazyAgdscheckboxgroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
export const LazyAgDSCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
export const LazyAgdscollapsingsidebar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
export const LazyAgDSColumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
export const LazyAgdscolumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
export const LazyAgDSColumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
export const LazyAgdscolumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
export const LazyAgDSCombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
export const LazyAgdscombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
export const LazyAgDSComboboxAsync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
export const LazyAgdscomboboxasync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
export const LazyAgDSComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
export const LazyAgdscomboboxasyncmulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
export const LazyAgDSComboboxMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
export const LazyAgdscomboboxmulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
export const LazyAgDSContent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
export const LazyAgdscontent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
export const LazyAgDSContentBleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
export const LazyAgdscontentbleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
export const LazyAgDSCore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
export const LazyAgdscore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
export const LazyAgDSCoreProvider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
export const LazyAgdscoreprovider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
export const LazyAgDSDatePicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
export const LazyAgdsdatepicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
export const LazyAgDSDetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
export const LazyAgdsdetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
export const LazyAgDSDirectionButton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
export const LazyAgdsdirectionbutton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
export const LazyAgDSDirectionLink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
export const LazyAgdsdirectionlink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
export const LazyAgDSDivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
export const LazyAgdsdivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
export const LazyAgDSDrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
export const LazyAgdsdrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
export const LazyAgDSDropdownMenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
export const LazyAgdsdropdownmenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
export const LazyAgDSDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
export const LazyAgdsdropdownmenubutton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
export const LazyAgDSDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
export const LazyAgdsdropdownmenudivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
export const LazyAgDSDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
export const LazyAgdsdropdownmenugroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
export const LazyAgDSDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
export const LazyAgdsdropdownmenuitem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
export const LazyAgDSDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
export const LazyAgdsdropdownmenuitemlink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
export const LazyAgDSDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
export const LazyAgdsdropdownmenuitemradio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
export const LazyAgDSDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
export const LazyAgdsdropdownmenupanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
export const LazyAgDSExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
export const LazyAgdsexternallinkcallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
export const LazyAgDSFeatureLinkList: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
export const LazyAgdsfeaturelinklist: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
export const LazyAgDSFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
export const LazyAgdsfeaturelinklistitem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
export const LazyAgDSField: LazyComponent<typeof import("agds-vue")['AgDSField']>
export const LazyAgdsfield: LazyComponent<typeof import("agds-vue")['AgDSField']>
export const LazyAgDSFieldContainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
export const LazyAgdsfieldcontainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
export const LazyAgDSFieldHint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
export const LazyAgdsfieldhint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
export const LazyAgDSFieldLabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
export const LazyAgdsfieldlabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
export const LazyAgDSFieldMessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
export const LazyAgdsfieldmessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
export const LazyAgDSFieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
export const LazyAgdsfieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
export const LazyAgDSFileUpload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
export const LazyAgdsfileupload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
export const LazyAgDSFilterSidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
export const LazyAgdsfiltersidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
export const LazyAgDSFlex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
export const LazyAgdsflex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
export const LazyAgDSFooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
export const LazyAgdsfooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
export const LazyAgDSFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
export const LazyAgdsfooterdivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
export const LazyAgDSFormStack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
export const LazyAgdsformstack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
export const LazyAgDSGlobalAlert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
export const LazyAgdsglobalalert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
export const LazyAgDSGroupedFields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
export const LazyAgdsgroupedfields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
export const LazyAgDSHeader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
export const LazyAgdsheader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
export const LazyAgDSHeading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
export const LazyAgdsheading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
export const LazyAgDSH1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
export const LazyAgdsh1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
export const LazyAgDSH2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
export const LazyAgdsh2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
export const LazyAgDSH3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
export const LazyAgdsh3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
export const LazyAgDSH4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
export const LazyAgdsh4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
export const LazyAgDSH5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
export const LazyAgdsh5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
export const LazyAgDSH6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
export const LazyAgdsh6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
export const LazyAgDSIcon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
export const LazyAgdsicon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
export const LazyAgDSInpageNav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
export const LazyAgdsinpagenav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
export const LazyAgDSLinkList: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
export const LazyAgdslinklist: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
export const LazyAgDSLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
export const LazyAgdslinklistitem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
export const LazyAgDSListItem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
export const LazyAgdslistitem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
export const LazyAgDSLoadingBlanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
export const LazyAgdsloadingblanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
export const LazyAgDSMainNav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
export const LazyAgdsmainnav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
export const LazyAgDSModal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
export const LazyAgdsmodal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
export const LazyAgDSNotificationBadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
export const LazyAgdsnotificationbadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
export const LazyAgDSOrderedList: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
export const LazyAgdsorderedlist: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
export const LazyAgDSPageAlert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
export const LazyAgdspagealert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
export const LazyAgDSPageContent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
export const LazyAgdspagecontent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
export const LazyAgDSPagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
export const LazyAgdspagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
export const LazyAgDSPaginationButtons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
export const LazyAgdspaginationbuttons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
export const LazyAgDSProgressIndicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
export const LazyAgdsprogressindicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
export const LazyAgDSProse: LazyComponent<typeof import("agds-vue")['AgDSProse']>
export const LazyAgdsprose: LazyComponent<typeof import("agds-vue")['AgDSProse']>
export const LazyAgDSRadio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
export const LazyAgdsradio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
export const LazyAgDSRadioGroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
export const LazyAgdsradiogroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
export const LazyAgDSSearchBox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
export const LazyAgdssearchbox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
export const LazyAgDSSearchBoxButton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
export const LazyAgdssearchboxbutton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
export const LazyAgDSSearchBoxInput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
export const LazyAgdssearchboxinput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
export const LazyAgDSSearchInput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
export const LazyAgdssearchinput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
export const LazyAgDSSectionAlert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
export const LazyAgdssectionalert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
export const LazyAgDSSectionContent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
export const LazyAgdssectioncontent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
export const LazyAgDSSelect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
export const LazyAgdsselect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
export const LazyAgDSSideNav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
export const LazyAgdssidenav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
export const LazyAgDSSkipLinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
export const LazyAgdsskiplinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
export const LazyAgDSStack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
export const LazyAgdsstack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
export const LazyAgDSSubNav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
export const LazyAgdssubnav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
export const LazyAgDSSummaryList: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
export const LazyAgdssummarylist: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
export const LazyAgDSSummaryListItem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
export const LazyAgdssummarylistitem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
export const LazyAgDSSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
export const LazyAgdssummarylistitemaction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
export const LazyAgDSSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
export const LazyAgdssummarylistitemdescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
export const LazyAgDSSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
export const LazyAgdssummarylistitemterm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
export const LazyAgDSSwitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
export const LazyAgdsswitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
export const LazyAgDSTab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
export const LazyAgdstab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
export const LazyAgDSTable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
export const LazyAgdstable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
export const LazyAgDSTableBody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
export const LazyAgdstablebody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
export const LazyAgDSTableCaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
export const LazyAgdstablecaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
export const LazyAgDSTableCell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
export const LazyAgdstablecell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
export const LazyAgDSTableHead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
export const LazyAgdstablehead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
export const LazyAgDSTableHeader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
export const LazyAgdstableheader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
export const LazyAgDSTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
export const LazyAgdstableheadersortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
export const LazyAgDSTableRow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
export const LazyAgdstablerow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
export const LazyAgDSTableScroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
export const LazyAgdstablescroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
export const LazyAgDSTabList: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
export const LazyAgdstablist: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
export const LazyAgDSTabPanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
export const LazyAgdstabpanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
export const LazyAgDSTabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
export const LazyAgdstabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
export const LazyAgDSTag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
export const LazyAgdstag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
export const LazyAgDSTags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
export const LazyAgdstags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
export const LazyAgDSText: LazyComponent<typeof import("agds-vue")['AgDSText']>
export const LazyAgdstext: LazyComponent<typeof import("agds-vue")['AgDSText']>
export const LazyAgDSTextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
export const LazyAgdstextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
export const LazyAgDSTextInput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
export const LazyAgdstextinput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
export const LazyAgDSTextLink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
export const LazyAgdstextlink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
export const LazyAgDSTextLinkExternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
export const LazyAgdstextlinkexternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
export const LazyAgDSTimeInput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
export const LazyAgdstimeinput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
export const LazyAgDSTimePicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
export const LazyAgdstimepicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
export const LazyAgDSToggleButton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
export const LazyAgdstogglebutton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
export const LazyAgDSUnorderedList: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
export const LazyAgdsunorderedlist: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
export const LazyAgDSVisuallyHidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
export const LazyAgdsvisuallyhidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
export const LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyMDC: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
