/**
 * All globally-registered AGDS component names.
 * Kept as a plain string array so the Nuxt module can import it without
 * pulling in Vue components or CSS.
 */
export const componentNames = [
    'AGDSCore', 'AGDSCoreProvider',
    'AGDSBox', 'AGDSFlex',
    'AGDSColumns', 'AGDSColumn',
    'AGDSFormStack', 'AGDSStack',
    'AGDSBreadcrumbs', 'AGDSBreadcrumbsItem',
    'AGDSButton', 'AGDSButtonLink', 'AGDSToggleButton',
    'AGDSAccordion', 'AGDSAccordionItem',
    'AGDSAvatar',
    'AGDSCallout',
    'AGDSGlobalAlert', 'AGDSSectionAlert', 'AGDSPageAlert', 'AGDSStatusBadge',
    'AGDSCard', 'AGDSCardHeader', 'AGDSCardFooter', 'AGDSCardInner', 'AGDSCardLink',
    'AGDSDetails',
    'AGDSTag', 'AGDSTags',
    'AGDSFooter', 'AGDSFooterDivider',
    'AGDSHeader',
    'AGDSDivider',
    'AGDSHeading', 'AGDSH1', 'AGDSH2', 'AGDSH3', 'AGDSH4', 'AGDSH5', 'AGDSH6',
    'AGDSFeatureLinkList', 'AGDSFeatureLinkListItem',
    'AGDSLinkList', 'AGDSLinkListItem',
    'AGDSIcon',
    'AGDSUnorderedList', 'AGDSOrderedList', 'AGDSListItem',
    'AGDSText',
    'AGDSPagination', 'AGDSPaginationButtons',
    'AGDSDropdownMenu', 'AGDSDropdownMenuButton', 'AGDSDropdownMenuPanel',
    'AGDSDropdownMenuItem', 'AGDSDropdownMenuItemLink', 'AGDSDropdownMenuItemRadio',
    'AGDSDropdownMenuGroup', 'AGDSDropdownMenuDivider',
    'AGDSSideNav', 'AGDSCollapsingSideBar', 'AGDSFilterSidebar', 'AGDSSubNav', 'AGDSMainNav',
    'AGDSModal', 'AGDSDrawer',
    'AGDSTabs', 'AGDSTabList', 'AGDSTab', 'AGDSTabPanel',
    'AGDSCheckbox', 'AGDSCheckboxGroup', 'AGDSControlGroup',
    'AGDSSwitch',
    'AGDSRadio', 'AGDSRadioGroup',
    'AGDSCombobox', 'AGDSComboboxMulti', 'AGDSComboboxAsync', 'AGDSComboboxAsyncMulti', 'AGDSAutocomplete',
    'AGDSDatePicker',
    'AGDSField', 'AGDSFieldContainer', 'AGDSFieldLabel', 'AGDSFieldHint', 'AGDSFieldMessage',
    'AGDSFieldset', 'AGDSGroupedFields',
    'AGDSCallToActionLink', 'AGDSCallToActionButton',
    'AGDSDirectionLink', 'AGDSDirectionButton',
    'AGDSLoadingBlanket', 'AGDSNotificationBadge',
    'AGDSVisuallyHidden', 'AGDSExternalLinkCallout',
    'AGDSTextLink', 'AGDSTextLinkExternal',
    'AGDSInpageNav',
    'AGDSContent', 'AGDSSectionContent', 'AGDSPageContent', 'AGDSContentBleed',
    'AGDSProse', 'AGDSSkipLinks',
    'AGDSSummaryList', 'AGDSSummaryListItem', 'AGDSSummaryListItemTerm',
    'AGDSSummaryListItemDescription', 'AGDSSummaryListItemAction',
    'AGDSProgressIndicator',
    'AGDSSearchBox', 'AGDSSearchBoxInput', 'AGDSSearchBoxButton',
    'AGDSFileInput', 'AGDSFileUpload',
    'AGDSTextInput', 'AGDSTextarea', 'AGDSPasswordInput', 'AGDSSearchInput', 'AGDSSelect',
    'AGDSTimeInput', 'AGDSTimePicker',
    'AGDSTaskList', 'AGDSTaskListItem',
    'AGDSAppLayout', 'AGDSAppLayoutHeader', 'AGDSAppLayoutSidebar', 'AGDSAppLayoutSidebarNav',
    'AGDSAppLayoutFooter', 'AGDSAppLayoutFooterDivider',
    'AGDSTable', 'AGDSTableBody', 'AGDSTableCaption', 'AGDSTableHead',
    'AGDSTableHeader', 'AGDSTableHeaderSortable', 'AGDSTableCell', 'AGDSTableRow', 'AGDSTableScroller',
];
