// Styles — tokens and base must come first so components can reference them
import './styles/tokens.css';
import './styles/base.css';
// Components
export { AusGovBox } from './components/box';
export { AusGovFlex } from './components/flex';
export { AusGovColumns, AusGovColumn } from './components/columns';
export { AusGovFormStack } from './components/form-stack';
export { AusGovBreadcrumbs, AusGovBreadcrumbsItem } from './components/breadcrumbs';
export { AusGovButton, AusGovButtonLink } from './components/button';
export { AusGovAccordion, AusGovAccordionItem } from './components/accordion';
export { AusGovAvatar } from './components/avatar';
export { AusGovCallout } from './components/callout';
export { AusGovGlobalAlert } from './components/global-alert';
export { AusGovCard, AusGovCardHeader, AusGovCardFooter, AusGovCardInner, AusGovCardLink } from './components/card';
export { AusGovDetails } from './components/details';
export { AusGovTag, AusGovTags } from './components/tags';
export { AusGovFooter, AusGovFooterDivider } from './components/footer';
export { AusGovHeader } from './components/header';
export { AusGovDropdownMenu, AusGovDropdownMenuButton, AusGovDropdownMenuPanel, AusGovDropdownMenuItem, AusGovDropdownMenuItemLink, AusGovDropdownMenuItemRadio, AusGovDropdownMenuGroup, AusGovDropdownMenuDivider, } from './components/dropdown-menu';
export { AusGovDivider } from './components/divider';
export { AusGovHeading, AusGovH1, AusGovH2, AusGovH3, AusGovH4, AusGovH5, AusGovH6 } from './components/heading';
export { AusGovFeatureLinkList, AusGovFeatureLinkListItem } from './components/feature-link-list';
export { AusGovIcon } from './components/icon';
export { AusGovUnorderedList, AusGovOrderedList, AusGovListItem } from './components/list';
export { AusGovText } from './components/text';
export { AusGovPagination, AusGovPaginationButtons, usePagination } from './components/pagination';
export { AusGovModal } from './components/modal';
export { AusGovDrawer } from './components/drawer';
export { AusGovTabs, AusGovTabList, AusGovTab, AusGovTabPanel } from './components/tabs';
export { AusGovCheckbox, AusGovCheckboxGroup } from './components/checkbox';
export { CHECKBOX_GROUP_KEY } from './components/checkbox';
export { AusGovCallToActionLink, AusGovCallToActionButton } from './components/call-to-action';
export { AusGovDirectionLink, AusGovDirectionButton } from './components/direction-link';
export { AusGovComboboxAsync, AusGovAutocomplete } from './components/autocomplete';
export { AusGovMainNav } from './components/main-nav';
export { AusGovSideNav } from './components/side-nav';
export { AusGovCollapsingSideBar } from './components/collapsing-side-bar';
export { AusGovFilterSidebar } from './components/filter-sidebar';
export { AusGovSubNav } from './components/sub-nav';
export { AusGovLoadingBlanket } from './components/loading-blanket';
export { AusGovNotificationBadge } from './components/notification-badge';
export { AusGovVisuallyHidden, AusGovExternalLinkCallout } from './components/visually-hidden';
export { AusGovInpageNav } from './components/inpage-nav';
export { AusGovContent, AusGovSectionContent, AusGovPageContent, AusGovContentBleed } from './components/content';
export { AusGovProgressIndicator } from './components/progress-indicator';
export { AusGovAppLayout, AusGovAppLayoutHeader, AusGovAppLayoutSidebar, AusGovAppLayoutSidebarNav, AusGovAppLayoutFooter, AusGovAppLayoutFooterDivider, } from './components/app-layout';
export { AusGovTable, AusGovTableBody, AusGovTableCaption, AusGovTableHead, AusGovTableHeader, AusGovTableHeaderSortable, AusGovTableCell, AusGovTableRow, AusGovTableScroller, } from './components/table';
import { AusGovBox } from './components/box';
import { AusGovFlex } from './components/flex';
import { AusGovColumns, AusGovColumn } from './components/columns';
import { AusGovFormStack } from './components/form-stack';
import { AusGovBreadcrumbs, AusGovBreadcrumbsItem } from './components/breadcrumbs';
import { AusGovButton, AusGovButtonLink } from './components/button';
import { AusGovAccordion, AusGovAccordionItem } from './components/accordion';
import { AusGovAvatar } from './components/avatar';
import { AusGovCallout } from './components/callout';
import { AusGovGlobalAlert } from './components/global-alert';
import { AusGovCard, AusGovCardHeader, AusGovCardFooter, AusGovCardInner, AusGovCardLink } from './components/card';
import { AusGovDetails } from './components/details';
import { AusGovTag, AusGovTags } from './components/tags';
import { AusGovFooter, AusGovFooterDivider } from './components/footer';
import { AusGovHeader } from './components/header';
import { AusGovDivider } from './components/divider';
import { AusGovHeading, AusGovH1, AusGovH2, AusGovH3, AusGovH4, AusGovH5, AusGovH6 } from './components/heading';
import { AusGovFeatureLinkList, AusGovFeatureLinkListItem } from './components/feature-link-list';
import { AusGovIcon } from './components/icon';
import { AusGovUnorderedList, AusGovOrderedList, AusGovListItem } from './components/list';
import { AusGovText } from './components/text';
import { AusGovPagination, AusGovPaginationButtons } from './components/pagination';
import { AusGovDropdownMenu, AusGovDropdownMenuButton, AusGovDropdownMenuPanel, AusGovDropdownMenuItem, AusGovDropdownMenuItemLink, AusGovDropdownMenuItemRadio, AusGovDropdownMenuGroup, AusGovDropdownMenuDivider, } from './components/dropdown-menu';
import { AusGovSideNav } from './components/side-nav';
import { AusGovCollapsingSideBar } from './components/collapsing-side-bar';
import { AusGovFilterSidebar } from './components/filter-sidebar';
import { AusGovSubNav } from './components/sub-nav';
import { AusGovMainNav } from './components/main-nav';
import { AusGovModal } from './components/modal';
import { AusGovDrawer } from './components/drawer';
import { AusGovTabs, AusGovTabList, AusGovTab, AusGovTabPanel } from './components/tabs';
import { AusGovCheckbox, AusGovCheckboxGroup } from './components/checkbox';
import { AusGovComboboxAsync, AusGovAutocomplete } from './components/autocomplete';
import { AusGovCallToActionLink, AusGovCallToActionButton } from './components/call-to-action';
import { AusGovDirectionLink, AusGovDirectionButton } from './components/direction-link';
import { AusGovLoadingBlanket } from './components/loading-blanket';
import { AusGovNotificationBadge } from './components/notification-badge';
import { AusGovVisuallyHidden, AusGovExternalLinkCallout } from './components/visually-hidden';
import { AusGovInpageNav } from './components/inpage-nav';
import { AusGovContent, AusGovSectionContent, AusGovPageContent, AusGovContentBleed } from './components/content';
import { AusGovProgressIndicator } from './components/progress-indicator';
import { AusGovAppLayout, AusGovAppLayoutHeader, AusGovAppLayoutSidebar, AusGovAppLayoutSidebarNav, AusGovAppLayoutFooter, AusGovAppLayoutFooterDivider, } from './components/app-layout';
import { AusGovTable, AusGovTableBody, AusGovTableCaption, AusGovTableHead, AusGovTableHeader, AusGovTableHeaderSortable, AusGovTableCell, AusGovTableRow, AusGovTableScroller, } from './components/table';
export const AusGovVue = {
    install(app) {
        app.component('AusGovBox', AusGovBox);
        app.component('AusGovFlex', AusGovFlex);
        app.component('AusGovColumns', AusGovColumns);
        app.component('AusGovColumn', AusGovColumn);
        app.component('AusGovFormStack', AusGovFormStack);
        app.component('AusGovBreadcrumbs', AusGovBreadcrumbs);
        app.component('AusGovBreadcrumbsItem', AusGovBreadcrumbsItem);
        app.component('AusGovButton', AusGovButton);
        app.component('AusGovButtonLink', AusGovButtonLink);
        app.component('AusGovAccordion', AusGovAccordion);
        app.component('AusGovAccordionItem', AusGovAccordionItem);
        app.component('AusGovAvatar', AusGovAvatar);
        app.component('AusGovCallout', AusGovCallout);
        app.component('AusGovGlobalAlert', AusGovGlobalAlert);
        app.component('AusGovCard', AusGovCard);
        app.component('AusGovCardHeader', AusGovCardHeader);
        app.component('AusGovCardFooter', AusGovCardFooter);
        app.component('AusGovCardInner', AusGovCardInner);
        app.component('AusGovCardLink', AusGovCardLink);
        app.component('AusGovDetails', AusGovDetails);
        app.component('AusGovTag', AusGovTag);
        app.component('AusGovTags', AusGovTags);
        app.component('AusGovFooter', AusGovFooter);
        app.component('AusGovFooterDivider', AusGovFooterDivider);
        app.component('AusGovHeader', AusGovHeader);
        app.component('AusGovDivider', AusGovDivider);
        app.component('AusGovHeading', AusGovHeading);
        app.component('AusGovH1', AusGovH1);
        app.component('AusGovH2', AusGovH2);
        app.component('AusGovH3', AusGovH3);
        app.component('AusGovH4', AusGovH4);
        app.component('AusGovH5', AusGovH5);
        app.component('AusGovH6', AusGovH6);
        app.component('AusGovFeatureLinkList', AusGovFeatureLinkList);
        app.component('AusGovFeatureLinkListItem', AusGovFeatureLinkListItem);
        app.component('AusGovIcon', AusGovIcon);
        app.component('AusGovUnorderedList', AusGovUnorderedList);
        app.component('AusGovOrderedList', AusGovOrderedList);
        app.component('AusGovListItem', AusGovListItem);
        app.component('AusGovText', AusGovText);
        app.component('AusGovTable', AusGovTable);
        app.component('AusGovTableBody', AusGovTableBody);
        app.component('AusGovTableCaption', AusGovTableCaption);
        app.component('AusGovTableHead', AusGovTableHead);
        app.component('AusGovTableHeader', AusGovTableHeader);
        app.component('AusGovTableHeaderSortable', AusGovTableHeaderSortable);
        app.component('AusGovTableCell', AusGovTableCell);
        app.component('AusGovTableRow', AusGovTableRow);
        app.component('AusGovTableScroller', AusGovTableScroller);
        app.component('AusGovAppLayout', AusGovAppLayout);
        app.component('AusGovAppLayoutHeader', AusGovAppLayoutHeader);
        app.component('AusGovAppLayoutSidebar', AusGovAppLayoutSidebar);
        app.component('AusGovAppLayoutSidebarNav', AusGovAppLayoutSidebarNav);
        app.component('AusGovAppLayoutFooter', AusGovAppLayoutFooter);
        app.component('AusGovAppLayoutFooterDivider', AusGovAppLayoutFooterDivider);
        app.component('AusGovSideNav', AusGovSideNav);
        app.component('AusGovCollapsingSideBar', AusGovCollapsingSideBar);
        app.component('AusGovFilterSidebar', AusGovFilterSidebar);
        app.component('AusGovSubNav', AusGovSubNav);
        app.component('AusGovMainNav', AusGovMainNav);
        app.component('AusGovModal', AusGovModal);
        app.component('AusGovDrawer', AusGovDrawer);
        app.component('AusGovTabs', AusGovTabs);
        app.component('AusGovTabList', AusGovTabList);
        app.component('AusGovTab', AusGovTab);
        app.component('AusGovTabPanel', AusGovTabPanel);
        app.component('AusGovPagination', AusGovPagination);
        app.component('AusGovPaginationButtons', AusGovPaginationButtons);
        app.component('AusGovCheckbox', AusGovCheckbox);
        app.component('AusGovCheckboxGroup', AusGovCheckboxGroup);
        app.component('AusGovComboboxAsync', AusGovComboboxAsync);
        app.component('AusGovAutocomplete', AusGovAutocomplete);
        app.component('AusGovCallToActionLink', AusGovCallToActionLink);
        app.component('AusGovCallToActionButton', AusGovCallToActionButton);
        app.component('AusGovDirectionLink', AusGovDirectionLink);
        app.component('AusGovDirectionButton', AusGovDirectionButton);
        app.component('AusGovVisuallyHidden', AusGovVisuallyHidden);
        app.component('AusGovExternalLinkCallout', AusGovExternalLinkCallout);
        app.component('AusGovInpageNav', AusGovInpageNav);
        app.component('AusGovContent', AusGovContent);
        app.component('AusGovSectionContent', AusGovSectionContent);
        app.component('AusGovPageContent', AusGovPageContent);
        app.component('AusGovContentBleed', AusGovContentBleed);
        app.component('AusGovProgressIndicator', AusGovProgressIndicator);
        app.component('AusGovLoadingBlanket', AusGovLoadingBlanket);
        app.component('AusGovNotificationBadge', AusGovNotificationBadge);
        app.component('AusGovDropdownMenu', AusGovDropdownMenu);
        app.component('AusGovDropdownMenuButton', AusGovDropdownMenuButton);
        app.component('AusGovDropdownMenuPanel', AusGovDropdownMenuPanel);
        app.component('AusGovDropdownMenuItem', AusGovDropdownMenuItem);
        app.component('AusGovDropdownMenuItemLink', AusGovDropdownMenuItemLink);
        app.component('AusGovDropdownMenuItemRadio', AusGovDropdownMenuItemRadio);
        app.component('AusGovDropdownMenuGroup', AusGovDropdownMenuGroup);
        app.component('AusGovDropdownMenuDivider', AusGovDropdownMenuDivider);
    },
};
export default AusGovVue;
