
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AccordionDemo: typeof import("../../app/components/content/AccordionDemo.vue")['default']
  AvatarDemo: typeof import("../../app/components/content/AvatarDemo.vue")['default']
  BreadcrumbsDemo: typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']
  ComponentPreview: typeof import("../../app/components/content/ComponentPreview.vue")['default']
  DocPreview: typeof import("../../app/components/content/DocPreview.vue")['default']
  FeatureLinkListDemo: typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']
  FilterSidebarDemo: typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']
  LiveCode: typeof import("../../app/components/content/LiveCode.vue")['default']
  PaginationDemo: typeof import("../../app/components/content/PaginationDemo.vue")['default']
  ProgressIndicatorDemo: typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']
  PropsTable: typeof import("../../app/components/content/PropsTable.vue")['default']
  ProsePre: typeof import("../../app/components/content/ProsePre.vue")['default']
  SideNavDemo: typeof import("../../app/components/content/SideNavDemo.vue")['default']
  DocsLayout: typeof import("../../app/components/DocsLayout.vue")['default']
  ProseA: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
  ProseBlockquote: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
  ProseCode: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
  ProseEm: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
  ProseH1: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
  ProseH2: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
  ProseH3: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
  ProseH4: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
  ProseH5: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
  ProseH6: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
  ProseHr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
  ProseImg: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
  ProseLi: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
  ProseOl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
  ProseP: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
  ProseScript: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
  ProseStrong: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
  ProseTable: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
  ProseTbody: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
  ProseTd: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
  ProseTh: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
  ProseThead: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
  ProseTr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
  ProseUl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
  NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  ContentRenderer: typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
  AgDsAccordion: typeof import("agds-vue")['AgDSAccordion']
  AgDsAccordionItem: typeof import("agds-vue")['AgDSAccordionItem']
  AgDsAppLayout: typeof import("agds-vue")['AgDSAppLayout']
  AgDsAppLayoutFooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
  AgDsAppLayoutFooterDivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
  AgDsAppLayoutHeader: typeof import("agds-vue")['AgDSAppLayoutHeader']
  AgDsAppLayoutSidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
  AgDsAppLayoutSidebarNav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
  AgDsAutocomplete: typeof import("agds-vue")['AgDSAutocomplete']
  AgDsAvatar: typeof import("agds-vue")['AgDSAvatar']
  AgDsBox: typeof import("agds-vue")['AgDSBox']
  AgDsBreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
  AgDsBreadcrumbsItem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
  AgDsButton: typeof import("agds-vue")['AgDSButton']
  AgDsButtonLink: typeof import("agds-vue")['AgDSButtonLink']
  AgDsCallout: typeof import("agds-vue")['AgDSCallout']
  AgDsCallToActionButton: typeof import("agds-vue")['AgDSCallToActionButton']
  AgDsCallToActionLink: typeof import("agds-vue")['AgDSCallToActionLink']
  AgDsCard: typeof import("agds-vue")['AgDSCard']
  AgDsCardFooter: typeof import("agds-vue")['AgDSCardFooter']
  AgDsCardHeader: typeof import("agds-vue")['AgDSCardHeader']
  AgDsCardInner: typeof import("agds-vue")['AgDSCardInner']
  AgDsCardLink: typeof import("agds-vue")['AgDSCardLink']
  AgDsCheckbox: typeof import("agds-vue")['AgDSCheckbox']
  AgDsCheckboxGroup: typeof import("agds-vue")['AgDSCheckboxGroup']
  AgDsCollapsingSideBar: typeof import("agds-vue")['AgDSCollapsingSideBar']
  AgDsColumn: typeof import("agds-vue")['AgDSColumn']
  AgDsColumns: typeof import("agds-vue")['AgDSColumns']
  AgDsCombobox: typeof import("agds-vue")['AgDSCombobox']
  AgDsComboboxAsync: typeof import("agds-vue")['AgDSComboboxAsync']
  AgDsComboboxAsyncMulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
  AgDsComboboxMulti: typeof import("agds-vue")['AgDSComboboxMulti']
  AgDsContent: typeof import("agds-vue")['AgDSContent']
  AgDsContentBleed: typeof import("agds-vue")['AgDSContentBleed']
  AgDsCore: typeof import("agds-vue")['AgDSCore']
  AgDsCoreProvider: typeof import("agds-vue")['AgDSCoreProvider']
  AgDsDatePicker: typeof import("agds-vue")['AgDSDatePicker']
  AgDsDetails: typeof import("agds-vue")['AgDSDetails']
  AgDsDirectionButton: typeof import("agds-vue")['AgDSDirectionButton']
  AgDsDirectionLink: typeof import("agds-vue")['AgDSDirectionLink']
  AgDsDivider: typeof import("agds-vue")['AgDSDivider']
  AgDsDrawer: typeof import("agds-vue")['AgDSDrawer']
  AgDsDropdownMenu: typeof import("agds-vue")['AgDSDropdownMenu']
  AgDsDropdownMenuButton: typeof import("agds-vue")['AgDSDropdownMenuButton']
  AgDsDropdownMenuDivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
  AgDsDropdownMenuGroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
  AgDsDropdownMenuItem: typeof import("agds-vue")['AgDSDropdownMenuItem']
  AgDsDropdownMenuItemLink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
  AgDsDropdownMenuItemRadio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
  AgDsDropdownMenuPanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
  AgDsExternalLinkCallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
  AgDsFeatureLinkList: typeof import("agds-vue")['AgDSFeatureLinkList']
  AgDsFeatureLinkListItem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
  AgDsField: typeof import("agds-vue")['AgDSField']
  AgDsFieldContainer: typeof import("agds-vue")['AgDSFieldContainer']
  AgDsFieldHint: typeof import("agds-vue")['AgDSFieldHint']
  AgDsFieldLabel: typeof import("agds-vue")['AgDSFieldLabel']
  AgDsFieldMessage: typeof import("agds-vue")['AgDSFieldMessage']
  AgDsFieldset: typeof import("agds-vue")['AgDSFieldset']
  AgDsFileUpload: typeof import("agds-vue")['AgDSFileUpload']
  AgDsFilterSidebar: typeof import("agds-vue")['AgDSFilterSidebar']
  AgDsFlex: typeof import("agds-vue")['AgDSFlex']
  AgDsFooter: typeof import("agds-vue")['AgDSFooter']
  AgDsFooterDivider: typeof import("agds-vue")['AgDSFooterDivider']
  AgDsFormStack: typeof import("agds-vue")['AgDSFormStack']
  AgDsGlobalAlert: typeof import("agds-vue")['AgDSGlobalAlert']
  AgDsGroupedFields: typeof import("agds-vue")['AgDSGroupedFields']
  AgDsHeader: typeof import("agds-vue")['AgDSHeader']
  AgDsHeading: typeof import("agds-vue")['AgDSHeading']
  AgDSH1: typeof import("agds-vue")['AgDSH1']
  AgDSH2: typeof import("agds-vue")['AgDSH2']
  AgDSH3: typeof import("agds-vue")['AgDSH3']
  AgDSH4: typeof import("agds-vue")['AgDSH4']
  AgDSH5: typeof import("agds-vue")['AgDSH5']
  AgDSH6: typeof import("agds-vue")['AgDSH6']
  AgDsIcon: typeof import("agds-vue")['AgDSIcon']
  AgDsInpageNav: typeof import("agds-vue")['AgDSInpageNav']
  AgDsLinkList: typeof import("agds-vue")['AgDSLinkList']
  AgDsLinkListItem: typeof import("agds-vue")['AgDSLinkListItem']
  AgDsListItem: typeof import("agds-vue")['AgDSListItem']
  AgDsLoadingBlanket: typeof import("agds-vue")['AgDSLoadingBlanket']
  AgDsMainNav: typeof import("agds-vue")['AgDSMainNav']
  AgDsModal: typeof import("agds-vue")['AgDSModal']
  AgDsNotificationBadge: typeof import("agds-vue")['AgDSNotificationBadge']
  AgDsOrderedList: typeof import("agds-vue")['AgDSOrderedList']
  AgDsPageAlert: typeof import("agds-vue")['AgDSPageAlert']
  AgDsPageContent: typeof import("agds-vue")['AgDSPageContent']
  AgDsPagination: typeof import("agds-vue")['AgDSPagination']
  AgDsPaginationButtons: typeof import("agds-vue")['AgDSPaginationButtons']
  AgDsProgressIndicator: typeof import("agds-vue")['AgDSProgressIndicator']
  AgDsProse: typeof import("agds-vue")['AgDSProse']
  AgDsRadio: typeof import("agds-vue")['AgDSRadio']
  AgDsRadioGroup: typeof import("agds-vue")['AgDSRadioGroup']
  AgDsSearchBox: typeof import("agds-vue")['AgDSSearchBox']
  AgDsSearchBoxButton: typeof import("agds-vue")['AgDSSearchBoxButton']
  AgDsSearchBoxInput: typeof import("agds-vue")['AgDSSearchBoxInput']
  AgDsSearchInput: typeof import("agds-vue")['AgDSSearchInput']
  AgDsSectionAlert: typeof import("agds-vue")['AgDSSectionAlert']
  AgDsSectionContent: typeof import("agds-vue")['AgDSSectionContent']
  AgDsSelect: typeof import("agds-vue")['AgDSSelect']
  AgDsSideNav: typeof import("agds-vue")['AgDSSideNav']
  AgDsSkipLinks: typeof import("agds-vue")['AgDSSkipLinks']
  AgDsStack: typeof import("agds-vue")['AgDSStack']
  AgDsSubNav: typeof import("agds-vue")['AgDSSubNav']
  AgDsSummaryList: typeof import("agds-vue")['AgDSSummaryList']
  AgDsSummaryListItem: typeof import("agds-vue")['AgDSSummaryListItem']
  AgDsSummaryListItemAction: typeof import("agds-vue")['AgDSSummaryListItemAction']
  AgDsSummaryListItemDescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
  AgDsSummaryListItemTerm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
  AgDsSwitch: typeof import("agds-vue")['AgDSSwitch']
  AgDsTab: typeof import("agds-vue")['AgDSTab']
  AgDsTable: typeof import("agds-vue")['AgDSTable']
  AgDsTableBody: typeof import("agds-vue")['AgDSTableBody']
  AgDsTableCaption: typeof import("agds-vue")['AgDSTableCaption']
  AgDsTableCell: typeof import("agds-vue")['AgDSTableCell']
  AgDsTableHead: typeof import("agds-vue")['AgDSTableHead']
  AgDsTableHeader: typeof import("agds-vue")['AgDSTableHeader']
  AgDsTableHeaderSortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
  AgDsTableRow: typeof import("agds-vue")['AgDSTableRow']
  AgDsTableScroller: typeof import("agds-vue")['AgDSTableScroller']
  AgDsTabList: typeof import("agds-vue")['AgDSTabList']
  AgDsTabPanel: typeof import("agds-vue")['AgDSTabPanel']
  AgDsTabs: typeof import("agds-vue")['AgDSTabs']
  AgDsTag: typeof import("agds-vue")['AgDSTag']
  AgDsTags: typeof import("agds-vue")['AgDSTags']
  AgDsText: typeof import("agds-vue")['AgDSText']
  AgDsTextarea: typeof import("agds-vue")['AgDSTextarea']
  AgDsTextInput: typeof import("agds-vue")['AgDSTextInput']
  AgDsTextLink: typeof import("agds-vue")['AgDSTextLink']
  AgDsTextLinkExternal: typeof import("agds-vue")['AgDSTextLinkExternal']
  AgDsTimeInput: typeof import("agds-vue")['AgDSTimeInput']
  AgDsTimePicker: typeof import("agds-vue")['AgDSTimePicker']
  AgDsToggleButton: typeof import("agds-vue")['AgDSToggleButton']
  AgDsUnorderedList: typeof import("agds-vue")['AgDSUnorderedList']
  AgDsVisuallyHidden: typeof import("agds-vue")['AgDSVisuallyHidden']
  NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
  MDC: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
  MDCCached: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
  MDCRenderer: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
  MDCSlot: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
  NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAccordionDemo: LazyComponent<typeof import("../../app/components/content/AccordionDemo.vue")['default']>
  LazyAvatarDemo: LazyComponent<typeof import("../../app/components/content/AvatarDemo.vue")['default']>
  LazyBreadcrumbsDemo: LazyComponent<typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']>
  LazyComponentPreview: LazyComponent<typeof import("../../app/components/content/ComponentPreview.vue")['default']>
  LazyDocPreview: LazyComponent<typeof import("../../app/components/content/DocPreview.vue")['default']>
  LazyFeatureLinkListDemo: LazyComponent<typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']>
  LazyFilterSidebarDemo: LazyComponent<typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']>
  LazyLiveCode: LazyComponent<typeof import("../../app/components/content/LiveCode.vue")['default']>
  LazyPaginationDemo: LazyComponent<typeof import("../../app/components/content/PaginationDemo.vue")['default']>
  LazyProgressIndicatorDemo: LazyComponent<typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']>
  LazyPropsTable: LazyComponent<typeof import("../../app/components/content/PropsTable.vue")['default']>
  LazyProsePre: LazyComponent<typeof import("../../app/components/content/ProsePre.vue")['default']>
  LazySideNavDemo: LazyComponent<typeof import("../../app/components/content/SideNavDemo.vue")['default']>
  LazyDocsLayout: LazyComponent<typeof import("../../app/components/DocsLayout.vue")['default']>
  LazyProseA: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
  LazyProseBlockquote: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
  LazyProseCode: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
  LazyProseEm: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
  LazyProseH1: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
  LazyProseH2: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
  LazyProseH3: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
  LazyProseH4: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
  LazyProseH5: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
  LazyProseH6: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
  LazyProseHr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
  LazyProseImg: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
  LazyProseLi: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
  LazyProseOl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
  LazyProseP: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
  LazyProseScript: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
  LazyProseStrong: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
  LazyProseTable: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
  LazyProseTbody: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
  LazyProseTd: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
  LazyProseTh: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
  LazyProseThead: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
  LazyProseTr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
  LazyProseUl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyContentRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
  LazyAgDsAccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
  LazyAgDsAccordionItem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
  LazyAgDsAppLayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
  LazyAgDsAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
  LazyAgDsAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
  LazyAgDsAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
  LazyAgDsAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
  LazyAgDsAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
  LazyAgDsAutocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
  LazyAgDsAvatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
  LazyAgDsBox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
  LazyAgDsBreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
  LazyAgDsBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
  LazyAgDsButton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
  LazyAgDsButtonLink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
  LazyAgDsCallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
  LazyAgDsCallToActionButton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
  LazyAgDsCallToActionLink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
  LazyAgDsCard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
  LazyAgDsCardFooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
  LazyAgDsCardHeader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
  LazyAgDsCardInner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
  LazyAgDsCardLink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
  LazyAgDsCheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
  LazyAgDsCheckboxGroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
  LazyAgDsCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
  LazyAgDsColumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
  LazyAgDsColumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
  LazyAgDsCombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
  LazyAgDsComboboxAsync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
  LazyAgDsComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
  LazyAgDsComboboxMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
  LazyAgDsContent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
  LazyAgDsContentBleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
  LazyAgDsCore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
  LazyAgDsCoreProvider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
  LazyAgDsDatePicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
  LazyAgDsDetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
  LazyAgDsDirectionButton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
  LazyAgDsDirectionLink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
  LazyAgDsDivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
  LazyAgDsDrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
  LazyAgDsDropdownMenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
  LazyAgDsDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
  LazyAgDsDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
  LazyAgDsDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
  LazyAgDsDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
  LazyAgDsDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
  LazyAgDsDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
  LazyAgDsDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
  LazyAgDsExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
  LazyAgDsFeatureLinkList: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
  LazyAgDsFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
  LazyAgDsField: LazyComponent<typeof import("agds-vue")['AgDSField']>
  LazyAgDsFieldContainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
  LazyAgDsFieldHint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
  LazyAgDsFieldLabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
  LazyAgDsFieldMessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
  LazyAgDsFieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
  LazyAgDsFileUpload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
  LazyAgDsFilterSidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
  LazyAgDsFlex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
  LazyAgDsFooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
  LazyAgDsFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
  LazyAgDsFormStack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
  LazyAgDsGlobalAlert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
  LazyAgDsGroupedFields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
  LazyAgDsHeader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
  LazyAgDsHeading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
  LazyAgDSH1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
  LazyAgDSH2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
  LazyAgDSH3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
  LazyAgDSH4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
  LazyAgDSH5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
  LazyAgDSH6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
  LazyAgDsIcon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
  LazyAgDsInpageNav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
  LazyAgDsLinkList: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
  LazyAgDsLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
  LazyAgDsListItem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
  LazyAgDsLoadingBlanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
  LazyAgDsMainNav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
  LazyAgDsModal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
  LazyAgDsNotificationBadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
  LazyAgDsOrderedList: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
  LazyAgDsPageAlert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
  LazyAgDsPageContent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
  LazyAgDsPagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
  LazyAgDsPaginationButtons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
  LazyAgDsProgressIndicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
  LazyAgDsProse: LazyComponent<typeof import("agds-vue")['AgDSProse']>
  LazyAgDsRadio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
  LazyAgDsRadioGroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
  LazyAgDsSearchBox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
  LazyAgDsSearchBoxButton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
  LazyAgDsSearchBoxInput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
  LazyAgDsSearchInput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
  LazyAgDsSectionAlert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
  LazyAgDsSectionContent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
  LazyAgDsSelect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
  LazyAgDsSideNav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
  LazyAgDsSkipLinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
  LazyAgDsStack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
  LazyAgDsSubNav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
  LazyAgDsSummaryList: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
  LazyAgDsSummaryListItem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
  LazyAgDsSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
  LazyAgDsSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
  LazyAgDsSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
  LazyAgDsSwitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
  LazyAgDsTab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
  LazyAgDsTable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
  LazyAgDsTableBody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
  LazyAgDsTableCaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
  LazyAgDsTableCell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
  LazyAgDsTableHead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
  LazyAgDsTableHeader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
  LazyAgDsTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
  LazyAgDsTableRow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
  LazyAgDsTableScroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
  LazyAgDsTabList: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
  LazyAgDsTabPanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
  LazyAgDsTabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
  LazyAgDsTag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
  LazyAgDsTags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
  LazyAgDsText: LazyComponent<typeof import("agds-vue")['AgDSText']>
  LazyAgDsTextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
  LazyAgDsTextInput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
  LazyAgDsTextLink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
  LazyAgDsTextLinkExternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
  LazyAgDsTimeInput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
  LazyAgDsTimePicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
  LazyAgDsToggleButton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
  LazyAgDsUnorderedList: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
  LazyAgDsVisuallyHidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
  LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyMDC: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
  LazyMDCCached: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
  LazyMDCRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
  LazyMDCSlot: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
  LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
