
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AccordionDemo: typeof import("../../app/components/content/AccordionDemo.vue")['default']
  AutocompleteDemo: typeof import("../../app/components/content/AutocompleteDemo.vue")['default']
  AvatarDemo: typeof import("../../app/components/content/AvatarDemo.vue")['default']
  BreadcrumbsDemo: typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']
  CheckboxDemo: typeof import("../../app/components/content/CheckboxDemo.vue")['default']
  ComboboxAsyncMultiDemo: typeof import("../../app/components/content/ComboboxAsyncMultiDemo.vue")['default']
  ComboboxDemo: typeof import("../../app/components/content/ComboboxDemo.vue")['default']
  ComponentPreview: typeof import("../../app/components/content/ComponentPreview.vue")['default']
  DatePickerDemo: typeof import("../../app/components/content/DatePickerDemo.vue")['default']
  DocPreview: typeof import("../../app/components/content/DocPreview.vue")['default']
  FeatureLinkListDemo: typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']
  FilterSidebarDemo: typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']
  LiveCode: typeof import("../../app/components/content/LiveCode.vue")['default']
  PageAlertDemo: typeof import("../../app/components/content/PageAlertDemo.vue")['default']
  PaginationDemo: typeof import("../../app/components/content/PaginationDemo.vue")['default']
  ProgressIndicatorDemo: typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']
  PropsTable: typeof import("../../app/components/content/PropsTable.vue")['default']
  ProsePre: typeof import("../../app/components/content/ProsePre.vue")['default']
  SectionAlertDemo: typeof import("../../app/components/content/SectionAlertDemo.vue")['default']
  SideNavDemo: typeof import("../../app/components/content/SideNavDemo.vue")['default']
  SkipLinksDemo: typeof import("../../app/components/content/SkipLinksDemo.vue")['default']
  StatusBadgeDemo: typeof import("../../app/components/content/StatusBadgeDemo.vue")['default']
  TagsDemo: typeof import("../../app/components/content/TagsDemo.vue")['default']
  TaskListDemo: typeof import("../../app/components/content/TaskListDemo.vue")['default']
  DocsLayout: typeof import("../../app/components/DocsLayout.vue")['default']
  ProseA: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
  ProseBlockquote: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
  ProseCode: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
  ProseEm: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
  ProseH1: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
  ProseH2: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
  ProseH3: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
  ProseH4: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
  ProseH5: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
  ProseH6: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
  ProseHr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
  ProseImg: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
  ProseLi: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
  ProseOl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
  ProseP: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
  ProseScript: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
  ProseStrong: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
  ProseTable: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
  ProseTbody: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
  ProseTd: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
  ProseTh: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
  ProseThead: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
  ProseTr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
  ProseUl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
  NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  ContentRenderer: typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
  AGDSAccordion: typeof import("agds-vue")['AGDSAccordion']
  Agdsaccordion: typeof import("agds-vue")['AGDSAccordion']
  AGDSAccordionItem: typeof import("agds-vue")['AGDSAccordionItem']
  Agdsaccordionitem: typeof import("agds-vue")['AGDSAccordionItem']
  AGDSAppLayout: typeof import("agds-vue")['AGDSAppLayout']
  Agdsapplayout: typeof import("agds-vue")['AGDSAppLayout']
  AGDSAppLayoutFooter: typeof import("agds-vue")['AGDSAppLayoutFooter']
  Agdsapplayoutfooter: typeof import("agds-vue")['AGDSAppLayoutFooter']
  AGDSAppLayoutFooterDivider: typeof import("agds-vue")['AGDSAppLayoutFooterDivider']
  Agdsapplayoutfooterdivider: typeof import("agds-vue")['AGDSAppLayoutFooterDivider']
  AGDSAppLayoutHeader: typeof import("agds-vue")['AGDSAppLayoutHeader']
  Agdsapplayoutheader: typeof import("agds-vue")['AGDSAppLayoutHeader']
  AGDSAppLayoutSidebar: typeof import("agds-vue")['AGDSAppLayoutSidebar']
  Agdsapplayoutsidebar: typeof import("agds-vue")['AGDSAppLayoutSidebar']
  AGDSAppLayoutSidebarNav: typeof import("agds-vue")['AGDSAppLayoutSidebarNav']
  Agdsapplayoutsidebarnav: typeof import("agds-vue")['AGDSAppLayoutSidebarNav']
  AGDSAutocomplete: typeof import("agds-vue")['AGDSAutocomplete']
  Agdsautocomplete: typeof import("agds-vue")['AGDSAutocomplete']
  AGDSAvatar: typeof import("agds-vue")['AGDSAvatar']
  Agdsavatar: typeof import("agds-vue")['AGDSAvatar']
  AGDSBox: typeof import("agds-vue")['AGDSBox']
  Agdsbox: typeof import("agds-vue")['AGDSBox']
  AGDSBreadcrumbs: typeof import("agds-vue")['AGDSBreadcrumbs']
  Agdsbreadcrumbs: typeof import("agds-vue")['AGDSBreadcrumbs']
  AGDSBreadcrumbsItem: typeof import("agds-vue")['AGDSBreadcrumbsItem']
  Agdsbreadcrumbsitem: typeof import("agds-vue")['AGDSBreadcrumbsItem']
  AGDSButton: typeof import("agds-vue")['AGDSButton']
  Agdsbutton: typeof import("agds-vue")['AGDSButton']
  AGDSButtonLink: typeof import("agds-vue")['AGDSButtonLink']
  Agdsbuttonlink: typeof import("agds-vue")['AGDSButtonLink']
  AGDSCallout: typeof import("agds-vue")['AGDSCallout']
  Agdscallout: typeof import("agds-vue")['AGDSCallout']
  AGDSCallToActionButton: typeof import("agds-vue")['AGDSCallToActionButton']
  Agdscalltoactionbutton: typeof import("agds-vue")['AGDSCallToActionButton']
  AGDSCallToActionLink: typeof import("agds-vue")['AGDSCallToActionLink']
  Agdscalltoactionlink: typeof import("agds-vue")['AGDSCallToActionLink']
  AGDSCard: typeof import("agds-vue")['AGDSCard']
  Agdscard: typeof import("agds-vue")['AGDSCard']
  AGDSCardFooter: typeof import("agds-vue")['AGDSCardFooter']
  Agdscardfooter: typeof import("agds-vue")['AGDSCardFooter']
  AGDSCardHeader: typeof import("agds-vue")['AGDSCardHeader']
  Agdscardheader: typeof import("agds-vue")['AGDSCardHeader']
  AGDSCardInner: typeof import("agds-vue")['AGDSCardInner']
  Agdscardinner: typeof import("agds-vue")['AGDSCardInner']
  AGDSCardLink: typeof import("agds-vue")['AGDSCardLink']
  Agdscardlink: typeof import("agds-vue")['AGDSCardLink']
  AGDSCheckbox: typeof import("agds-vue")['AGDSCheckbox']
  Agdscheckbox: typeof import("agds-vue")['AGDSCheckbox']
  AGDSCheckboxGroup: typeof import("agds-vue")['AGDSCheckboxGroup']
  Agdscheckboxgroup: typeof import("agds-vue")['AGDSCheckboxGroup']
  AGDSCollapsingSideBar: typeof import("agds-vue")['AGDSCollapsingSideBar']
  Agdscollapsingsidebar: typeof import("agds-vue")['AGDSCollapsingSideBar']
  AGDSColumn: typeof import("agds-vue")['AGDSColumn']
  Agdscolumn: typeof import("agds-vue")['AGDSColumn']
  AGDSColumns: typeof import("agds-vue")['AGDSColumns']
  Agdscolumns: typeof import("agds-vue")['AGDSColumns']
  AGDSCombobox: typeof import("agds-vue")['AGDSCombobox']
  Agdscombobox: typeof import("agds-vue")['AGDSCombobox']
  AGDSComboboxAsync: typeof import("agds-vue")['AGDSComboboxAsync']
  Agdscomboboxasync: typeof import("agds-vue")['AGDSComboboxAsync']
  AGDSComboboxAsyncMulti: typeof import("agds-vue")['AGDSComboboxAsyncMulti']
  Agdscomboboxasyncmulti: typeof import("agds-vue")['AGDSComboboxAsyncMulti']
  AGDSComboboxMulti: typeof import("agds-vue")['AGDSComboboxMulti']
  Agdscomboboxmulti: typeof import("agds-vue")['AGDSComboboxMulti']
  AGDSContent: typeof import("agds-vue")['AGDSContent']
  Agdscontent: typeof import("agds-vue")['AGDSContent']
  AGDSContentBleed: typeof import("agds-vue")['AGDSContentBleed']
  Agdscontentbleed: typeof import("agds-vue")['AGDSContentBleed']
  AGDSCore: typeof import("agds-vue")['AGDSCore']
  Agdscore: typeof import("agds-vue")['AGDSCore']
  AGDSCoreProvider: typeof import("agds-vue")['AGDSCoreProvider']
  Agdscoreprovider: typeof import("agds-vue")['AGDSCoreProvider']
  AGDSDatePicker: typeof import("agds-vue")['AGDSDatePicker']
  Agdsdatepicker: typeof import("agds-vue")['AGDSDatePicker']
  AGDSDetails: typeof import("agds-vue")['AGDSDetails']
  Agdsdetails: typeof import("agds-vue")['AGDSDetails']
  AGDSDirectionButton: typeof import("agds-vue")['AGDSDirectionButton']
  Agdsdirectionbutton: typeof import("agds-vue")['AGDSDirectionButton']
  AGDSDirectionLink: typeof import("agds-vue")['AGDSDirectionLink']
  Agdsdirectionlink: typeof import("agds-vue")['AGDSDirectionLink']
  AGDSDivider: typeof import("agds-vue")['AGDSDivider']
  Agdsdivider: typeof import("agds-vue")['AGDSDivider']
  AGDSDrawer: typeof import("agds-vue")['AGDSDrawer']
  Agdsdrawer: typeof import("agds-vue")['AGDSDrawer']
  AGDSDropdownMenu: typeof import("agds-vue")['AGDSDropdownMenu']
  Agdsdropdownmenu: typeof import("agds-vue")['AGDSDropdownMenu']
  AGDSDropdownMenuButton: typeof import("agds-vue")['AGDSDropdownMenuButton']
  Agdsdropdownmenubutton: typeof import("agds-vue")['AGDSDropdownMenuButton']
  AGDSDropdownMenuDivider: typeof import("agds-vue")['AGDSDropdownMenuDivider']
  Agdsdropdownmenudivider: typeof import("agds-vue")['AGDSDropdownMenuDivider']
  AGDSDropdownMenuGroup: typeof import("agds-vue")['AGDSDropdownMenuGroup']
  Agdsdropdownmenugroup: typeof import("agds-vue")['AGDSDropdownMenuGroup']
  AGDSDropdownMenuItem: typeof import("agds-vue")['AGDSDropdownMenuItem']
  Agdsdropdownmenuitem: typeof import("agds-vue")['AGDSDropdownMenuItem']
  AGDSDropdownMenuItemLink: typeof import("agds-vue")['AGDSDropdownMenuItemLink']
  Agdsdropdownmenuitemlink: typeof import("agds-vue")['AGDSDropdownMenuItemLink']
  AGDSDropdownMenuItemRadio: typeof import("agds-vue")['AGDSDropdownMenuItemRadio']
  Agdsdropdownmenuitemradio: typeof import("agds-vue")['AGDSDropdownMenuItemRadio']
  AGDSDropdownMenuPanel: typeof import("agds-vue")['AGDSDropdownMenuPanel']
  Agdsdropdownmenupanel: typeof import("agds-vue")['AGDSDropdownMenuPanel']
  AGDSExternalLinkCallout: typeof import("agds-vue")['AGDSExternalLinkCallout']
  Agdsexternallinkcallout: typeof import("agds-vue")['AGDSExternalLinkCallout']
  AGDSFeatureLinkList: typeof import("agds-vue")['AGDSFeatureLinkList']
  Agdsfeaturelinklist: typeof import("agds-vue")['AGDSFeatureLinkList']
  AGDSFeatureLinkListItem: typeof import("agds-vue")['AGDSFeatureLinkListItem']
  Agdsfeaturelinklistitem: typeof import("agds-vue")['AGDSFeatureLinkListItem']
  AGDSField: typeof import("agds-vue")['AGDSField']
  Agdsfield: typeof import("agds-vue")['AGDSField']
  AGDSFieldContainer: typeof import("agds-vue")['AGDSFieldContainer']
  Agdsfieldcontainer: typeof import("agds-vue")['AGDSFieldContainer']
  AGDSFieldHint: typeof import("agds-vue")['AGDSFieldHint']
  Agdsfieldhint: typeof import("agds-vue")['AGDSFieldHint']
  AGDSFieldLabel: typeof import("agds-vue")['AGDSFieldLabel']
  Agdsfieldlabel: typeof import("agds-vue")['AGDSFieldLabel']
  AGDSFieldMessage: typeof import("agds-vue")['AGDSFieldMessage']
  Agdsfieldmessage: typeof import("agds-vue")['AGDSFieldMessage']
  AGDSFieldset: typeof import("agds-vue")['AGDSFieldset']
  Agdsfieldset: typeof import("agds-vue")['AGDSFieldset']
  AGDSFileUpload: typeof import("agds-vue")['AGDSFileUpload']
  Agdsfileupload: typeof import("agds-vue")['AGDSFileUpload']
  AGDSFilterSidebar: typeof import("agds-vue")['AGDSFilterSidebar']
  Agdsfiltersidebar: typeof import("agds-vue")['AGDSFilterSidebar']
  AGDSFlex: typeof import("agds-vue")['AGDSFlex']
  Agdsflex: typeof import("agds-vue")['AGDSFlex']
  AGDSFooter: typeof import("agds-vue")['AGDSFooter']
  Agdsfooter: typeof import("agds-vue")['AGDSFooter']
  AGDSFooterDivider: typeof import("agds-vue")['AGDSFooterDivider']
  Agdsfooterdivider: typeof import("agds-vue")['AGDSFooterDivider']
  AGDSFormStack: typeof import("agds-vue")['AGDSFormStack']
  Agdsformstack: typeof import("agds-vue")['AGDSFormStack']
  AGDSGlobalAlert: typeof import("agds-vue")['AGDSGlobalAlert']
  Agdsglobalalert: typeof import("agds-vue")['AGDSGlobalAlert']
  AGDSGroupedFields: typeof import("agds-vue")['AGDSGroupedFields']
  Agdsgroupedfields: typeof import("agds-vue")['AGDSGroupedFields']
  AGDSHeader: typeof import("agds-vue")['AGDSHeader']
  Agdsheader: typeof import("agds-vue")['AGDSHeader']
  AGDSHeading: typeof import("agds-vue")['AGDSHeading']
  Agdsheading: typeof import("agds-vue")['AGDSHeading']
  Agdsh1: typeof import("agds-vue")['AGDSH1']
  Agdsh2: typeof import("agds-vue")['AGDSH2']
  Agdsh3: typeof import("agds-vue")['AGDSH3']
  Agdsh4: typeof import("agds-vue")['AGDSH4']
  Agdsh5: typeof import("agds-vue")['AGDSH5']
  Agdsh6: typeof import("agds-vue")['AGDSH6']
  AGDSIcon: typeof import("agds-vue")['AGDSIcon']
  Agdsicon: typeof import("agds-vue")['AGDSIcon']
  AGDSInpageNav: typeof import("agds-vue")['AGDSInpageNav']
  Agdsinpagenav: typeof import("agds-vue")['AGDSInpageNav']
  AGDSLinkList: typeof import("agds-vue")['AGDSLinkList']
  Agdslinklist: typeof import("agds-vue")['AGDSLinkList']
  AGDSLinkListItem: typeof import("agds-vue")['AGDSLinkListItem']
  Agdslinklistitem: typeof import("agds-vue")['AGDSLinkListItem']
  AGDSListItem: typeof import("agds-vue")['AGDSListItem']
  Agdslistitem: typeof import("agds-vue")['AGDSListItem']
  AGDSLoadingBlanket: typeof import("agds-vue")['AGDSLoadingBlanket']
  Agdsloadingblanket: typeof import("agds-vue")['AGDSLoadingBlanket']
  AGDSMainNav: typeof import("agds-vue")['AGDSMainNav']
  Agdsmainnav: typeof import("agds-vue")['AGDSMainNav']
  AGDSModal: typeof import("agds-vue")['AGDSModal']
  Agdsmodal: typeof import("agds-vue")['AGDSModal']
  AGDSNotificationBadge: typeof import("agds-vue")['AGDSNotificationBadge']
  Agdsnotificationbadge: typeof import("agds-vue")['AGDSNotificationBadge']
  AGDSOrderedList: typeof import("agds-vue")['AGDSOrderedList']
  Agdsorderedlist: typeof import("agds-vue")['AGDSOrderedList']
  AGDSPageAlert: typeof import("agds-vue")['AGDSPageAlert']
  Agdspagealert: typeof import("agds-vue")['AGDSPageAlert']
  AGDSPageContent: typeof import("agds-vue")['AGDSPageContent']
  Agdspagecontent: typeof import("agds-vue")['AGDSPageContent']
  AGDSPagination: typeof import("agds-vue")['AGDSPagination']
  Agdspagination: typeof import("agds-vue")['AGDSPagination']
  AGDSPaginationButtons: typeof import("agds-vue")['AGDSPaginationButtons']
  Agdspaginationbuttons: typeof import("agds-vue")['AGDSPaginationButtons']
  AGDSProgressIndicator: typeof import("agds-vue")['AGDSProgressIndicator']
  Agdsprogressindicator: typeof import("agds-vue")['AGDSProgressIndicator']
  AGDSProse: typeof import("agds-vue")['AGDSProse']
  Agdsprose: typeof import("agds-vue")['AGDSProse']
  AGDSRadio: typeof import("agds-vue")['AGDSRadio']
  Agdsradio: typeof import("agds-vue")['AGDSRadio']
  AGDSRadioGroup: typeof import("agds-vue")['AGDSRadioGroup']
  Agdsradiogroup: typeof import("agds-vue")['AGDSRadioGroup']
  AGDSSearchBox: typeof import("agds-vue")['AGDSSearchBox']
  Agdssearchbox: typeof import("agds-vue")['AGDSSearchBox']
  AGDSSearchBoxButton: typeof import("agds-vue")['AGDSSearchBoxButton']
  Agdssearchboxbutton: typeof import("agds-vue")['AGDSSearchBoxButton']
  AGDSSearchBoxInput: typeof import("agds-vue")['AGDSSearchBoxInput']
  Agdssearchboxinput: typeof import("agds-vue")['AGDSSearchBoxInput']
  AGDSSearchInput: typeof import("agds-vue")['AGDSSearchInput']
  Agdssearchinput: typeof import("agds-vue")['AGDSSearchInput']
  AGDSSectionAlert: typeof import("agds-vue")['AGDSSectionAlert']
  Agdssectionalert: typeof import("agds-vue")['AGDSSectionAlert']
  AGDSSectionContent: typeof import("agds-vue")['AGDSSectionContent']
  Agdssectioncontent: typeof import("agds-vue")['AGDSSectionContent']
  AGDSSelect: typeof import("agds-vue")['AGDSSelect']
  Agdsselect: typeof import("agds-vue")['AGDSSelect']
  AGDSSideNav: typeof import("agds-vue")['AGDSSideNav']
  Agdssidenav: typeof import("agds-vue")['AGDSSideNav']
  AGDSSkipLinks: typeof import("agds-vue")['AGDSSkipLinks']
  Agdsskiplinks: typeof import("agds-vue")['AGDSSkipLinks']
  AGDSStack: typeof import("agds-vue")['AGDSStack']
  Agdsstack: typeof import("agds-vue")['AGDSStack']
  AGDSStatusBadge: typeof import("agds-vue")['AGDSStatusBadge']
  Agdsstatusbadge: typeof import("agds-vue")['AGDSStatusBadge']
  AGDSSubNav: typeof import("agds-vue")['AGDSSubNav']
  Agdssubnav: typeof import("agds-vue")['AGDSSubNav']
  AGDSSummaryList: typeof import("agds-vue")['AGDSSummaryList']
  Agdssummarylist: typeof import("agds-vue")['AGDSSummaryList']
  AGDSSummaryListItem: typeof import("agds-vue")['AGDSSummaryListItem']
  Agdssummarylistitem: typeof import("agds-vue")['AGDSSummaryListItem']
  AGDSSummaryListItemAction: typeof import("agds-vue")['AGDSSummaryListItemAction']
  Agdssummarylistitemaction: typeof import("agds-vue")['AGDSSummaryListItemAction']
  AGDSSummaryListItemDescription: typeof import("agds-vue")['AGDSSummaryListItemDescription']
  Agdssummarylistitemdescription: typeof import("agds-vue")['AGDSSummaryListItemDescription']
  AGDSSummaryListItemTerm: typeof import("agds-vue")['AGDSSummaryListItemTerm']
  Agdssummarylistitemterm: typeof import("agds-vue")['AGDSSummaryListItemTerm']
  AGDSSwitch: typeof import("agds-vue")['AGDSSwitch']
  Agdsswitch: typeof import("agds-vue")['AGDSSwitch']
  AGDSTab: typeof import("agds-vue")['AGDSTab']
  Agdstab: typeof import("agds-vue")['AGDSTab']
  AGDSTable: typeof import("agds-vue")['AGDSTable']
  Agdstable: typeof import("agds-vue")['AGDSTable']
  AGDSTableBody: typeof import("agds-vue")['AGDSTableBody']
  Agdstablebody: typeof import("agds-vue")['AGDSTableBody']
  AGDSTableCaption: typeof import("agds-vue")['AGDSTableCaption']
  Agdstablecaption: typeof import("agds-vue")['AGDSTableCaption']
  AGDSTableCell: typeof import("agds-vue")['AGDSTableCell']
  Agdstablecell: typeof import("agds-vue")['AGDSTableCell']
  AGDSTableHead: typeof import("agds-vue")['AGDSTableHead']
  Agdstablehead: typeof import("agds-vue")['AGDSTableHead']
  AGDSTableHeader: typeof import("agds-vue")['AGDSTableHeader']
  Agdstableheader: typeof import("agds-vue")['AGDSTableHeader']
  AGDSTableHeaderSortable: typeof import("agds-vue")['AGDSTableHeaderSortable']
  Agdstableheadersortable: typeof import("agds-vue")['AGDSTableHeaderSortable']
  AGDSTableRow: typeof import("agds-vue")['AGDSTableRow']
  Agdstablerow: typeof import("agds-vue")['AGDSTableRow']
  AGDSTableScroller: typeof import("agds-vue")['AGDSTableScroller']
  Agdstablescroller: typeof import("agds-vue")['AGDSTableScroller']
  AGDSTabList: typeof import("agds-vue")['AGDSTabList']
  Agdstablist: typeof import("agds-vue")['AGDSTabList']
  AGDSTabPanel: typeof import("agds-vue")['AGDSTabPanel']
  Agdstabpanel: typeof import("agds-vue")['AGDSTabPanel']
  AGDSTabs: typeof import("agds-vue")['AGDSTabs']
  Agdstabs: typeof import("agds-vue")['AGDSTabs']
  AGDSTag: typeof import("agds-vue")['AGDSTag']
  Agdstag: typeof import("agds-vue")['AGDSTag']
  AGDSTags: typeof import("agds-vue")['AGDSTags']
  Agdstags: typeof import("agds-vue")['AGDSTags']
  AGDSTaskList: typeof import("agds-vue")['AGDSTaskList']
  Agdstasklist: typeof import("agds-vue")['AGDSTaskList']
  AGDSTaskListItem: typeof import("agds-vue")['AGDSTaskListItem']
  Agdstasklistitem: typeof import("agds-vue")['AGDSTaskListItem']
  AGDSText: typeof import("agds-vue")['AGDSText']
  Agdstext: typeof import("agds-vue")['AGDSText']
  AGDSTextarea: typeof import("agds-vue")['AGDSTextarea']
  Agdstextarea: typeof import("agds-vue")['AGDSTextarea']
  AGDSTextInput: typeof import("agds-vue")['AGDSTextInput']
  Agdstextinput: typeof import("agds-vue")['AGDSTextInput']
  AGDSTextLink: typeof import("agds-vue")['AGDSTextLink']
  Agdstextlink: typeof import("agds-vue")['AGDSTextLink']
  AGDSTextLinkExternal: typeof import("agds-vue")['AGDSTextLinkExternal']
  Agdstextlinkexternal: typeof import("agds-vue")['AGDSTextLinkExternal']
  AGDSTimeInput: typeof import("agds-vue")['AGDSTimeInput']
  Agdstimeinput: typeof import("agds-vue")['AGDSTimeInput']
  AGDSTimePicker: typeof import("agds-vue")['AGDSTimePicker']
  Agdstimepicker: typeof import("agds-vue")['AGDSTimePicker']
  AGDSToggleButton: typeof import("agds-vue")['AGDSToggleButton']
  Agdstogglebutton: typeof import("agds-vue")['AGDSToggleButton']
  AGDSUnorderedList: typeof import("agds-vue")['AGDSUnorderedList']
  Agdsunorderedlist: typeof import("agds-vue")['AGDSUnorderedList']
  AGDSVisuallyHidden: typeof import("agds-vue")['AGDSVisuallyHidden']
  Agdsvisuallyhidden: typeof import("agds-vue")['AGDSVisuallyHidden']
  NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
  MDC: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
  MDCCached: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
  MDCRenderer: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
  MDCSlot: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
  NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAccordionDemo: LazyComponent<typeof import("../../app/components/content/AccordionDemo.vue")['default']>
  LazyAutocompleteDemo: LazyComponent<typeof import("../../app/components/content/AutocompleteDemo.vue")['default']>
  LazyAvatarDemo: LazyComponent<typeof import("../../app/components/content/AvatarDemo.vue")['default']>
  LazyBreadcrumbsDemo: LazyComponent<typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']>
  LazyCheckboxDemo: LazyComponent<typeof import("../../app/components/content/CheckboxDemo.vue")['default']>
  LazyComboboxAsyncMultiDemo: LazyComponent<typeof import("../../app/components/content/ComboboxAsyncMultiDemo.vue")['default']>
  LazyComboboxDemo: LazyComponent<typeof import("../../app/components/content/ComboboxDemo.vue")['default']>
  LazyComponentPreview: LazyComponent<typeof import("../../app/components/content/ComponentPreview.vue")['default']>
  LazyDatePickerDemo: LazyComponent<typeof import("../../app/components/content/DatePickerDemo.vue")['default']>
  LazyDocPreview: LazyComponent<typeof import("../../app/components/content/DocPreview.vue")['default']>
  LazyFeatureLinkListDemo: LazyComponent<typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']>
  LazyFilterSidebarDemo: LazyComponent<typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']>
  LazyLiveCode: LazyComponent<typeof import("../../app/components/content/LiveCode.vue")['default']>
  LazyPageAlertDemo: LazyComponent<typeof import("../../app/components/content/PageAlertDemo.vue")['default']>
  LazyPaginationDemo: LazyComponent<typeof import("../../app/components/content/PaginationDemo.vue")['default']>
  LazyProgressIndicatorDemo: LazyComponent<typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']>
  LazyPropsTable: LazyComponent<typeof import("../../app/components/content/PropsTable.vue")['default']>
  LazyProsePre: LazyComponent<typeof import("../../app/components/content/ProsePre.vue")['default']>
  LazySectionAlertDemo: LazyComponent<typeof import("../../app/components/content/SectionAlertDemo.vue")['default']>
  LazySideNavDemo: LazyComponent<typeof import("../../app/components/content/SideNavDemo.vue")['default']>
  LazySkipLinksDemo: LazyComponent<typeof import("../../app/components/content/SkipLinksDemo.vue")['default']>
  LazyStatusBadgeDemo: LazyComponent<typeof import("../../app/components/content/StatusBadgeDemo.vue")['default']>
  LazyTagsDemo: LazyComponent<typeof import("../../app/components/content/TagsDemo.vue")['default']>
  LazyTaskListDemo: LazyComponent<typeof import("../../app/components/content/TaskListDemo.vue")['default']>
  LazyDocsLayout: LazyComponent<typeof import("../../app/components/DocsLayout.vue")['default']>
  LazyProseA: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
  LazyProseBlockquote: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
  LazyProseCode: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
  LazyProseEm: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
  LazyProseH1: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
  LazyProseH2: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
  LazyProseH3: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
  LazyProseH4: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
  LazyProseH5: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
  LazyProseH6: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
  LazyProseHr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
  LazyProseImg: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
  LazyProseLi: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
  LazyProseOl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
  LazyProseP: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
  LazyProseScript: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
  LazyProseStrong: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
  LazyProseTable: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
  LazyProseTbody: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
  LazyProseTd: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
  LazyProseTh: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
  LazyProseThead: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
  LazyProseTr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
  LazyProseUl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyContentRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
  LazyAGDSAccordion: LazyComponent<typeof import("agds-vue")['AGDSAccordion']>
  LazyAgdsaccordion: LazyComponent<typeof import("agds-vue")['AGDSAccordion']>
  LazyAGDSAccordionItem: LazyComponent<typeof import("agds-vue")['AGDSAccordionItem']>
  LazyAgdsaccordionitem: LazyComponent<typeof import("agds-vue")['AGDSAccordionItem']>
  LazyAGDSAppLayout: LazyComponent<typeof import("agds-vue")['AGDSAppLayout']>
  LazyAgdsapplayout: LazyComponent<typeof import("agds-vue")['AGDSAppLayout']>
  LazyAGDSAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooter']>
  LazyAgdsapplayoutfooter: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooter']>
  LazyAGDSAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooterDivider']>
  LazyAgdsapplayoutfooterdivider: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutFooterDivider']>
  LazyAGDSAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutHeader']>
  LazyAgdsapplayoutheader: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutHeader']>
  LazyAGDSAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebar']>
  LazyAgdsapplayoutsidebar: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebar']>
  LazyAGDSAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebarNav']>
  LazyAgdsapplayoutsidebarnav: LazyComponent<typeof import("agds-vue")['AGDSAppLayoutSidebarNav']>
  LazyAGDSAutocomplete: LazyComponent<typeof import("agds-vue")['AGDSAutocomplete']>
  LazyAgdsautocomplete: LazyComponent<typeof import("agds-vue")['AGDSAutocomplete']>
  LazyAGDSAvatar: LazyComponent<typeof import("agds-vue")['AGDSAvatar']>
  LazyAgdsavatar: LazyComponent<typeof import("agds-vue")['AGDSAvatar']>
  LazyAGDSBox: LazyComponent<typeof import("agds-vue")['AGDSBox']>
  LazyAgdsbox: LazyComponent<typeof import("agds-vue")['AGDSBox']>
  LazyAGDSBreadcrumbs: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbs']>
  LazyAgdsbreadcrumbs: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbs']>
  LazyAGDSBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbsItem']>
  LazyAgdsbreadcrumbsitem: LazyComponent<typeof import("agds-vue")['AGDSBreadcrumbsItem']>
  LazyAGDSButton: LazyComponent<typeof import("agds-vue")['AGDSButton']>
  LazyAgdsbutton: LazyComponent<typeof import("agds-vue")['AGDSButton']>
  LazyAGDSButtonLink: LazyComponent<typeof import("agds-vue")['AGDSButtonLink']>
  LazyAgdsbuttonlink: LazyComponent<typeof import("agds-vue")['AGDSButtonLink']>
  LazyAGDSCallout: LazyComponent<typeof import("agds-vue")['AGDSCallout']>
  LazyAgdscallout: LazyComponent<typeof import("agds-vue")['AGDSCallout']>
  LazyAGDSCallToActionButton: LazyComponent<typeof import("agds-vue")['AGDSCallToActionButton']>
  LazyAgdscalltoactionbutton: LazyComponent<typeof import("agds-vue")['AGDSCallToActionButton']>
  LazyAGDSCallToActionLink: LazyComponent<typeof import("agds-vue")['AGDSCallToActionLink']>
  LazyAgdscalltoactionlink: LazyComponent<typeof import("agds-vue")['AGDSCallToActionLink']>
  LazyAGDSCard: LazyComponent<typeof import("agds-vue")['AGDSCard']>
  LazyAgdscard: LazyComponent<typeof import("agds-vue")['AGDSCard']>
  LazyAGDSCardFooter: LazyComponent<typeof import("agds-vue")['AGDSCardFooter']>
  LazyAgdscardfooter: LazyComponent<typeof import("agds-vue")['AGDSCardFooter']>
  LazyAGDSCardHeader: LazyComponent<typeof import("agds-vue")['AGDSCardHeader']>
  LazyAgdscardheader: LazyComponent<typeof import("agds-vue")['AGDSCardHeader']>
  LazyAGDSCardInner: LazyComponent<typeof import("agds-vue")['AGDSCardInner']>
  LazyAgdscardinner: LazyComponent<typeof import("agds-vue")['AGDSCardInner']>
  LazyAGDSCardLink: LazyComponent<typeof import("agds-vue")['AGDSCardLink']>
  LazyAgdscardlink: LazyComponent<typeof import("agds-vue")['AGDSCardLink']>
  LazyAGDSCheckbox: LazyComponent<typeof import("agds-vue")['AGDSCheckbox']>
  LazyAgdscheckbox: LazyComponent<typeof import("agds-vue")['AGDSCheckbox']>
  LazyAGDSCheckboxGroup: LazyComponent<typeof import("agds-vue")['AGDSCheckboxGroup']>
  LazyAgdscheckboxgroup: LazyComponent<typeof import("agds-vue")['AGDSCheckboxGroup']>
  LazyAGDSCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AGDSCollapsingSideBar']>
  LazyAgdscollapsingsidebar: LazyComponent<typeof import("agds-vue")['AGDSCollapsingSideBar']>
  LazyAGDSColumn: LazyComponent<typeof import("agds-vue")['AGDSColumn']>
  LazyAgdscolumn: LazyComponent<typeof import("agds-vue")['AGDSColumn']>
  LazyAGDSColumns: LazyComponent<typeof import("agds-vue")['AGDSColumns']>
  LazyAgdscolumns: LazyComponent<typeof import("agds-vue")['AGDSColumns']>
  LazyAGDSCombobox: LazyComponent<typeof import("agds-vue")['AGDSCombobox']>
  LazyAgdscombobox: LazyComponent<typeof import("agds-vue")['AGDSCombobox']>
  LazyAGDSComboboxAsync: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsync']>
  LazyAgdscomboboxasync: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsync']>
  LazyAGDSComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsyncMulti']>
  LazyAgdscomboboxasyncmulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxAsyncMulti']>
  LazyAGDSComboboxMulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxMulti']>
  LazyAgdscomboboxmulti: LazyComponent<typeof import("agds-vue")['AGDSComboboxMulti']>
  LazyAGDSContent: LazyComponent<typeof import("agds-vue")['AGDSContent']>
  LazyAgdscontent: LazyComponent<typeof import("agds-vue")['AGDSContent']>
  LazyAGDSContentBleed: LazyComponent<typeof import("agds-vue")['AGDSContentBleed']>
  LazyAgdscontentbleed: LazyComponent<typeof import("agds-vue")['AGDSContentBleed']>
  LazyAGDSCore: LazyComponent<typeof import("agds-vue")['AGDSCore']>
  LazyAgdscore: LazyComponent<typeof import("agds-vue")['AGDSCore']>
  LazyAGDSCoreProvider: LazyComponent<typeof import("agds-vue")['AGDSCoreProvider']>
  LazyAgdscoreprovider: LazyComponent<typeof import("agds-vue")['AGDSCoreProvider']>
  LazyAGDSDatePicker: LazyComponent<typeof import("agds-vue")['AGDSDatePicker']>
  LazyAgdsdatepicker: LazyComponent<typeof import("agds-vue")['AGDSDatePicker']>
  LazyAGDSDetails: LazyComponent<typeof import("agds-vue")['AGDSDetails']>
  LazyAgdsdetails: LazyComponent<typeof import("agds-vue")['AGDSDetails']>
  LazyAGDSDirectionButton: LazyComponent<typeof import("agds-vue")['AGDSDirectionButton']>
  LazyAgdsdirectionbutton: LazyComponent<typeof import("agds-vue")['AGDSDirectionButton']>
  LazyAGDSDirectionLink: LazyComponent<typeof import("agds-vue")['AGDSDirectionLink']>
  LazyAgdsdirectionlink: LazyComponent<typeof import("agds-vue")['AGDSDirectionLink']>
  LazyAGDSDivider: LazyComponent<typeof import("agds-vue")['AGDSDivider']>
  LazyAgdsdivider: LazyComponent<typeof import("agds-vue")['AGDSDivider']>
  LazyAGDSDrawer: LazyComponent<typeof import("agds-vue")['AGDSDrawer']>
  LazyAgdsdrawer: LazyComponent<typeof import("agds-vue")['AGDSDrawer']>
  LazyAGDSDropdownMenu: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenu']>
  LazyAgdsdropdownmenu: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenu']>
  LazyAGDSDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuButton']>
  LazyAgdsdropdownmenubutton: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuButton']>
  LazyAGDSDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuDivider']>
  LazyAgdsdropdownmenudivider: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuDivider']>
  LazyAGDSDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuGroup']>
  LazyAgdsdropdownmenugroup: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuGroup']>
  LazyAGDSDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItem']>
  LazyAgdsdropdownmenuitem: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItem']>
  LazyAGDSDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemLink']>
  LazyAgdsdropdownmenuitemlink: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemLink']>
  LazyAGDSDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemRadio']>
  LazyAgdsdropdownmenuitemradio: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuItemRadio']>
  LazyAGDSDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuPanel']>
  LazyAgdsdropdownmenupanel: LazyComponent<typeof import("agds-vue")['AGDSDropdownMenuPanel']>
  LazyAGDSExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AGDSExternalLinkCallout']>
  LazyAgdsexternallinkcallout: LazyComponent<typeof import("agds-vue")['AGDSExternalLinkCallout']>
  LazyAGDSFeatureLinkList: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkList']>
  LazyAgdsfeaturelinklist: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkList']>
  LazyAGDSFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkListItem']>
  LazyAgdsfeaturelinklistitem: LazyComponent<typeof import("agds-vue")['AGDSFeatureLinkListItem']>
  LazyAGDSField: LazyComponent<typeof import("agds-vue")['AGDSField']>
  LazyAgdsfield: LazyComponent<typeof import("agds-vue")['AGDSField']>
  LazyAGDSFieldContainer: LazyComponent<typeof import("agds-vue")['AGDSFieldContainer']>
  LazyAgdsfieldcontainer: LazyComponent<typeof import("agds-vue")['AGDSFieldContainer']>
  LazyAGDSFieldHint: LazyComponent<typeof import("agds-vue")['AGDSFieldHint']>
  LazyAgdsfieldhint: LazyComponent<typeof import("agds-vue")['AGDSFieldHint']>
  LazyAGDSFieldLabel: LazyComponent<typeof import("agds-vue")['AGDSFieldLabel']>
  LazyAgdsfieldlabel: LazyComponent<typeof import("agds-vue")['AGDSFieldLabel']>
  LazyAGDSFieldMessage: LazyComponent<typeof import("agds-vue")['AGDSFieldMessage']>
  LazyAgdsfieldmessage: LazyComponent<typeof import("agds-vue")['AGDSFieldMessage']>
  LazyAGDSFieldset: LazyComponent<typeof import("agds-vue")['AGDSFieldset']>
  LazyAgdsfieldset: LazyComponent<typeof import("agds-vue")['AGDSFieldset']>
  LazyAGDSFileUpload: LazyComponent<typeof import("agds-vue")['AGDSFileUpload']>
  LazyAgdsfileupload: LazyComponent<typeof import("agds-vue")['AGDSFileUpload']>
  LazyAGDSFilterSidebar: LazyComponent<typeof import("agds-vue")['AGDSFilterSidebar']>
  LazyAgdsfiltersidebar: LazyComponent<typeof import("agds-vue")['AGDSFilterSidebar']>
  LazyAGDSFlex: LazyComponent<typeof import("agds-vue")['AGDSFlex']>
  LazyAgdsflex: LazyComponent<typeof import("agds-vue")['AGDSFlex']>
  LazyAGDSFooter: LazyComponent<typeof import("agds-vue")['AGDSFooter']>
  LazyAgdsfooter: LazyComponent<typeof import("agds-vue")['AGDSFooter']>
  LazyAGDSFooterDivider: LazyComponent<typeof import("agds-vue")['AGDSFooterDivider']>
  LazyAgdsfooterdivider: LazyComponent<typeof import("agds-vue")['AGDSFooterDivider']>
  LazyAGDSFormStack: LazyComponent<typeof import("agds-vue")['AGDSFormStack']>
  LazyAgdsformstack: LazyComponent<typeof import("agds-vue")['AGDSFormStack']>
  LazyAGDSGlobalAlert: LazyComponent<typeof import("agds-vue")['AGDSGlobalAlert']>
  LazyAgdsglobalalert: LazyComponent<typeof import("agds-vue")['AGDSGlobalAlert']>
  LazyAGDSGroupedFields: LazyComponent<typeof import("agds-vue")['AGDSGroupedFields']>
  LazyAgdsgroupedfields: LazyComponent<typeof import("agds-vue")['AGDSGroupedFields']>
  LazyAGDSHeader: LazyComponent<typeof import("agds-vue")['AGDSHeader']>
  LazyAgdsheader: LazyComponent<typeof import("agds-vue")['AGDSHeader']>
  LazyAGDSHeading: LazyComponent<typeof import("agds-vue")['AGDSHeading']>
  LazyAgdsheading: LazyComponent<typeof import("agds-vue")['AGDSHeading']>
  LazyAgdsh1: LazyComponent<typeof import("agds-vue")['AGDSH1']>
  LazyAgdsh2: LazyComponent<typeof import("agds-vue")['AGDSH2']>
  LazyAgdsh3: LazyComponent<typeof import("agds-vue")['AGDSH3']>
  LazyAgdsh4: LazyComponent<typeof import("agds-vue")['AGDSH4']>
  LazyAgdsh5: LazyComponent<typeof import("agds-vue")['AGDSH5']>
  LazyAgdsh6: LazyComponent<typeof import("agds-vue")['AGDSH6']>
  LazyAGDSIcon: LazyComponent<typeof import("agds-vue")['AGDSIcon']>
  LazyAgdsicon: LazyComponent<typeof import("agds-vue")['AGDSIcon']>
  LazyAGDSInpageNav: LazyComponent<typeof import("agds-vue")['AGDSInpageNav']>
  LazyAgdsinpagenav: LazyComponent<typeof import("agds-vue")['AGDSInpageNav']>
  LazyAGDSLinkList: LazyComponent<typeof import("agds-vue")['AGDSLinkList']>
  LazyAgdslinklist: LazyComponent<typeof import("agds-vue")['AGDSLinkList']>
  LazyAGDSLinkListItem: LazyComponent<typeof import("agds-vue")['AGDSLinkListItem']>
  LazyAgdslinklistitem: LazyComponent<typeof import("agds-vue")['AGDSLinkListItem']>
  LazyAGDSListItem: LazyComponent<typeof import("agds-vue")['AGDSListItem']>
  LazyAgdslistitem: LazyComponent<typeof import("agds-vue")['AGDSListItem']>
  LazyAGDSLoadingBlanket: LazyComponent<typeof import("agds-vue")['AGDSLoadingBlanket']>
  LazyAgdsloadingblanket: LazyComponent<typeof import("agds-vue")['AGDSLoadingBlanket']>
  LazyAGDSMainNav: LazyComponent<typeof import("agds-vue")['AGDSMainNav']>
  LazyAgdsmainnav: LazyComponent<typeof import("agds-vue")['AGDSMainNav']>
  LazyAGDSModal: LazyComponent<typeof import("agds-vue")['AGDSModal']>
  LazyAgdsmodal: LazyComponent<typeof import("agds-vue")['AGDSModal']>
  LazyAGDSNotificationBadge: LazyComponent<typeof import("agds-vue")['AGDSNotificationBadge']>
  LazyAgdsnotificationbadge: LazyComponent<typeof import("agds-vue")['AGDSNotificationBadge']>
  LazyAGDSOrderedList: LazyComponent<typeof import("agds-vue")['AGDSOrderedList']>
  LazyAgdsorderedlist: LazyComponent<typeof import("agds-vue")['AGDSOrderedList']>
  LazyAGDSPageAlert: LazyComponent<typeof import("agds-vue")['AGDSPageAlert']>
  LazyAgdspagealert: LazyComponent<typeof import("agds-vue")['AGDSPageAlert']>
  LazyAGDSPageContent: LazyComponent<typeof import("agds-vue")['AGDSPageContent']>
  LazyAgdspagecontent: LazyComponent<typeof import("agds-vue")['AGDSPageContent']>
  LazyAGDSPagination: LazyComponent<typeof import("agds-vue")['AGDSPagination']>
  LazyAgdspagination: LazyComponent<typeof import("agds-vue")['AGDSPagination']>
  LazyAGDSPaginationButtons: LazyComponent<typeof import("agds-vue")['AGDSPaginationButtons']>
  LazyAgdspaginationbuttons: LazyComponent<typeof import("agds-vue")['AGDSPaginationButtons']>
  LazyAGDSProgressIndicator: LazyComponent<typeof import("agds-vue")['AGDSProgressIndicator']>
  LazyAgdsprogressindicator: LazyComponent<typeof import("agds-vue")['AGDSProgressIndicator']>
  LazyAGDSProse: LazyComponent<typeof import("agds-vue")['AGDSProse']>
  LazyAgdsprose: LazyComponent<typeof import("agds-vue")['AGDSProse']>
  LazyAGDSRadio: LazyComponent<typeof import("agds-vue")['AGDSRadio']>
  LazyAgdsradio: LazyComponent<typeof import("agds-vue")['AGDSRadio']>
  LazyAGDSRadioGroup: LazyComponent<typeof import("agds-vue")['AGDSRadioGroup']>
  LazyAgdsradiogroup: LazyComponent<typeof import("agds-vue")['AGDSRadioGroup']>
  LazyAGDSSearchBox: LazyComponent<typeof import("agds-vue")['AGDSSearchBox']>
  LazyAgdssearchbox: LazyComponent<typeof import("agds-vue")['AGDSSearchBox']>
  LazyAGDSSearchBoxButton: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxButton']>
  LazyAgdssearchboxbutton: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxButton']>
  LazyAGDSSearchBoxInput: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxInput']>
  LazyAgdssearchboxinput: LazyComponent<typeof import("agds-vue")['AGDSSearchBoxInput']>
  LazyAGDSSearchInput: LazyComponent<typeof import("agds-vue")['AGDSSearchInput']>
  LazyAgdssearchinput: LazyComponent<typeof import("agds-vue")['AGDSSearchInput']>
  LazyAGDSSectionAlert: LazyComponent<typeof import("agds-vue")['AGDSSectionAlert']>
  LazyAgdssectionalert: LazyComponent<typeof import("agds-vue")['AGDSSectionAlert']>
  LazyAGDSSectionContent: LazyComponent<typeof import("agds-vue")['AGDSSectionContent']>
  LazyAgdssectioncontent: LazyComponent<typeof import("agds-vue")['AGDSSectionContent']>
  LazyAGDSSelect: LazyComponent<typeof import("agds-vue")['AGDSSelect']>
  LazyAgdsselect: LazyComponent<typeof import("agds-vue")['AGDSSelect']>
  LazyAGDSSideNav: LazyComponent<typeof import("agds-vue")['AGDSSideNav']>
  LazyAgdssidenav: LazyComponent<typeof import("agds-vue")['AGDSSideNav']>
  LazyAGDSSkipLinks: LazyComponent<typeof import("agds-vue")['AGDSSkipLinks']>
  LazyAgdsskiplinks: LazyComponent<typeof import("agds-vue")['AGDSSkipLinks']>
  LazyAGDSStack: LazyComponent<typeof import("agds-vue")['AGDSStack']>
  LazyAgdsstack: LazyComponent<typeof import("agds-vue")['AGDSStack']>
  LazyAGDSStatusBadge: LazyComponent<typeof import("agds-vue")['AGDSStatusBadge']>
  LazyAgdsstatusbadge: LazyComponent<typeof import("agds-vue")['AGDSStatusBadge']>
  LazyAGDSSubNav: LazyComponent<typeof import("agds-vue")['AGDSSubNav']>
  LazyAgdssubnav: LazyComponent<typeof import("agds-vue")['AGDSSubNav']>
  LazyAGDSSummaryList: LazyComponent<typeof import("agds-vue")['AGDSSummaryList']>
  LazyAgdssummarylist: LazyComponent<typeof import("agds-vue")['AGDSSummaryList']>
  LazyAGDSSummaryListItem: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItem']>
  LazyAgdssummarylistitem: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItem']>
  LazyAGDSSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemAction']>
  LazyAgdssummarylistitemaction: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemAction']>
  LazyAGDSSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemDescription']>
  LazyAgdssummarylistitemdescription: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemDescription']>
  LazyAGDSSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemTerm']>
  LazyAgdssummarylistitemterm: LazyComponent<typeof import("agds-vue")['AGDSSummaryListItemTerm']>
  LazyAGDSSwitch: LazyComponent<typeof import("agds-vue")['AGDSSwitch']>
  LazyAgdsswitch: LazyComponent<typeof import("agds-vue")['AGDSSwitch']>
  LazyAGDSTab: LazyComponent<typeof import("agds-vue")['AGDSTab']>
  LazyAgdstab: LazyComponent<typeof import("agds-vue")['AGDSTab']>
  LazyAGDSTable: LazyComponent<typeof import("agds-vue")['AGDSTable']>
  LazyAgdstable: LazyComponent<typeof import("agds-vue")['AGDSTable']>
  LazyAGDSTableBody: LazyComponent<typeof import("agds-vue")['AGDSTableBody']>
  LazyAgdstablebody: LazyComponent<typeof import("agds-vue")['AGDSTableBody']>
  LazyAGDSTableCaption: LazyComponent<typeof import("agds-vue")['AGDSTableCaption']>
  LazyAgdstablecaption: LazyComponent<typeof import("agds-vue")['AGDSTableCaption']>
  LazyAGDSTableCell: LazyComponent<typeof import("agds-vue")['AGDSTableCell']>
  LazyAgdstablecell: LazyComponent<typeof import("agds-vue")['AGDSTableCell']>
  LazyAGDSTableHead: LazyComponent<typeof import("agds-vue")['AGDSTableHead']>
  LazyAgdstablehead: LazyComponent<typeof import("agds-vue")['AGDSTableHead']>
  LazyAGDSTableHeader: LazyComponent<typeof import("agds-vue")['AGDSTableHeader']>
  LazyAgdstableheader: LazyComponent<typeof import("agds-vue")['AGDSTableHeader']>
  LazyAGDSTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AGDSTableHeaderSortable']>
  LazyAgdstableheadersortable: LazyComponent<typeof import("agds-vue")['AGDSTableHeaderSortable']>
  LazyAGDSTableRow: LazyComponent<typeof import("agds-vue")['AGDSTableRow']>
  LazyAgdstablerow: LazyComponent<typeof import("agds-vue")['AGDSTableRow']>
  LazyAGDSTableScroller: LazyComponent<typeof import("agds-vue")['AGDSTableScroller']>
  LazyAgdstablescroller: LazyComponent<typeof import("agds-vue")['AGDSTableScroller']>
  LazyAGDSTabList: LazyComponent<typeof import("agds-vue")['AGDSTabList']>
  LazyAgdstablist: LazyComponent<typeof import("agds-vue")['AGDSTabList']>
  LazyAGDSTabPanel: LazyComponent<typeof import("agds-vue")['AGDSTabPanel']>
  LazyAgdstabpanel: LazyComponent<typeof import("agds-vue")['AGDSTabPanel']>
  LazyAGDSTabs: LazyComponent<typeof import("agds-vue")['AGDSTabs']>
  LazyAgdstabs: LazyComponent<typeof import("agds-vue")['AGDSTabs']>
  LazyAGDSTag: LazyComponent<typeof import("agds-vue")['AGDSTag']>
  LazyAgdstag: LazyComponent<typeof import("agds-vue")['AGDSTag']>
  LazyAGDSTags: LazyComponent<typeof import("agds-vue")['AGDSTags']>
  LazyAgdstags: LazyComponent<typeof import("agds-vue")['AGDSTags']>
  LazyAGDSTaskList: LazyComponent<typeof import("agds-vue")['AGDSTaskList']>
  LazyAgdstasklist: LazyComponent<typeof import("agds-vue")['AGDSTaskList']>
  LazyAGDSTaskListItem: LazyComponent<typeof import("agds-vue")['AGDSTaskListItem']>
  LazyAgdstasklistitem: LazyComponent<typeof import("agds-vue")['AGDSTaskListItem']>
  LazyAGDSText: LazyComponent<typeof import("agds-vue")['AGDSText']>
  LazyAgdstext: LazyComponent<typeof import("agds-vue")['AGDSText']>
  LazyAGDSTextarea: LazyComponent<typeof import("agds-vue")['AGDSTextarea']>
  LazyAgdstextarea: LazyComponent<typeof import("agds-vue")['AGDSTextarea']>
  LazyAGDSTextInput: LazyComponent<typeof import("agds-vue")['AGDSTextInput']>
  LazyAgdstextinput: LazyComponent<typeof import("agds-vue")['AGDSTextInput']>
  LazyAGDSTextLink: LazyComponent<typeof import("agds-vue")['AGDSTextLink']>
  LazyAgdstextlink: LazyComponent<typeof import("agds-vue")['AGDSTextLink']>
  LazyAGDSTextLinkExternal: LazyComponent<typeof import("agds-vue")['AGDSTextLinkExternal']>
  LazyAgdstextlinkexternal: LazyComponent<typeof import("agds-vue")['AGDSTextLinkExternal']>
  LazyAGDSTimeInput: LazyComponent<typeof import("agds-vue")['AGDSTimeInput']>
  LazyAgdstimeinput: LazyComponent<typeof import("agds-vue")['AGDSTimeInput']>
  LazyAGDSTimePicker: LazyComponent<typeof import("agds-vue")['AGDSTimePicker']>
  LazyAgdstimepicker: LazyComponent<typeof import("agds-vue")['AGDSTimePicker']>
  LazyAGDSToggleButton: LazyComponent<typeof import("agds-vue")['AGDSToggleButton']>
  LazyAgdstogglebutton: LazyComponent<typeof import("agds-vue")['AGDSToggleButton']>
  LazyAGDSUnorderedList: LazyComponent<typeof import("agds-vue")['AGDSUnorderedList']>
  LazyAgdsunorderedlist: LazyComponent<typeof import("agds-vue")['AGDSUnorderedList']>
  LazyAGDSVisuallyHidden: LazyComponent<typeof import("agds-vue")['AGDSVisuallyHidden']>
  LazyAgdsvisuallyhidden: LazyComponent<typeof import("agds-vue")['AGDSVisuallyHidden']>
  LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyMDC: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
  LazyMDCCached: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
  LazyMDCRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
  LazyMDCSlot: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
  LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
