
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AccordionDemo: typeof import("../../app/components/content/AccordionDemo.vue")['default']
  BreadcrumbsDemo: typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']
  ComponentPreview: typeof import("../../app/components/content/ComponentPreview.vue")['default']
  DocPreview: typeof import("../../app/components/content/DocPreview.vue")['default']
  FeatureLinkListDemo: typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']
  FilterSidebarDemo: typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']
  LiveCode: typeof import("../../app/components/content/LiveCode.vue")['default']
  PaginationDemo: typeof import("../../app/components/content/PaginationDemo.vue")['default']
  ProgressIndicatorDemo: typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']
  PropsTable: typeof import("../../app/components/content/PropsTable.vue")['default']
  ProsePre: typeof import("../../app/components/content/ProsePre.vue")['default']
  SideNavDemo: typeof import("../../app/components/content/SideNavDemo.vue")['default']
  DocsLayout: typeof import("../../app/components/DocsLayout.vue")['default']
  ProseA: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
  ProseBlockquote: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
  ProseCode: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
  ProseEm: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
  ProseH1: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
  ProseH2: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
  ProseH3: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
  ProseH4: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
  ProseH5: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
  ProseH6: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
  ProseHr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
  ProseImg: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
  ProseLi: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
  ProseOl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
  ProseP: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
  ProseScript: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
  ProseStrong: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
  ProseTable: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
  ProseTbody: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
  ProseTd: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
  ProseTh: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
  ProseThead: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
  ProseTr: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
  ProseUl: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
  NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  ContentRenderer: typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
  AgDSAccordion: typeof import("agds-vue")['AgDSAccordion']
  Agdsaccordion: typeof import("agds-vue")['AgDSAccordion']
  AgDSAccordionItem: typeof import("agds-vue")['AgDSAccordionItem']
  Agdsaccordionitem: typeof import("agds-vue")['AgDSAccordionItem']
  AgDSAppLayout: typeof import("agds-vue")['AgDSAppLayout']
  Agdsapplayout: typeof import("agds-vue")['AgDSAppLayout']
  AgDSAppLayoutFooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
  Agdsapplayoutfooter: typeof import("agds-vue")['AgDSAppLayoutFooter']
  AgDSAppLayoutFooterDivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
  Agdsapplayoutfooterdivider: typeof import("agds-vue")['AgDSAppLayoutFooterDivider']
  AgDSAppLayoutHeader: typeof import("agds-vue")['AgDSAppLayoutHeader']
  Agdsapplayoutheader: typeof import("agds-vue")['AgDSAppLayoutHeader']
  AgDSAppLayoutSidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
  Agdsapplayoutsidebar: typeof import("agds-vue")['AgDSAppLayoutSidebar']
  AgDSAppLayoutSidebarNav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
  Agdsapplayoutsidebarnav: typeof import("agds-vue")['AgDSAppLayoutSidebarNav']
  AgDSAutocomplete: typeof import("agds-vue")['AgDSAutocomplete']
  Agdsautocomplete: typeof import("agds-vue")['AgDSAutocomplete']
  AgDSAvatar: typeof import("agds-vue")['AgDSAvatar']
  Agdsavatar: typeof import("agds-vue")['AgDSAvatar']
  AgDSBox: typeof import("agds-vue")['AgDSBox']
  Agdsbox: typeof import("agds-vue")['AgDSBox']
  AgDSBreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
  Agdsbreadcrumbs: typeof import("agds-vue")['AgDSBreadcrumbs']
  AgDSBreadcrumbsItem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
  Agdsbreadcrumbsitem: typeof import("agds-vue")['AgDSBreadcrumbsItem']
  AgDSButton: typeof import("agds-vue")['AgDSButton']
  Agdsbutton: typeof import("agds-vue")['AgDSButton']
  AgDSButtonLink: typeof import("agds-vue")['AgDSButtonLink']
  Agdsbuttonlink: typeof import("agds-vue")['AgDSButtonLink']
  AgDSCallout: typeof import("agds-vue")['AgDSCallout']
  Agdscallout: typeof import("agds-vue")['AgDSCallout']
  AgDSCallToActionButton: typeof import("agds-vue")['AgDSCallToActionButton']
  Agdscalltoactionbutton: typeof import("agds-vue")['AgDSCallToActionButton']
  AgDSCallToActionLink: typeof import("agds-vue")['AgDSCallToActionLink']
  Agdscalltoactionlink: typeof import("agds-vue")['AgDSCallToActionLink']
  AgDSCard: typeof import("agds-vue")['AgDSCard']
  Agdscard: typeof import("agds-vue")['AgDSCard']
  AgDSCardFooter: typeof import("agds-vue")['AgDSCardFooter']
  Agdscardfooter: typeof import("agds-vue")['AgDSCardFooter']
  AgDSCardHeader: typeof import("agds-vue")['AgDSCardHeader']
  Agdscardheader: typeof import("agds-vue")['AgDSCardHeader']
  AgDSCardInner: typeof import("agds-vue")['AgDSCardInner']
  Agdscardinner: typeof import("agds-vue")['AgDSCardInner']
  AgDSCardLink: typeof import("agds-vue")['AgDSCardLink']
  Agdscardlink: typeof import("agds-vue")['AgDSCardLink']
  AgDSCheckbox: typeof import("agds-vue")['AgDSCheckbox']
  Agdscheckbox: typeof import("agds-vue")['AgDSCheckbox']
  AgDSCheckboxGroup: typeof import("agds-vue")['AgDSCheckboxGroup']
  Agdscheckboxgroup: typeof import("agds-vue")['AgDSCheckboxGroup']
  AgDSCollapsingSideBar: typeof import("agds-vue")['AgDSCollapsingSideBar']
  Agdscollapsingsidebar: typeof import("agds-vue")['AgDSCollapsingSideBar']
  AgDSColumn: typeof import("agds-vue")['AgDSColumn']
  Agdscolumn: typeof import("agds-vue")['AgDSColumn']
  AgDSColumns: typeof import("agds-vue")['AgDSColumns']
  Agdscolumns: typeof import("agds-vue")['AgDSColumns']
  AgDSCombobox: typeof import("agds-vue")['AgDSCombobox']
  Agdscombobox: typeof import("agds-vue")['AgDSCombobox']
  AgDSComboboxAsync: typeof import("agds-vue")['AgDSComboboxAsync']
  Agdscomboboxasync: typeof import("agds-vue")['AgDSComboboxAsync']
  AgDSComboboxAsyncMulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
  Agdscomboboxasyncmulti: typeof import("agds-vue")['AgDSComboboxAsyncMulti']
  AgDSComboboxMulti: typeof import("agds-vue")['AgDSComboboxMulti']
  Agdscomboboxmulti: typeof import("agds-vue")['AgDSComboboxMulti']
  AgDSContent: typeof import("agds-vue")['AgDSContent']
  Agdscontent: typeof import("agds-vue")['AgDSContent']
  AgDSContentBleed: typeof import("agds-vue")['AgDSContentBleed']
  Agdscontentbleed: typeof import("agds-vue")['AgDSContentBleed']
  AgDSCore: typeof import("agds-vue")['AgDSCore']
  Agdscore: typeof import("agds-vue")['AgDSCore']
  AgDSCoreProvider: typeof import("agds-vue")['AgDSCoreProvider']
  Agdscoreprovider: typeof import("agds-vue")['AgDSCoreProvider']
  AgDSDatePicker: typeof import("agds-vue")['AgDSDatePicker']
  Agdsdatepicker: typeof import("agds-vue")['AgDSDatePicker']
  AgDSDetails: typeof import("agds-vue")['AgDSDetails']
  Agdsdetails: typeof import("agds-vue")['AgDSDetails']
  AgDSDirectionButton: typeof import("agds-vue")['AgDSDirectionButton']
  Agdsdirectionbutton: typeof import("agds-vue")['AgDSDirectionButton']
  AgDSDirectionLink: typeof import("agds-vue")['AgDSDirectionLink']
  Agdsdirectionlink: typeof import("agds-vue")['AgDSDirectionLink']
  AgDSDivider: typeof import("agds-vue")['AgDSDivider']
  Agdsdivider: typeof import("agds-vue")['AgDSDivider']
  AgDSDrawer: typeof import("agds-vue")['AgDSDrawer']
  Agdsdrawer: typeof import("agds-vue")['AgDSDrawer']
  AgDSDropdownMenu: typeof import("agds-vue")['AgDSDropdownMenu']
  Agdsdropdownmenu: typeof import("agds-vue")['AgDSDropdownMenu']
  AgDSDropdownMenuButton: typeof import("agds-vue")['AgDSDropdownMenuButton']
  Agdsdropdownmenubutton: typeof import("agds-vue")['AgDSDropdownMenuButton']
  AgDSDropdownMenuDivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
  Agdsdropdownmenudivider: typeof import("agds-vue")['AgDSDropdownMenuDivider']
  AgDSDropdownMenuGroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
  Agdsdropdownmenugroup: typeof import("agds-vue")['AgDSDropdownMenuGroup']
  AgDSDropdownMenuItem: typeof import("agds-vue")['AgDSDropdownMenuItem']
  Agdsdropdownmenuitem: typeof import("agds-vue")['AgDSDropdownMenuItem']
  AgDSDropdownMenuItemLink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
  Agdsdropdownmenuitemlink: typeof import("agds-vue")['AgDSDropdownMenuItemLink']
  AgDSDropdownMenuItemRadio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
  Agdsdropdownmenuitemradio: typeof import("agds-vue")['AgDSDropdownMenuItemRadio']
  AgDSDropdownMenuPanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
  Agdsdropdownmenupanel: typeof import("agds-vue")['AgDSDropdownMenuPanel']
  AgDSExternalLinkCallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
  Agdsexternallinkcallout: typeof import("agds-vue")['AgDSExternalLinkCallout']
  AgDSFeatureLinkList: typeof import("agds-vue")['AgDSFeatureLinkList']
  Agdsfeaturelinklist: typeof import("agds-vue")['AgDSFeatureLinkList']
  AgDSFeatureLinkListItem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
  Agdsfeaturelinklistitem: typeof import("agds-vue")['AgDSFeatureLinkListItem']
  AgDSField: typeof import("agds-vue")['AgDSField']
  Agdsfield: typeof import("agds-vue")['AgDSField']
  AgDSFieldContainer: typeof import("agds-vue")['AgDSFieldContainer']
  Agdsfieldcontainer: typeof import("agds-vue")['AgDSFieldContainer']
  AgDSFieldHint: typeof import("agds-vue")['AgDSFieldHint']
  Agdsfieldhint: typeof import("agds-vue")['AgDSFieldHint']
  AgDSFieldLabel: typeof import("agds-vue")['AgDSFieldLabel']
  Agdsfieldlabel: typeof import("agds-vue")['AgDSFieldLabel']
  AgDSFieldMessage: typeof import("agds-vue")['AgDSFieldMessage']
  Agdsfieldmessage: typeof import("agds-vue")['AgDSFieldMessage']
  AgDSFieldset: typeof import("agds-vue")['AgDSFieldset']
  Agdsfieldset: typeof import("agds-vue")['AgDSFieldset']
  AgDSFileUpload: typeof import("agds-vue")['AgDSFileUpload']
  Agdsfileupload: typeof import("agds-vue")['AgDSFileUpload']
  AgDSFilterSidebar: typeof import("agds-vue")['AgDSFilterSidebar']
  Agdsfiltersidebar: typeof import("agds-vue")['AgDSFilterSidebar']
  AgDSFlex: typeof import("agds-vue")['AgDSFlex']
  Agdsflex: typeof import("agds-vue")['AgDSFlex']
  AgDSFooter: typeof import("agds-vue")['AgDSFooter']
  Agdsfooter: typeof import("agds-vue")['AgDSFooter']
  AgDSFooterDivider: typeof import("agds-vue")['AgDSFooterDivider']
  Agdsfooterdivider: typeof import("agds-vue")['AgDSFooterDivider']
  AgDSFormStack: typeof import("agds-vue")['AgDSFormStack']
  Agdsformstack: typeof import("agds-vue")['AgDSFormStack']
  AgDSGlobalAlert: typeof import("agds-vue")['AgDSGlobalAlert']
  Agdsglobalalert: typeof import("agds-vue")['AgDSGlobalAlert']
  AgDSGroupedFields: typeof import("agds-vue")['AgDSGroupedFields']
  Agdsgroupedfields: typeof import("agds-vue")['AgDSGroupedFields']
  AgDSHeader: typeof import("agds-vue")['AgDSHeader']
  Agdsheader: typeof import("agds-vue")['AgDSHeader']
  AgDSHeading: typeof import("agds-vue")['AgDSHeading']
  Agdsheading: typeof import("agds-vue")['AgDSHeading']
  AgDSH1: typeof import("agds-vue")['AgDSH1']
  Agdsh1: typeof import("agds-vue")['AgDSH1']
  AgDSH2: typeof import("agds-vue")['AgDSH2']
  Agdsh2: typeof import("agds-vue")['AgDSH2']
  AgDSH3: typeof import("agds-vue")['AgDSH3']
  Agdsh3: typeof import("agds-vue")['AgDSH3']
  AgDSH4: typeof import("agds-vue")['AgDSH4']
  Agdsh4: typeof import("agds-vue")['AgDSH4']
  AgDSH5: typeof import("agds-vue")['AgDSH5']
  Agdsh5: typeof import("agds-vue")['AgDSH5']
  AgDSH6: typeof import("agds-vue")['AgDSH6']
  Agdsh6: typeof import("agds-vue")['AgDSH6']
  AgDSIcon: typeof import("agds-vue")['AgDSIcon']
  Agdsicon: typeof import("agds-vue")['AgDSIcon']
  AgDSInpageNav: typeof import("agds-vue")['AgDSInpageNav']
  Agdsinpagenav: typeof import("agds-vue")['AgDSInpageNav']
  AgDSLinkList: typeof import("agds-vue")['AgDSLinkList']
  Agdslinklist: typeof import("agds-vue")['AgDSLinkList']
  AgDSLinkListItem: typeof import("agds-vue")['AgDSLinkListItem']
  Agdslinklistitem: typeof import("agds-vue")['AgDSLinkListItem']
  AgDSListItem: typeof import("agds-vue")['AgDSListItem']
  Agdslistitem: typeof import("agds-vue")['AgDSListItem']
  AgDSLoadingBlanket: typeof import("agds-vue")['AgDSLoadingBlanket']
  Agdsloadingblanket: typeof import("agds-vue")['AgDSLoadingBlanket']
  AgDSMainNav: typeof import("agds-vue")['AgDSMainNav']
  Agdsmainnav: typeof import("agds-vue")['AgDSMainNav']
  AgDSModal: typeof import("agds-vue")['AgDSModal']
  Agdsmodal: typeof import("agds-vue")['AgDSModal']
  AgDSNotificationBadge: typeof import("agds-vue")['AgDSNotificationBadge']
  Agdsnotificationbadge: typeof import("agds-vue")['AgDSNotificationBadge']
  AgDSOrderedList: typeof import("agds-vue")['AgDSOrderedList']
  Agdsorderedlist: typeof import("agds-vue")['AgDSOrderedList']
  AgDSPageAlert: typeof import("agds-vue")['AgDSPageAlert']
  Agdspagealert: typeof import("agds-vue")['AgDSPageAlert']
  AgDSPageContent: typeof import("agds-vue")['AgDSPageContent']
  Agdspagecontent: typeof import("agds-vue")['AgDSPageContent']
  AgDSPagination: typeof import("agds-vue")['AgDSPagination']
  Agdspagination: typeof import("agds-vue")['AgDSPagination']
  AgDSPaginationButtons: typeof import("agds-vue")['AgDSPaginationButtons']
  Agdspaginationbuttons: typeof import("agds-vue")['AgDSPaginationButtons']
  AgDSProgressIndicator: typeof import("agds-vue")['AgDSProgressIndicator']
  Agdsprogressindicator: typeof import("agds-vue")['AgDSProgressIndicator']
  AgDSProse: typeof import("agds-vue")['AgDSProse']
  Agdsprose: typeof import("agds-vue")['AgDSProse']
  AgDSRadio: typeof import("agds-vue")['AgDSRadio']
  Agdsradio: typeof import("agds-vue")['AgDSRadio']
  AgDSRadioGroup: typeof import("agds-vue")['AgDSRadioGroup']
  Agdsradiogroup: typeof import("agds-vue")['AgDSRadioGroup']
  AgDSSearchBox: typeof import("agds-vue")['AgDSSearchBox']
  Agdssearchbox: typeof import("agds-vue")['AgDSSearchBox']
  AgDSSearchBoxButton: typeof import("agds-vue")['AgDSSearchBoxButton']
  Agdssearchboxbutton: typeof import("agds-vue")['AgDSSearchBoxButton']
  AgDSSearchBoxInput: typeof import("agds-vue")['AgDSSearchBoxInput']
  Agdssearchboxinput: typeof import("agds-vue")['AgDSSearchBoxInput']
  AgDSSearchInput: typeof import("agds-vue")['AgDSSearchInput']
  Agdssearchinput: typeof import("agds-vue")['AgDSSearchInput']
  AgDSSectionAlert: typeof import("agds-vue")['AgDSSectionAlert']
  Agdssectionalert: typeof import("agds-vue")['AgDSSectionAlert']
  AgDSSectionContent: typeof import("agds-vue")['AgDSSectionContent']
  Agdssectioncontent: typeof import("agds-vue")['AgDSSectionContent']
  AgDSSelect: typeof import("agds-vue")['AgDSSelect']
  Agdsselect: typeof import("agds-vue")['AgDSSelect']
  AgDSSideNav: typeof import("agds-vue")['AgDSSideNav']
  Agdssidenav: typeof import("agds-vue")['AgDSSideNav']
  AgDSSkipLinks: typeof import("agds-vue")['AgDSSkipLinks']
  Agdsskiplinks: typeof import("agds-vue")['AgDSSkipLinks']
  AgDSStack: typeof import("agds-vue")['AgDSStack']
  Agdsstack: typeof import("agds-vue")['AgDSStack']
  AgDSSubNav: typeof import("agds-vue")['AgDSSubNav']
  Agdssubnav: typeof import("agds-vue")['AgDSSubNav']
  AgDSSummaryList: typeof import("agds-vue")['AgDSSummaryList']
  Agdssummarylist: typeof import("agds-vue")['AgDSSummaryList']
  AgDSSummaryListItem: typeof import("agds-vue")['AgDSSummaryListItem']
  Agdssummarylistitem: typeof import("agds-vue")['AgDSSummaryListItem']
  AgDSSummaryListItemAction: typeof import("agds-vue")['AgDSSummaryListItemAction']
  Agdssummarylistitemaction: typeof import("agds-vue")['AgDSSummaryListItemAction']
  AgDSSummaryListItemDescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
  Agdssummarylistitemdescription: typeof import("agds-vue")['AgDSSummaryListItemDescription']
  AgDSSummaryListItemTerm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
  Agdssummarylistitemterm: typeof import("agds-vue")['AgDSSummaryListItemTerm']
  AgDSSwitch: typeof import("agds-vue")['AgDSSwitch']
  Agdsswitch: typeof import("agds-vue")['AgDSSwitch']
  AgDSTab: typeof import("agds-vue")['AgDSTab']
  Agdstab: typeof import("agds-vue")['AgDSTab']
  AgDSTable: typeof import("agds-vue")['AgDSTable']
  Agdstable: typeof import("agds-vue")['AgDSTable']
  AgDSTableBody: typeof import("agds-vue")['AgDSTableBody']
  Agdstablebody: typeof import("agds-vue")['AgDSTableBody']
  AgDSTableCaption: typeof import("agds-vue")['AgDSTableCaption']
  Agdstablecaption: typeof import("agds-vue")['AgDSTableCaption']
  AgDSTableCell: typeof import("agds-vue")['AgDSTableCell']
  Agdstablecell: typeof import("agds-vue")['AgDSTableCell']
  AgDSTableHead: typeof import("agds-vue")['AgDSTableHead']
  Agdstablehead: typeof import("agds-vue")['AgDSTableHead']
  AgDSTableHeader: typeof import("agds-vue")['AgDSTableHeader']
  Agdstableheader: typeof import("agds-vue")['AgDSTableHeader']
  AgDSTableHeaderSortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
  Agdstableheadersortable: typeof import("agds-vue")['AgDSTableHeaderSortable']
  AgDSTableRow: typeof import("agds-vue")['AgDSTableRow']
  Agdstablerow: typeof import("agds-vue")['AgDSTableRow']
  AgDSTableScroller: typeof import("agds-vue")['AgDSTableScroller']
  Agdstablescroller: typeof import("agds-vue")['AgDSTableScroller']
  AgDSTabList: typeof import("agds-vue")['AgDSTabList']
  Agdstablist: typeof import("agds-vue")['AgDSTabList']
  AgDSTabPanel: typeof import("agds-vue")['AgDSTabPanel']
  Agdstabpanel: typeof import("agds-vue")['AgDSTabPanel']
  AgDSTabs: typeof import("agds-vue")['AgDSTabs']
  Agdstabs: typeof import("agds-vue")['AgDSTabs']
  AgDSTag: typeof import("agds-vue")['AgDSTag']
  Agdstag: typeof import("agds-vue")['AgDSTag']
  AgDSTags: typeof import("agds-vue")['AgDSTags']
  Agdstags: typeof import("agds-vue")['AgDSTags']
  AgDSText: typeof import("agds-vue")['AgDSText']
  Agdstext: typeof import("agds-vue")['AgDSText']
  AgDSTextarea: typeof import("agds-vue")['AgDSTextarea']
  Agdstextarea: typeof import("agds-vue")['AgDSTextarea']
  AgDSTextInput: typeof import("agds-vue")['AgDSTextInput']
  Agdstextinput: typeof import("agds-vue")['AgDSTextInput']
  AgDSTextLink: typeof import("agds-vue")['AgDSTextLink']
  Agdstextlink: typeof import("agds-vue")['AgDSTextLink']
  AgDSTextLinkExternal: typeof import("agds-vue")['AgDSTextLinkExternal']
  Agdstextlinkexternal: typeof import("agds-vue")['AgDSTextLinkExternal']
  AgDSTimeInput: typeof import("agds-vue")['AgDSTimeInput']
  Agdstimeinput: typeof import("agds-vue")['AgDSTimeInput']
  AgDSTimePicker: typeof import("agds-vue")['AgDSTimePicker']
  Agdstimepicker: typeof import("agds-vue")['AgDSTimePicker']
  AgDSToggleButton: typeof import("agds-vue")['AgDSToggleButton']
  Agdstogglebutton: typeof import("agds-vue")['AgDSToggleButton']
  AgDSUnorderedList: typeof import("agds-vue")['AgDSUnorderedList']
  Agdsunorderedlist: typeof import("agds-vue")['AgDSUnorderedList']
  AgDSVisuallyHidden: typeof import("agds-vue")['AgDSVisuallyHidden']
  Agdsvisuallyhidden: typeof import("agds-vue")['AgDSVisuallyHidden']
  NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']
  MDC: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
  MDCCached: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
  MDCRenderer: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
  MDCSlot: typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
  NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAccordionDemo: LazyComponent<typeof import("../../app/components/content/AccordionDemo.vue")['default']>
  LazyBreadcrumbsDemo: LazyComponent<typeof import("../../app/components/content/BreadcrumbsDemo.vue")['default']>
  LazyComponentPreview: LazyComponent<typeof import("../../app/components/content/ComponentPreview.vue")['default']>
  LazyDocPreview: LazyComponent<typeof import("../../app/components/content/DocPreview.vue")['default']>
  LazyFeatureLinkListDemo: LazyComponent<typeof import("../../app/components/content/FeatureLinkListDemo.vue")['default']>
  LazyFilterSidebarDemo: LazyComponent<typeof import("../../app/components/content/FilterSidebarDemo.vue")['default']>
  LazyLiveCode: LazyComponent<typeof import("../../app/components/content/LiveCode.vue")['default']>
  LazyPaginationDemo: LazyComponent<typeof import("../../app/components/content/PaginationDemo.vue")['default']>
  LazyProgressIndicatorDemo: LazyComponent<typeof import("../../app/components/content/ProgressIndicatorDemo.vue")['default']>
  LazyPropsTable: LazyComponent<typeof import("../../app/components/content/PropsTable.vue")['default']>
  LazyProsePre: LazyComponent<typeof import("../../app/components/content/ProsePre.vue")['default']>
  LazySideNavDemo: LazyComponent<typeof import("../../app/components/content/SideNavDemo.vue")['default']>
  LazyDocsLayout: LazyComponent<typeof import("../../app/components/DocsLayout.vue")['default']>
  LazyProseA: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
  LazyProseBlockquote: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
  LazyProseCode: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
  LazyProseEm: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
  LazyProseH1: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
  LazyProseH2: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
  LazyProseH3: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
  LazyProseH4: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
  LazyProseH5: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
  LazyProseH6: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
  LazyProseHr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
  LazyProseImg: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
  LazyProseLi: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
  LazyProseOl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
  LazyProseP: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
  LazyProseScript: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
  LazyProseStrong: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
  LazyProseTable: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
  LazyProseTbody: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
  LazyProseTd: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
  LazyProseTh: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
  LazyProseThead: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
  LazyProseTr: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
  LazyProseUl: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyContentRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
  LazyAgDSAccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
  LazyAgdsaccordion: LazyComponent<typeof import("agds-vue")['AgDSAccordion']>
  LazyAgDSAccordionItem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
  LazyAgdsaccordionitem: LazyComponent<typeof import("agds-vue")['AgDSAccordionItem']>
  LazyAgDSAppLayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
  LazyAgdsapplayout: LazyComponent<typeof import("agds-vue")['AgDSAppLayout']>
  LazyAgDSAppLayoutFooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
  LazyAgdsapplayoutfooter: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooter']>
  LazyAgDSAppLayoutFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
  LazyAgdsapplayoutfooterdivider: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutFooterDivider']>
  LazyAgDSAppLayoutHeader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
  LazyAgdsapplayoutheader: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutHeader']>
  LazyAgDSAppLayoutSidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
  LazyAgdsapplayoutsidebar: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebar']>
  LazyAgDSAppLayoutSidebarNav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
  LazyAgdsapplayoutsidebarnav: LazyComponent<typeof import("agds-vue")['AgDSAppLayoutSidebarNav']>
  LazyAgDSAutocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
  LazyAgdsautocomplete: LazyComponent<typeof import("agds-vue")['AgDSAutocomplete']>
  LazyAgDSAvatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
  LazyAgdsavatar: LazyComponent<typeof import("agds-vue")['AgDSAvatar']>
  LazyAgDSBox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
  LazyAgdsbox: LazyComponent<typeof import("agds-vue")['AgDSBox']>
  LazyAgDSBreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
  LazyAgdsbreadcrumbs: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbs']>
  LazyAgDSBreadcrumbsItem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
  LazyAgdsbreadcrumbsitem: LazyComponent<typeof import("agds-vue")['AgDSBreadcrumbsItem']>
  LazyAgDSButton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
  LazyAgdsbutton: LazyComponent<typeof import("agds-vue")['AgDSButton']>
  LazyAgDSButtonLink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
  LazyAgdsbuttonlink: LazyComponent<typeof import("agds-vue")['AgDSButtonLink']>
  LazyAgDSCallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
  LazyAgdscallout: LazyComponent<typeof import("agds-vue")['AgDSCallout']>
  LazyAgDSCallToActionButton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
  LazyAgdscalltoactionbutton: LazyComponent<typeof import("agds-vue")['AgDSCallToActionButton']>
  LazyAgDSCallToActionLink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
  LazyAgdscalltoactionlink: LazyComponent<typeof import("agds-vue")['AgDSCallToActionLink']>
  LazyAgDSCard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
  LazyAgdscard: LazyComponent<typeof import("agds-vue")['AgDSCard']>
  LazyAgDSCardFooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
  LazyAgdscardfooter: LazyComponent<typeof import("agds-vue")['AgDSCardFooter']>
  LazyAgDSCardHeader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
  LazyAgdscardheader: LazyComponent<typeof import("agds-vue")['AgDSCardHeader']>
  LazyAgDSCardInner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
  LazyAgdscardinner: LazyComponent<typeof import("agds-vue")['AgDSCardInner']>
  LazyAgDSCardLink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
  LazyAgdscardlink: LazyComponent<typeof import("agds-vue")['AgDSCardLink']>
  LazyAgDSCheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
  LazyAgdscheckbox: LazyComponent<typeof import("agds-vue")['AgDSCheckbox']>
  LazyAgDSCheckboxGroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
  LazyAgdscheckboxgroup: LazyComponent<typeof import("agds-vue")['AgDSCheckboxGroup']>
  LazyAgDSCollapsingSideBar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
  LazyAgdscollapsingsidebar: LazyComponent<typeof import("agds-vue")['AgDSCollapsingSideBar']>
  LazyAgDSColumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
  LazyAgdscolumn: LazyComponent<typeof import("agds-vue")['AgDSColumn']>
  LazyAgDSColumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
  LazyAgdscolumns: LazyComponent<typeof import("agds-vue")['AgDSColumns']>
  LazyAgDSCombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
  LazyAgdscombobox: LazyComponent<typeof import("agds-vue")['AgDSCombobox']>
  LazyAgDSComboboxAsync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
  LazyAgdscomboboxasync: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsync']>
  LazyAgDSComboboxAsyncMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
  LazyAgdscomboboxasyncmulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxAsyncMulti']>
  LazyAgDSComboboxMulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
  LazyAgdscomboboxmulti: LazyComponent<typeof import("agds-vue")['AgDSComboboxMulti']>
  LazyAgDSContent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
  LazyAgdscontent: LazyComponent<typeof import("agds-vue")['AgDSContent']>
  LazyAgDSContentBleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
  LazyAgdscontentbleed: LazyComponent<typeof import("agds-vue")['AgDSContentBleed']>
  LazyAgDSCore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
  LazyAgdscore: LazyComponent<typeof import("agds-vue")['AgDSCore']>
  LazyAgDSCoreProvider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
  LazyAgdscoreprovider: LazyComponent<typeof import("agds-vue")['AgDSCoreProvider']>
  LazyAgDSDatePicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
  LazyAgdsdatepicker: LazyComponent<typeof import("agds-vue")['AgDSDatePicker']>
  LazyAgDSDetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
  LazyAgdsdetails: LazyComponent<typeof import("agds-vue")['AgDSDetails']>
  LazyAgDSDirectionButton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
  LazyAgdsdirectionbutton: LazyComponent<typeof import("agds-vue")['AgDSDirectionButton']>
  LazyAgDSDirectionLink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
  LazyAgdsdirectionlink: LazyComponent<typeof import("agds-vue")['AgDSDirectionLink']>
  LazyAgDSDivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
  LazyAgdsdivider: LazyComponent<typeof import("agds-vue")['AgDSDivider']>
  LazyAgDSDrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
  LazyAgdsdrawer: LazyComponent<typeof import("agds-vue")['AgDSDrawer']>
  LazyAgDSDropdownMenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
  LazyAgdsdropdownmenu: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenu']>
  LazyAgDSDropdownMenuButton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
  LazyAgdsdropdownmenubutton: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuButton']>
  LazyAgDSDropdownMenuDivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
  LazyAgdsdropdownmenudivider: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuDivider']>
  LazyAgDSDropdownMenuGroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
  LazyAgdsdropdownmenugroup: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuGroup']>
  LazyAgDSDropdownMenuItem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
  LazyAgdsdropdownmenuitem: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItem']>
  LazyAgDSDropdownMenuItemLink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
  LazyAgdsdropdownmenuitemlink: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemLink']>
  LazyAgDSDropdownMenuItemRadio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
  LazyAgdsdropdownmenuitemradio: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuItemRadio']>
  LazyAgDSDropdownMenuPanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
  LazyAgdsdropdownmenupanel: LazyComponent<typeof import("agds-vue")['AgDSDropdownMenuPanel']>
  LazyAgDSExternalLinkCallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
  LazyAgdsexternallinkcallout: LazyComponent<typeof import("agds-vue")['AgDSExternalLinkCallout']>
  LazyAgDSFeatureLinkList: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
  LazyAgdsfeaturelinklist: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkList']>
  LazyAgDSFeatureLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
  LazyAgdsfeaturelinklistitem: LazyComponent<typeof import("agds-vue")['AgDSFeatureLinkListItem']>
  LazyAgDSField: LazyComponent<typeof import("agds-vue")['AgDSField']>
  LazyAgdsfield: LazyComponent<typeof import("agds-vue")['AgDSField']>
  LazyAgDSFieldContainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
  LazyAgdsfieldcontainer: LazyComponent<typeof import("agds-vue")['AgDSFieldContainer']>
  LazyAgDSFieldHint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
  LazyAgdsfieldhint: LazyComponent<typeof import("agds-vue")['AgDSFieldHint']>
  LazyAgDSFieldLabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
  LazyAgdsfieldlabel: LazyComponent<typeof import("agds-vue")['AgDSFieldLabel']>
  LazyAgDSFieldMessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
  LazyAgdsfieldmessage: LazyComponent<typeof import("agds-vue")['AgDSFieldMessage']>
  LazyAgDSFieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
  LazyAgdsfieldset: LazyComponent<typeof import("agds-vue")['AgDSFieldset']>
  LazyAgDSFileUpload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
  LazyAgdsfileupload: LazyComponent<typeof import("agds-vue")['AgDSFileUpload']>
  LazyAgDSFilterSidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
  LazyAgdsfiltersidebar: LazyComponent<typeof import("agds-vue")['AgDSFilterSidebar']>
  LazyAgDSFlex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
  LazyAgdsflex: LazyComponent<typeof import("agds-vue")['AgDSFlex']>
  LazyAgDSFooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
  LazyAgdsfooter: LazyComponent<typeof import("agds-vue")['AgDSFooter']>
  LazyAgDSFooterDivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
  LazyAgdsfooterdivider: LazyComponent<typeof import("agds-vue")['AgDSFooterDivider']>
  LazyAgDSFormStack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
  LazyAgdsformstack: LazyComponent<typeof import("agds-vue")['AgDSFormStack']>
  LazyAgDSGlobalAlert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
  LazyAgdsglobalalert: LazyComponent<typeof import("agds-vue")['AgDSGlobalAlert']>
  LazyAgDSGroupedFields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
  LazyAgdsgroupedfields: LazyComponent<typeof import("agds-vue")['AgDSGroupedFields']>
  LazyAgDSHeader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
  LazyAgdsheader: LazyComponent<typeof import("agds-vue")['AgDSHeader']>
  LazyAgDSHeading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
  LazyAgdsheading: LazyComponent<typeof import("agds-vue")['AgDSHeading']>
  LazyAgDSH1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
  LazyAgdsh1: LazyComponent<typeof import("agds-vue")['AgDSH1']>
  LazyAgDSH2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
  LazyAgdsh2: LazyComponent<typeof import("agds-vue")['AgDSH2']>
  LazyAgDSH3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
  LazyAgdsh3: LazyComponent<typeof import("agds-vue")['AgDSH3']>
  LazyAgDSH4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
  LazyAgdsh4: LazyComponent<typeof import("agds-vue")['AgDSH4']>
  LazyAgDSH5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
  LazyAgdsh5: LazyComponent<typeof import("agds-vue")['AgDSH5']>
  LazyAgDSH6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
  LazyAgdsh6: LazyComponent<typeof import("agds-vue")['AgDSH6']>
  LazyAgDSIcon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
  LazyAgdsicon: LazyComponent<typeof import("agds-vue")['AgDSIcon']>
  LazyAgDSInpageNav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
  LazyAgdsinpagenav: LazyComponent<typeof import("agds-vue")['AgDSInpageNav']>
  LazyAgDSLinkList: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
  LazyAgdslinklist: LazyComponent<typeof import("agds-vue")['AgDSLinkList']>
  LazyAgDSLinkListItem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
  LazyAgdslinklistitem: LazyComponent<typeof import("agds-vue")['AgDSLinkListItem']>
  LazyAgDSListItem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
  LazyAgdslistitem: LazyComponent<typeof import("agds-vue")['AgDSListItem']>
  LazyAgDSLoadingBlanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
  LazyAgdsloadingblanket: LazyComponent<typeof import("agds-vue")['AgDSLoadingBlanket']>
  LazyAgDSMainNav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
  LazyAgdsmainnav: LazyComponent<typeof import("agds-vue")['AgDSMainNav']>
  LazyAgDSModal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
  LazyAgdsmodal: LazyComponent<typeof import("agds-vue")['AgDSModal']>
  LazyAgDSNotificationBadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
  LazyAgdsnotificationbadge: LazyComponent<typeof import("agds-vue")['AgDSNotificationBadge']>
  LazyAgDSOrderedList: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
  LazyAgdsorderedlist: LazyComponent<typeof import("agds-vue")['AgDSOrderedList']>
  LazyAgDSPageAlert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
  LazyAgdspagealert: LazyComponent<typeof import("agds-vue")['AgDSPageAlert']>
  LazyAgDSPageContent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
  LazyAgdspagecontent: LazyComponent<typeof import("agds-vue")['AgDSPageContent']>
  LazyAgDSPagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
  LazyAgdspagination: LazyComponent<typeof import("agds-vue")['AgDSPagination']>
  LazyAgDSPaginationButtons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
  LazyAgdspaginationbuttons: LazyComponent<typeof import("agds-vue")['AgDSPaginationButtons']>
  LazyAgDSProgressIndicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
  LazyAgdsprogressindicator: LazyComponent<typeof import("agds-vue")['AgDSProgressIndicator']>
  LazyAgDSProse: LazyComponent<typeof import("agds-vue")['AgDSProse']>
  LazyAgdsprose: LazyComponent<typeof import("agds-vue")['AgDSProse']>
  LazyAgDSRadio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
  LazyAgdsradio: LazyComponent<typeof import("agds-vue")['AgDSRadio']>
  LazyAgDSRadioGroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
  LazyAgdsradiogroup: LazyComponent<typeof import("agds-vue")['AgDSRadioGroup']>
  LazyAgDSSearchBox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
  LazyAgdssearchbox: LazyComponent<typeof import("agds-vue")['AgDSSearchBox']>
  LazyAgDSSearchBoxButton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
  LazyAgdssearchboxbutton: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxButton']>
  LazyAgDSSearchBoxInput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
  LazyAgdssearchboxinput: LazyComponent<typeof import("agds-vue")['AgDSSearchBoxInput']>
  LazyAgDSSearchInput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
  LazyAgdssearchinput: LazyComponent<typeof import("agds-vue")['AgDSSearchInput']>
  LazyAgDSSectionAlert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
  LazyAgdssectionalert: LazyComponent<typeof import("agds-vue")['AgDSSectionAlert']>
  LazyAgDSSectionContent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
  LazyAgdssectioncontent: LazyComponent<typeof import("agds-vue")['AgDSSectionContent']>
  LazyAgDSSelect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
  LazyAgdsselect: LazyComponent<typeof import("agds-vue")['AgDSSelect']>
  LazyAgDSSideNav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
  LazyAgdssidenav: LazyComponent<typeof import("agds-vue")['AgDSSideNav']>
  LazyAgDSSkipLinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
  LazyAgdsskiplinks: LazyComponent<typeof import("agds-vue")['AgDSSkipLinks']>
  LazyAgDSStack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
  LazyAgdsstack: LazyComponent<typeof import("agds-vue")['AgDSStack']>
  LazyAgDSSubNav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
  LazyAgdssubnav: LazyComponent<typeof import("agds-vue")['AgDSSubNav']>
  LazyAgDSSummaryList: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
  LazyAgdssummarylist: LazyComponent<typeof import("agds-vue")['AgDSSummaryList']>
  LazyAgDSSummaryListItem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
  LazyAgdssummarylistitem: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItem']>
  LazyAgDSSummaryListItemAction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
  LazyAgdssummarylistitemaction: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemAction']>
  LazyAgDSSummaryListItemDescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
  LazyAgdssummarylistitemdescription: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemDescription']>
  LazyAgDSSummaryListItemTerm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
  LazyAgdssummarylistitemterm: LazyComponent<typeof import("agds-vue")['AgDSSummaryListItemTerm']>
  LazyAgDSSwitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
  LazyAgdsswitch: LazyComponent<typeof import("agds-vue")['AgDSSwitch']>
  LazyAgDSTab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
  LazyAgdstab: LazyComponent<typeof import("agds-vue")['AgDSTab']>
  LazyAgDSTable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
  LazyAgdstable: LazyComponent<typeof import("agds-vue")['AgDSTable']>
  LazyAgDSTableBody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
  LazyAgdstablebody: LazyComponent<typeof import("agds-vue")['AgDSTableBody']>
  LazyAgDSTableCaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
  LazyAgdstablecaption: LazyComponent<typeof import("agds-vue")['AgDSTableCaption']>
  LazyAgDSTableCell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
  LazyAgdstablecell: LazyComponent<typeof import("agds-vue")['AgDSTableCell']>
  LazyAgDSTableHead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
  LazyAgdstablehead: LazyComponent<typeof import("agds-vue")['AgDSTableHead']>
  LazyAgDSTableHeader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
  LazyAgdstableheader: LazyComponent<typeof import("agds-vue")['AgDSTableHeader']>
  LazyAgDSTableHeaderSortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
  LazyAgdstableheadersortable: LazyComponent<typeof import("agds-vue")['AgDSTableHeaderSortable']>
  LazyAgDSTableRow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
  LazyAgdstablerow: LazyComponent<typeof import("agds-vue")['AgDSTableRow']>
  LazyAgDSTableScroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
  LazyAgdstablescroller: LazyComponent<typeof import("agds-vue")['AgDSTableScroller']>
  LazyAgDSTabList: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
  LazyAgdstablist: LazyComponent<typeof import("agds-vue")['AgDSTabList']>
  LazyAgDSTabPanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
  LazyAgdstabpanel: LazyComponent<typeof import("agds-vue")['AgDSTabPanel']>
  LazyAgDSTabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
  LazyAgdstabs: LazyComponent<typeof import("agds-vue")['AgDSTabs']>
  LazyAgDSTag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
  LazyAgdstag: LazyComponent<typeof import("agds-vue")['AgDSTag']>
  LazyAgDSTags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
  LazyAgdstags: LazyComponent<typeof import("agds-vue")['AgDSTags']>
  LazyAgDSText: LazyComponent<typeof import("agds-vue")['AgDSText']>
  LazyAgdstext: LazyComponent<typeof import("agds-vue")['AgDSText']>
  LazyAgDSTextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
  LazyAgdstextarea: LazyComponent<typeof import("agds-vue")['AgDSTextarea']>
  LazyAgDSTextInput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
  LazyAgdstextinput: LazyComponent<typeof import("agds-vue")['AgDSTextInput']>
  LazyAgDSTextLink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
  LazyAgdstextlink: LazyComponent<typeof import("agds-vue")['AgDSTextLink']>
  LazyAgDSTextLinkExternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
  LazyAgdstextlinkexternal: LazyComponent<typeof import("agds-vue")['AgDSTextLinkExternal']>
  LazyAgDSTimeInput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
  LazyAgdstimeinput: LazyComponent<typeof import("agds-vue")['AgDSTimeInput']>
  LazyAgDSTimePicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
  LazyAgdstimepicker: LazyComponent<typeof import("agds-vue")['AgDSTimePicker']>
  LazyAgDSToggleButton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
  LazyAgdstogglebutton: LazyComponent<typeof import("agds-vue")['AgDSToggleButton']>
  LazyAgDSUnorderedList: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
  LazyAgdsunorderedlist: LazyComponent<typeof import("agds-vue")['AgDSUnorderedList']>
  LazyAgDSVisuallyHidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
  LazyAgdsvisuallyhidden: LazyComponent<typeof import("agds-vue")['AgDSVisuallyHidden']>
  LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyMDC: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
  LazyMDCCached: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
  LazyMDCRenderer: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
  LazyMDCSlot: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+mdc@0.20.2_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
  LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@24.12.0_@vue+compiler-sfc@3.5.29_better-s_8c323be4ace4b7004f42fd86bae437ff/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
