export { default as AGDSTable } from './AGDSTable.vue';
export { default as AGDSTableBody } from './AGDSTableBody.vue';
export { default as AGDSTableCaption } from './AGDSTableCaption.vue';
export { default as AGDSTableHead } from './AGDSTableHead.vue';
export { default as AGDSTableHeader } from './AGDSTableHeader.vue';
export { default as AGDSTableHeaderSortable } from './AGDSTableHeaderSortable.vue';
export { default as AGDSTableCell } from './AGDSTableCell.vue';
export { default as AGDSTableRow } from './AGDSTableRow.vue';
export { default as AGDSTableScroller } from './AGDSTableScroller.vue';
